### ISSUE TITLE
ES6 Rewrite

### ISSUE THREAD

**Issue by druti** [zenoamaro/react-quill#100]
I'm planning on rewriting this in ES6. Anything I should know about before investing the time?

**Comment by colegeissinger** [comment]
Curious what the progress is on the ES6 rewrite? I'm just now learning how to utilize this in a project I'm working on and enjoying it so far!

**Comment by igolden** [comment]
+1

**Comment by tausch86** [comment]
+1

**Comment by tausch86** [comment]
@druti @colegeissinger @igolden check out https://github.com/zenoamaro/react-quill/pull/129

**Comment by zenoamaro** [comment]
> Curious what the progress is on the ES6 rewrite? I'm just now learning how to utilize this in a project I'm working on and enjoying it so far!

I expect the ES6 rewrite to be completely unnoticeable, so by all means, don't let that stop you.

**Comment by zenoamaro** [comment]
ReactQuill v2 is not fully TypeScript and React16+. Please try the latest `v2.0.0-beta`!
