### ISSUE TITLE
Set contents with Delta

### ISSUE THREAD

**Issue by druti** [zenoamaro/react-quill#101]
Add support for setting content with Delta.

**Comment by drock07** [comment]
Any update on this? 

I'd love to be able to store Deltas in my database instead of raw HTML, but without this, I'm not sure how to go about doing that. 

Additionally, I'm using react-quill with redux-form, and they would work really well together if we could set the content with a Delta.

**Comment by alexkrolick** [comment]
This will probably be the next feature. Quick poll - how do you want the API to work? Do you want setContents exposed directly, or do you want the value prop to take Deltas for the declarative API?

**Comment by alexkrolick** [comment]
Also note that you can access `getEditor().setContents(...)` with a ref to the ReactQuill right now.

**Comment by drock07** [comment]
Would it be possible to do some type checking on value? If it's a string, set the HTML, and if it's an object, attempt to setContents?

The ideal for my use case would be to just set value with the Delta.

**Comment by zenoamaro** [comment]
@drock07, have a look at the proposed Delta API.

**Comment by drock07** [comment]
Those changes are definitely sufficient for my needs. Thank you!

**Comment by ziogaschr** [comment]
@drock07 can you share an example of how you use it with redux-form please?
