### ISSUE TITLE
Update Quill v0.21 to Quill v1.0

### ISSUE THREAD

**Issue by Enijar** [zenoamaro/react-quill#107]
Since v1.0 of Quill is [now in beta](http://beta.quilljs.com/), it would be a good idea to start looking into upgrading the dependency from v0.21 to v1.0.

Let me know your thoughts.

**Comment by wwwdata** [comment]
When upgrading to 1.0 the mixins should also be removed, see: https://facebook.github.io/react/blog/2016/07/13/mixins-considered-harmful.html

**Comment by alexkrolick** [comment]
See PR #106. It should be noted that the wrapper may not be possible to upgrade in place from 0.21 to 1.0.

Moving away from the mixin architecture is a separate issue.

**Comment by alexkrolick** [comment]
#106 could use review now that 1.0.0 is the stable version

**Comment by zenoamaro** [comment]
ReactQuill is now updated to Quill 1.0. Dupe of #113.
