### ISSUE TITLE
Is it possible to insert some text?

### ISSUE THREAD

**Issue by thomas-jeepe** [zenoamaro/react-quill#109]
Right now Im building an app and I'm using react-quill. One of the features is adding snippets to whatever you are editing. Right now I just have the html string and appending the snippet to it. However adding the snippet at the cursor position would be best.

I tried getting the quill editor instance so that I could edit it, however using getEditor() returned null. Using createEditor threw a Quill error. And I can't seem to get the instance so I an get the selection and insert text.

**Comment by alexkrolick** [comment]
See example of how to access Quill backing instance here: https://codepen.io/alexkrolick/pen/YNmGar?editors=0011
