### ISSUE TITLE
Expose focus and blur events

### ISSUE THREAD

**Issue by justindra** [zenoamaro/react-quill#110]
It would be great if you could set a class to the main div so that we can style it to set it when it is focused. Or can expose an `onFocus` and `onBlur` method to the props?

**Comment by zenoamaro** [comment]
I agree, `onFocus` and `onBlur` should be also exposed by ReactQuill.

It's unlikely that we'll add classes automatically, but the above should be enough to implement it.

**Comment by zenoamaro** [comment]
@justindra, please verify that the events, as proposed in #246, does what you need. Thanks!

**Comment by justindra** [comment]
@zenoamaro That is perfect! Will close

**Comment by zenoamaro** [comment]
I like your excitement :) But you can let the PR close the ticket itself when it is merged after review.
