### ISSUE TITLE
How do you create custom toolbar buttons in react-quill?

### ISSUE THREAD

**Issue by akshaygoyal88** [zenoamaro/react-quill#111]
I am trying to create a custom toolbar button which will open up a modal and user can select images from their when image selected it should be inserted in the content.
So how how can I customize and register a module like [this](http://quilljs.com/docs/modules/toolbar/)  with react-quill ?
Thanks in Advance.

**Comment by alexkrolick** [comment]
In the next version of Quill (1.0), you can pass the toolbar and modules config into the initializer:

See this fork for a 1.0 compatible version: https://github.com/alexkrolick/react-quill/releases/tag/v2.0.0-rc.1

**Comment by zenoamaro** [comment]
This is supported in the latest version, and only needs to be enabled in the toolbar. See [the Quill toolbar documentation] (http://quilljs.com/docs/modules/toolbar) for information on how to do this.

**Comment by Dagur** [comment]
The documentation is very unclear and I've been wracking my brain over this all day. 

So far I've come up with this:
`var EmailEditor = React.createClass({
    modules: {
        toolbar: {
            container: ['bold', 'italic', 'custom'],  // Selector for toolbar container
            handlers: {
                'custom': function () { alert( "test"); }
            }
        }
    },

    render: function() {
        return (
          <div className="text-editor">
            <ReactQuill onChange={this.props.onChange}
                        modules={this.modules}>                
                <div key="editor"
                     ref="editor"
                     className="quill-contents"                     
                     dangerouslySetInnerHTML={{__html:this.props.value}} />
            </ReactQuill>
        </div>
    );
},`

Where do I put the custom HTML for the new button?

**Comment by Dagur** [comment]
I think I finally figured it out

```
var EmailEditor = React.createClass({
    modules: {
        toolbar: {
            container: "#toolbar",
            handlers: {
                "insertName": function () {                                       
                    this.quill.insertText(this.quill.getSelection().index, "test");                    
                }
            }
        }
    },
    render: function() {
        return (
          <div className="text-editor">
              <div id="toolbar">
                  <button className="ql-bold"></button>
                  <button className="ql-italic"></button>
                  <button className="ql-insertName">Name</button>
              </div>  
              <ReactQuill onChange={this.props.onChange} modules={this.modules}>                                              
                <div key="editor"                     
                     ref="editor"
                     className="quill-contents"                     
                     dangerouslySetInnerHTML={{__html:this.props.value}}></div>
              </ReactQuill>
        </div>);
    }
});
```

**Comment by alexkrolick** [comment]
Added a [new example](https://github.com/zenoamaro/react-quill/blob/master/README.md#html-toolbar) and a [Codepen demo](https://codepen.io/alexkrolick/pen/gmroPj?editors=0010) to the README

![kapture 2017-03-03 at 0 01 17](https://cloud.githubusercontent.com/assets/1571667/23542929/984c2b68-ffa4-11e6-811c-cc2b62634887.gif)

**Comment by sam201994** [comment]
How do I add custom tags to the toolbar. I want to add <hr /> tag to the toolbar. or is there any other editor which has this feature with other basics one

**Comment by alexkrolick** [comment]
@sam201994 

You can use the custom toolbar API here: https://github.com/zenoamaro/react-quill#custom-toolbar

**Comment by avdbg** [comment]
@Dagur I think it's really easy. Just use your first code and add some CSS to change the "custom" button's content. Like this:  
```
.ql-custom:before {
    display: inline-block;
    font: normal normal normal 14px/1 FontAwesome;
    font-size: inherit;
    text-rendering: auto;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    transform: translate(0, 0);

    content: "\f0c7";
}
```
The button will become a floppy icon. The code is copied from font-awesome.css.  
There is a problem is that I do not know whether the button's class will change in the future version. I hope it will not.

**Comment by alexkrolick** [comment]
Changing the CSS classes would be considered worthy of a semver major bump, so you should be safe ☺️

**Comment by volkandkaya** [comment]
@alexkrolick the insert star demo was great. I was just wondering how I would step it up by sending some arguments to the function (custom font selector so I need to send the value selected).

**Comment by RDeevice** [comment]
# @alexkrolick `xx`### ### _**sss**_[ss](url)

- #374

**Comment by KiranVH** [comment]
Does anyone know how to create dropdown kind of popup when clicking on custom created toolbar button

**Comment by Himanshu-Negi-Dev** [comment]
- [ ]   ###

- [ ] 

- [ ] 

- [ ]

**Comment by twigs67** [comment]
Can we can an updated example for functional components?

**Comment by stefan-bozinovski** [comment]
I was hoping for an example for functional components as well.

**Comment by PedroBarbosaSw** [comment]
Any example? lol
