### ISSUE TITLE
Official Update to v1.0

### ISSUE THREAD

**Issue by igolden** [zenoamaro/react-quill#113]
Quill has officially released v1.0 as stable, and now there's a mismatch between versions.

Some common methods are no longer available in Quill, ie getHTML is now getContents and delivered as a Delta. It'd be nice to see an official update to 1.0 to get this component stable.

I've seen a couple branches with 1.0 merged in, maybe we can merge one of those in to get this started and finished quickly. If I can get a confirmation you'd merge in a branch of mine, I'd be happy to get this updated to v1.0 this week - as I'm using this in a production project.

Thanks again - happy quill-ing!

**Comment by mikecousins** [comment]
Is this project still alive? I wonder if we should fork this and get it done and published somewhere new? This is pretty badly needed.

**Comment by djyde** [comment]
have a try https://github.com/djyde/React-Quill

**Comment by mikecousins** [comment]
Yeah, I ended up just writing a simple component into our app already. Nice package :)

**Comment by alexkrolick** [comment]
See #106 - I've updated my fork to use Quill 1.0.0 which was released today

**Comment by alexkrolick** [comment]
Anyone know what's going on here? If the maintenance of this package is no longer possible would it make sense to move that responsibility to a Github organization (perhaps the core quill organization)?

cc @igolden @zenoamaro

**Comment by zenoamaro** [comment]
Thanks to the incredible work of @clemmy and @alexrolick, ReactQuill is now updated to Quill 1.0. See Pull Request #106 for details.

@alexkrolick I cannot hide it has been hard to find the time and dedication lately. Would you have someone in mind re: change of ownership?

**Comment by dropfen** [comment]
hey @zenoamaro , this is great, but on NPM still the old version is distributed.

**Comment by alexkrolick** [comment]
@zenoamaro As a starting point, how about a react-quill Github org? You might also contact @jhchen to see what he thinks about creating a more official group for wrappers, Parchment plugins, etc.

**Comment by mouhsinelonly** [comment]
please update the NPM version

**Comment by tomaash** [comment]
My NPM now looks like this to be able to use Quill 1.0.2: 
`"react-quill": "github:zenoamaro/react-quill"`
I install from master, and pray that it won't break. Please release a NPM version with this update :)

**Comment by alexkrolick** [comment]
@zenoamaro it's probably safe to bump the version because semver should prevent auto-updating to an incompatible API...

**Comment by Gorb** [comment]
Any chance of a vague ETA on this? I appreciate the lack of time to spend on the project but I need to know whether I can use NPM for the up-to-date references (Quill v1.0, etc) or I have to git pull and build something locally. Nothing new on CDNJS either.

**Comment by Silverwolf90** [comment]
Seems like duplicate issues are getting directed to this thread but haven't had an official response by @zenoamaro as to the state of the npm version. Is there a specific reason why it hasn't been updated? Or is it just maintenance that hasn't happened yet?

Sorry to be another person clogging notifications, very much appreciate all the hard work that has gone into this!

**Comment by zenoamaro** [comment]
It is tasks for release that didn't yet happen:

- testing that all features are still working – ie. events and ranges changed formats, and there are more coming.

- testing what is actually deprecated – ie. toolbar is marked as deprecated in v1 PR, but as far as I could see Quill still supports it, just like before. 

- documentation on actual deprecated features and migration steps.

Backwards compatibility was never a problem as ^0.X versions get treated just like major versions by semver – shipping a good release is the point, which is in-progress.

**Comment by altayaydemir** [comment]
@zenoamaro you can publish a beta or rc version maybe?

**Comment by dropfen** [comment]
@altayaydemir or alpha ) Anyway, its better then rely on the repo directly

**Comment by alexkrolick** [comment]
Updated the docs in latest PR #134.

Would be nice if someone could take a look at the tests and see what needs to be done per Zeno's comments.

**Comment by zenoamaro** [comment]
I'm happy to announce that an updated NPM package is now available in the beta channel: 
```
npm install react-quill@v1.0.0-beta-1
```
There may be other breaking changes leading to `v1.0.0`, however we'll try to reduce that to the minimum.

Future beta versions will be announced on this thread in the same way.

**Comment by zenoamaro** [comment]
Short update for those only following this thread –

the latest published package version is `v1.0.0-rc.2`.

Install it as such: `npm install react-quill@v1.0.0-rc.2`.
