### ISSUE TITLE
Adding different Font and colors

### ISSUE THREAD

**Issue by satyadeeproat** [zenoamaro/react-quill#115]
Anybody tried out adding different and colors. I guess in most editor we have the features of changing font and also coloring ?

**Comment by alexkrolick** [comment]
You can do this in Quill if you enable the format and toolbar items: https://quilljs.com/docs/modules/toolbar/

May want to wait until 1.0.0 is released because the API for the toolbar has changed since 0.21

**Comment by zenoamaro** [comment]
This can be done on the latest version (releasing soon). Please refer to [Upgrading to React-Quill v1.0.0](https://github.com/zenoamaro/react-quill/blob/f5717cd50b1371359c64fc74a789700d8e9e46a7/README.md#upgrading-to-react-quill-v1-0-0) for required changes, and to the [Quill toolbar format](http://quilljs.com/docs/modules/toolbar) for information on toolbar configuration.
