### ISSUE TITLE
Is project alive?

### ISSUE THREAD

**Issue by yankouskia** [zenoamaro/react-quill#116]
Is project alive? Are you going to support it? And what about xss in it?

**Comment by Gattermeier** [comment]
@zenoamaro

**Comment by tausch86** [comment]
@yankouskia @Gattermeier see https://github.com/zenoamaro/react-quill/pull/129

**Comment by andrewmclagan** [comment]
...hello?

**Comment by zenoamaro** [comment]
Apologies for the delay. Please refer to [the README](https://github.com/zenoamaro/react-quill/blob/f5717cd50b1371359c64fc74a789700d8e9e46a7/README.md) for recent announcements.
