### ISSUE TITLE
quill.js:7634 Uncaught TypeError: Cannot read property 'node' of undefined

### ISSUE THREAD

**Issue by jbgarr** [zenoamaro/react-quill#117]
This error happens when trying to call `focus()` on a ref to the `ReactQuill` component.

My general use case is: I have a `ReactQuill` component that takes a comment, the comment is submitted, then the content is cleared. This clearing of the content seems to cause this issue. Here is my basic setup:

```
    <ReactQuill
        theme='snow'
        value={this.state.content}
        onChange={this.onContentChange}
        ref="quillEditor">
        <ReactQuill.Toolbar key="toolbar"
          ref="toolbar"
          items={toolbar} />
        <div key="editor"
          ref="editor"
          className="quill-contents"
          onClick={this.focusOnEditor}
          onFocus={this.onEditorFocus}
          onBlur={this.onEditorBlur} />
      </ReactQuill>
```

To reproduce the issue use the structure above, then add a "Clear" button that sets the state.content to '' (an empty string). Set the `focusOnEditor` function to something like this:

```
focusOnEditor = () => {
  this.refs.quillEditor.getEditor().focus();
}
```

Now to see the error add some content, then click the 'Clear' button, then click back into the editor, but click closer to the edge of the editor (where it's padded, and not in the middle of the input). This should cause the error to be thrown.

**Comment by alexkrolick** [comment]
Does this still happen on master/the release candidate? Quill has become stable since then.
