### ISSUE TITLE
Inserting custom Tag(with html) and corresponding toolbar Icon ?

### ISSUE THREAD

**Issue by pravin-d** [zenoamaro/react-quill#119]
I'm trying to insert a React Tag into the editor's content (maybe to start of with it can be pure html). The  Tag will a label with some innerHTML and data attr. The Tag can either be inserted by a special button(not part of toolbar) or by a toolbar item. 
The latest quill has a module called clipboard which does what I need. However there is no npm for clipboard module so that I can include it.
I checked the documentation and there is no provision to insert the html at a given index. 
My question
1. Can I just download clipboard module and register ? 
2. Is there a function in react-quill or the version of quill its using.. which I can use ?

**Comment by alexkrolick** [comment]
You can pass modules directly in the configuration object as of the update to Quill 1.0: https://github.com/zenoamaro/react-quill#example

Does that work for you?

**Comment by pravin-d** [comment]
Thanks man.. The problem was that I was using react-quill npm. The latest version over there is react-quil@0.4.1 . Would it be possible to update the same on npm mode packages ?

**Comment by zenoamaro** [comment]
@pravin-d for now, try to install the package from github:

    npm install zenoamaro/react-quill

Once this version is stabilized, I will publish a new one.

**Comment by liSong5713** [comment]
it still dosen't work

**Comment by izkrivera** [comment]
I am also interested in this feature! 

npm install zenoamaro/react-quill
...

import ReactQuill from 'react-quill';

ERROR in ./~/quill/index.js
Module build failed: Error: ENOENT: no such file or directory, open '/[pathToProject]/node_modules/quill/index.js'
 @ ./~/react-quill/src/index.js 8:12-28

**Comment by zenoamaro** [comment]
Please refer to #113 for update announcements on the official package.
