### ISSUE TITLE
PlaceHolder and 'selection-change' event?

### ISSUE THREAD

**Issue by Predjo** [zenoamaro/react-quill#12]
Is there a way to add a placeholder text to the editor, and also is there a way to listen to the 'selection-change' event?

**Comment by zenoamaro** [comment]
I'll add a callback for the `selection-change` event pretty soon.

I'll think about providing a placeholder prop for the editor, but in the mean time I can think of a few things that you could do:

- Override the editor element in a custom component to provide a placeholder-ed component instead. The core functionality has been split over into `ReactQuill.Mixin` but you could just as well copy-paste the whole `Component` implementation into your sources and edit it as you please.

- Or maybe use the css `:empty` selector to display a `::before` pseudo-element with your placeholder text as `content`. I think this could fail though, unless the editor has zero content at all.

**Comment by Predjo** [comment]
Any ETA on the selection-change event?

**Comment by zenoamaro** [comment]
Latest version introduces `onChangeSelection`, which should be what you need.

I'm still interested in the placeholder feature though. Could you open another issue for that?
