### ISSUE TITLE
Documentation updates related to Quill 1.0

### ISSUE THREAD

**Issue by alexkrolick** [zenoamaro/react-quill#120]
As of the upgrade to Quill v1.0.3 there are some parts of the documentation that should be updated:
- Document upgrade path 
  - breaking API changes
  - converting to new toolbar format
- Quick Start section in the README should be updated to prefer the Quill 1.0 configuration for the toolbar, currently under this heading: https://github.com/zenoamaro/react-quill#using-with-quill-10

**Comment by dropfen** [comment]
Yeah, this could help. 
Currently, when my Component gets re-rendered a new toolbar is added. I am using the the master branch at the moment..

**Comment by zenoamaro** [comment]
Fixed in the latest version. Please refer to [Upgrading to React-Quill v1.0.0](https://github.com/zenoamaro/react-quill/blob/f5717cd50b1371359c64fc74a789700d8e9e46a7/README.md#upgrading-to-react-quill-v1-0-0) for a list of required changes.
