### ISSUE TITLE
update with npm not working

### ISSUE THREAD

**Issue by mouhsinelonly** [zenoamaro/react-quill#121]
i tried to update the package with npm update but with no luck

**Comment by alexkrolick** [comment]
The NPM version hasn't been bumped yet due to a need to specify a migration path for existing installs.

@zenoamaro on the other hand, I bumped the major version in package.json, so it wouldn't break semver to push an update to NPM.

**Comment by mouhsinelonly** [comment]
existing installs could stay on the old version, as no one is forced to make an update ?

**Comment by jhaddow** [comment]
Any chance you can branch off the current version that is published on npm so we can look through the source code of that version here on GitHub?

**Comment by tomaash** [comment]
@zenoamaro can you please release current master to NPM? As major version has been updated already in package.json, it should not break semver for anyone.

**Comment by zenoamaro** [comment]
Duplicate of #113.
