### ISSUE TITLE
onChangeSelection with range of HTML 

### ISSUE THREAD

**Issue by parduhn** [zenoamaro/react-quill#126]
Hi,
is there a way to get the HTML range from quill?

For example the text would be: '12345'. If the cursor is placed after the 3 the range would be 3. However, the HTML format would look like this: '`<div>12345</div>`' and the real HTML position would be 8. 

Is there a way to get the HTML position?

Cheers,
Hayo

**Comment by jhaddow** [comment]
I have struggled with this as well.

**Comment by zenoamaro** [comment]
At a glance, there doesn't seem to be an easy way to accomplish that.

But ReactQuill does not manage the selection, everything is done by Quill, so unfortunately there is little we can do here. 

It would be best if you asked this question over to [Quill](https://github.com/quilljs/quill/issues) itself, where they may come up with a solution to your need.
