### ISSUE TITLE
The version of react-quill on www.npmjs.com is too old

### ISSUE THREAD

**Issue by zhanxia** [zenoamaro/react-quill#127]
when i run npm install in my project,The version of react-quill in my node_modules is 0.4.1,so i can't use the image local upload feature in my project.How do I use the image local upload feature?

**Comment by alexkrolick** [comment]
Duplicate of https://github.com/zenoamaro/react-quill/issues/113

**Comment by zenoamaro** [comment]
Please see #113 for release updates.
