### ISSUE TITLE
webpack build issue

### ISSUE THREAD

**Issue by xingkaixin** [zenoamaro/react-quill#13]
WARNING in ./~/react-quill/~/quill/dist/quill.js
Critical dependencies:
1:538-546 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/react-quill/~/quill/dist/quill.js 1:538-546

~~~

**Comment by zenoamaro** [comment]
Hi, thanks for reporting.

Unfortunately this is not an issue with react-quill, and so it's unavoidable.

See #7 for explanation and directions on how to silence this warning.

**Comment by xingkaixin** [comment]
I got it,thx~
