### ISSUE TITLE
defaultValue not respected

### ISSUE THREAD

**Issue by Gorb** [zenoamaro/react-quill#132]
I tested with other props (`readOnly={ true }` works, for example) and `defaultValue` doesn't seem to work. I want to be able to pre-populate the editor with the previous state (so users don't have to start from scratch).

Using the npm version (v0.4.1); is the fix to pull the latest from github and compile manually? :/

**Comment by alexkrolick** [comment]
You can point to a version on Github in an NPM package.json like this:

```
    "react-quill": "zenamaro/react-quill#v2.0.1",
```
```
    "react-quill": "alexkrolick/react-quill#v2.0.2",
```

I think the NPM version should be bumped soon, however.

**Comment by Gorb** [comment]
Thanks for that tip, appreciated!

**Comment by sertaconay** [comment]
Isn't NPM version "bumped" yet?

**Comment by alexkrolick** [comment]
You can install with NPM:

```sh
npm install react-quill@1.0.0-beta-1
```

package.json:
```json
{
    "react-quill": "1.0.0-beta-1"
}

**Comment by sertaconay** [comment]
Are you sure that it fixes the problem? Because it doesn't even work in provided [demo pen](http://codepen.io/alexkrolick/pen/xgyOXQ).
Maybe I couldn't make it work. If so, can you provide a working pen that contains example of defaultValue property?

**Comment by sertaconay** [comment]
Ah, OK. I added ```defaultValue``` property but I didn't delete ```value``` property. I tried to use both property at the same time. When I looked at the [source code](https://github.com/zenoamaro/react-quill/blob/master/src/component.js#L112) I realized my mistake. It works now.
