### ISSUE TITLE
Sticky toolbar?

### ISSUE THREAD

**Issue by berndschimmer** [zenoamaro/react-quill#133]
Hi, 
is it possible to add sticky behaviour to the toolbar?
Cheers,
Bernd

**Comment by alexkrolick** [comment]
Yes, you can target `.ql-toolbar` in your CSS

**Comment by berndschimmer** [comment]
I thought of something like https://www.npmjs.com/package/react-sticky. So that it starts being sticky if you scroll down.

**Comment by alexkrolick** [comment]
That is behavior you would want to implement in the container for the editor, not in the editor itself.
