### ISSUE TITLE
Quick start help. Toolbar and style issues.

### ISSUE THREAD

**Issue by acomito** [zenoamaro/react-quill#136]
I have a pretty simple example project but am having trouble getting this fully "quick started":

```
import React from 'react';
import ReactQuill from 'react-quill';


class Index extends React.Component {
	constructor(props) {
		super(props);
		this.handleChange = this.handleChange.bind(this);
	}
	handleChange(text) {
    	     Meteor.call('updateText', text, this.props.thisDocument._id)
  	}
	render() {
		const { thisDocument } = this.props;

		return <div className="Index">
                                <h3>Editor</h3>
				    <ReactQuill
				    	value={thisDocument && thisDocument.body ? thisDocument.body : ''} 
				    	onChange={this.handleChange}
				    />
			  </div>
	}
} 

export default Index;
```

This result is almost exactly what I need, but seems to be conflicting (or non-existent) styles:

![alt tag](http://g.recordit.co/GzlipKmieZ.gif)

I do have these in my main html:

```
<link href="https://cdn.quilljs.com/1.0.0/quill.snow.css" rel="stylesheet">
<link href="https://cdn.quilljs.com/1.0.0/quill.core.css" rel="stylesheet">
```

If I ad snow as the theme, I get this:

<ReactQuill 
   value={thisDocument && thisDocument.body ? thisDocument.body : ''} 
   onChange={this.handleChange}
  theme='snow'
/>

and results in:

![alt tag](http://g.recordit.co/1wkbFcqUDv.gif)

Is this something with my bootstrap styles leaking into quill or am I missing something? I saw a few issues about the NPM package not being up-to-date--- is this related?

I'd really like the toolbar to match the demo: https://zenoamaro.github.io/react-quill/

But it wasn't clear how to get there when I looked at the demo folder and the quick start guide doesn't seem to get your there either.

great package-- I'm hoping to get it up and running soon!

**Comment by alexkrolick** [comment]
The npm version uses pre-1.0 Quill. Try the Github version or this one (PR outstanding): https://github.com/alexkrolick/react-quill/releases/tag/v2.0.2

**Comment by darios2** [comment]
Dont know if you fixed your issued but I had same problem, my path for css was diferent than in guide, this path worked for me 
 <link rel="stylesheet" href="../node_modules/react-quill/node_modules/quill/dist/quill.snow.css">
