### ISSUE TITLE
Problem with clipboard matchers

### ISSUE THREAD

**Issue by berndschimmer** [zenoamaro/react-quill#137]
Hi again :-)

I have a Problem with the clipboard matchers. The matcher is working, but the result is as if the matcher is ignored. Here is my setup.

```
  _formats: [
     "header",
     "bold", "italic", "underline", "strike", "blockquote",
     "list", "bullet",
     "link", "image", "video"
  ]


modules = {
  clipboard: {
       matchers: [
         ['h1', this.customh1]
       ]
     },
     toolbar: {
        container: [
          [{ header: [2,3,false] }, "bold", "italic", "underline"],
          [{ list: "ordered"}, { list: "bullet"}],
          [ "image", "video"]
        ]
      }
}

customh1 (node, delta) {
    return delta.compose(new Delta().retain(delta.length(), { h1: false }));
}
```
My goal is: paste a h1 from Word and the h1 will be ignored or transformed to a p.

What am I doing wrong?

**Comment by alexkrolick** [comment]
This might be something you file upstream in Quill.

**Comment by berndschimmer** [comment]
Yep, here is the solution: https://github.com/quilljs/quill/issues/1161
It is not { h1: false } but { header: false }.
Obvious...
