### ISSUE TITLE
Delta not showing up

### ISSUE THREAD

**Issue by Deelux** [zenoamaro/react-quill#138]
Hi everyone, 

I have been trying to implement React Quill in my project but can't seem to get it working 100%.

To be honest I don't think these are bugs, but more my lack of knowledge about Quill.

1. I can't seem to console.log(delta)
2. How can I display the content of my Quill in my preview window without the html tags?

This is my code:

`
import ReactQuill from 'react-quill';

export default class AddSpark extends Component {
  constructor(props) {
    super(props);

    this.onChange = this.onChange.bind(this);

    this.state ={
      content: '',
    };
  }

onChange(html) {
    this.setState ({ content: html });
      console.log(html)
    }

  render() {
     const events = {
      'text-change': delta => {
        console.log(delta)
      }
    }

    return (
      <div>
      <Col xs={12} md={6}>
        <form ref={(input) => this.sparkForm = input} onSubmit={(e) => this.createSpark(e)}>

            <ControlLabel>Select your city</ControlLabel>
            <select id="formControlsCity" placeholder="Choose your city" onChange={this.onChange} className="form-control" onClick={ moreOptions } ref={(input) => this.city = input}>
              <option value="select">Choose your city</option>
              <option value="Beijing">Beijing</option>
              <option value="Shanghai">Shanghai</option>
              <option value="Chengdu & Chongqing">Chengdu & Chongqing</option>
            </select>
       
            <ControlLabel>Select your person</ControlLabel>
            <select id="formControlsPerson" placeholder="Choose your person" className="form-control" ref={(input) => this.person = input}>
              <option value="select">First select your city</option>
            </select>
    
            <ControlLabel>Select your location</ControlLabel>
            <select id="formControlsLocation" placeholder="Choose your location" className="form-control" ref={(input) => this.location = input}>
              <option value="select">First select your city</option>
            </select>

            <ControlLabel>Title</ControlLabel>
            <input type="text" label="Title" placeholder="Enter your title" className="form-control" ref={(input) => this.title = input}/>
          

            <ControlLabel>Content</ControlLabel>
              <div className='_quill'>
                <ReactQuill
                  theme="snow"
                  ref='editor'
                  onChange={this.onChange}
                  events={events} />
              </div>
              <br />

          <Button type="submit">Submit</Button>
        </form>
      </Col>
      <Col xs={12} md={6}>
      <h3>Preview</h3>

            {this.state.content}
      </Col>

      </div>
  )}
}

`

**Comment by alexkrolick** [comment]
- You need to set the `value` of the editor if you want it to be a controlled input (`value={this.state.html}`)
- you would either want to strip the HTML tags with another library, or override the CSS to make all the classes appear as plain text in your preview area
- See the README for basic and advanced configuration options: https://github.com/zenoamaro/react-quill#use-it-straight-away

**Comment by alexkrolick** [comment]
Also, it looks like you are trying to register the event listener on the Quill instance, so you need to use the API provided for that by Quill: http://quilljs.com/docs/api/#text-change
