### ISSUE TITLE
New Method: getCursorPosition()

### ISSUE THREAD

**Issue by JasonEtco** [zenoamaro/react-quill#139]
Not sure how to implement this, but it would be a big help in determining where to inject new content.

**Comment by alexkrolick** [comment]
Have you looked at the Quill APIs to see if you could achieve that with the wrapped Quill instance?

**Comment by zenoamaro** [comment]
@JasonEtco, the way to get the cursor location is to listen for changes in the selection. 

If you pass a callback to `onChangeSelection`, you will receive a `range` object containing the `index` of the cursor, and the `length` of the selection, if any.
