### ISSUE TITLE
input chinese the editor concent,the letter also came out

### ISSUE THREAD

**Issue by xingkaixin** [zenoamaro/react-quill#14]
this issue occurs in the demo ,I uploaded 2 GIF to describe
![quill-input-chinese-in demo](https://cloud.githubusercontent.com/assets/3390425/8412177/a7678e7a-1eba-11e5-89a0-bc68b9445390.gif)
![quill-input-chinese-in-mylocal-demo](https://cloud.githubusercontent.com/assets/3390425/8412180/ac2f48f8-1eba-11e5-9391-38551efe5064.gif)

**Comment by xingkaixin** [comment]
I'm going to check this  in the morning.

**Comment by zenoamaro** [comment]
Am I understanding correctly? The issue appears in the demo page for react-quill, but not in your own wiring of the component outside of the demo? If so that would point to an issue with events and state. I believe fixing #9 and #10 would also fix this issue.

**Comment by xingkaixin** [comment]
online demo and location app also occurs.I think this issue is not like #9 and #10 .It's a new issue that you type the chinese.

the first gif is online demo
this second is my location app

**Comment by zenoamaro** [comment]
What I mean is that there are some issues with react-quill in [controlled] mode. When you type something, the field is getting stored and then updated back with each keystroke, which, among other annoyances, would close your popups immediately after each update.

I'm not 100% sure so I'm leaving this ticket open.

[controlled]: https://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by zenoamaro** [comment]
The latest release handles events in a different way, so that should take care of your issue. 

Please re-open this issue if still have the same issue.

**Comment by thbgh** [comment]
this problem is still
