### ISSUE TITLE
Toolbar not working on mobile devices

### ISSUE THREAD

**Issue by berndschimmer** [zenoamaro/react-quill#141]
Hi, 
when visiting https://zenoamaro.github.io/react-quill/ with an iPhone and changing anything with the toolbar (font, size, bold etc.) - nothing happens.
The same changes made on http://quilljs.com/ works fine on mobile.
Do you have any clue what it could be?

Bernd

**Comment by alexkrolick** [comment]
I'm not sure the demo is running the latest version, will have to see what that GH pages file is loading.

**Comment by zenoamaro** [comment]
@berndschimmer, I have updated the toolbar in the demo. You can try it again.
