### ISSUE TITLE
Cannot resolve 'file' or 'directory' error when using new react-quill

### ISSUE THREAD

**Issue by hangingchads** [zenoamaro/react-quill#142]
I am writing a component that uses react-quill (pulling the source from GitHub).  Here's what I'm including in package.json:
"quill": "^1.0.2",
    "react": "^15.4.0",
    "react-dom": "^15.4.0",
    "react-quill": "git+https://github.com/zenoamaro/react-quill.git",

When I build the component with webpack:
./node_modules/.bin/webpack -d --watch --config webpack.example.config.js

I get the following error:
Module not found: Error: Cannot resolve 'file' or 'directory' ./../../css-loader/lib/css-base.js

I don't get the error when I use the released version of react-quill (and the older version quill).

Is there something else that I need to include?

**Comment by anaumov** [comment]
I have same issue with
```
../node_modules/react-quill/dist/quill.snow.css
```

**Comment by anaumov** [comment]
I think it's related to https://github.com/zenoamaro/react-quill/issues/74

**Comment by tlerias** [comment]
+1 with

`../node_modules/react-quill/dist/quill.snow.css`

**Comment by zenoamaro** [comment]
This should be fixed in `master`. Can you verify?

Also, CSS files will be bundled properly with the next release.

**Comment by zackify** [comment]
How long until the next release?

**Comment by zenoamaro** [comment]
@zackify see #113
