### ISSUE TITLE
read property 'TYPED_ARRAY_SUPPORT' of undefined on release candidate

### ISSUE THREAD

**Issue by SuperheroUI** [zenoamaro/react-quill#143]
I was having this issue when running react-quill, it would build fine, but would not run in the browser due to: read property 'TYPED_ARRAY_SUPPORT' of undefined. 

I found out this: 

I added this to the webpack config file for the project (not my webpack config) , then rebuilt it and it worked.

node: {
        global: false
    },

More Info:

The above fix may only be required if you are using later versions of webpack or react or something. I updated all of react, node webpack ect and create a new version of this rep because I wanted to update  to es6 class class instead of createClass, change some defaults and styles, git rid of MakeFile, blah blah. 

You can find it here: https://github.com/SuperheroUI/shQuill.

Thanks zenoamaro for this awesome start to a wrapper, your the best.

**Comment by zenoamaro** [comment]
Thanks for the heads-up, @SuperheroUI.

I don't feel this is a ReactQuill issue specifically, however.

If you feel we should put out a warning on the README, please reopen.
