### ISSUE TITLE
mixin: setEditorSelection strange behavior

### ISSUE THREAD

**Issue by g-borgulya** [zenoamaro/react-quill#144]
Hi,

I always run into a problem whenever I try to update the editor's content via quill API calls from "outside" the quill component: after the change almost the whole content of the editor got always selected. I checked the setEditorSelection method in mixin.js, and it seems to me that it is intentional. During the bound validation of the range the length is set to the full length of the editor and also the selection index is modified to something I don't even understand.

Is there a reason for this?

**Comment by alexkrolick** [comment]
<img width="603" alt="screen shot 2017-02-20 at 10 34 46 pm" src="https://cloud.githubusercontent.com/assets/1571667/23153351/df087cea-f7bc-11e6-8901-2f47731c13bf.png">

**Comment by wouterh** [comment]
I had the same problem and looked into it a bit more. I'll submit a pull request in a minute.
