### ISSUE TITLE
Any migration to react-native?

### ISSUE THREAD

**Issue by cinder92** [zenoamaro/react-quill#145]
it would be great!

**Comment by kantharia** [comment]
is there any future plans ?

**Comment by alexkrolick** [comment]
File this upstream with Quill. I doubt that it would work directly as it relies on browser/DOM objects.

**Comment by zenoamaro** [comment]
What @alexkrolick said is correct. It is unlikely that Quill will ever be ported to React Native, as it is tied to the browser. Maybe, now that they switched to Parchment, they can consider it. But anyway, the call is on Quill itself to make, not React Quill.

Still, you should be able to run it in a webview 😌.
