### ISSUE TITLE
css not in dist folder

### ISSUE THREAD

**Issue by luisrudge** [zenoamaro/react-quill#149]
https://unpkg.com/react-quill@0.4.1/dist/

I saw https://github.com/zenoamaro/react-quill/commit/f16858cc11948ee5ec4f42e6e555ef7f4dfcac6b, but I'm not sure if this is published or not

**Comment by maxg7** [comment]
It's definitely not published on npm. If you run `npm i https://github.com/zenoamaro/react-quill.git --save` the css will be included.

**Comment by zenoamaro** [comment]
It is available in `v1.0.0.-beta-1`.
