### ISSUE TITLE
Directly updating value inside editor

### ISSUE THREAD

**Issue by darios2** [zenoamaro/react-quill#150]
I'm trying to use insertText (from http://quilljs.com/docs/api/) since I want to place string at index location I'm getting from range. If I change plain text in store I'm not preserving html format and index is from plain text. If I'm using api from quill I get "insertText is not a function" (for every function).

**Comment by alexkrolick** [comment]
Hi,
Can you try upgrading to the beta version on NPM? You may be using a new Quill 1.0 API.

**Comment by zenoamaro** [comment]
@darios2 have a look at http://codepen.io/anon/pen/mRveOj?editors=0010 to see a working example.

My guess is that you're doing `this.refs.reactQuill.insertText()` instead of `this.refs.reactQuill.getEditor().insertText()`.

**Comment by alexkrolick** [comment]
Another example: https://codepen.io/alexkrolick/pen/YNmGar?editors=0011

**Comment by kychanbi** [comment]
@zenoamaro The font and font size setting seem doesnt work in demo

**Comment by alexkrolick** [comment]
Should work now, was missing from the approved formats list
