### ISSUE TITLE
Component stops updating state after several seconds of typing

### ISSUE THREAD

**Issue by mvincent7891** [zenoamaro/react-quill#156]
I can verify that the state of my component is being changed and passed down to the quill component, but quill stops updating after 5 - 10 seconds of typing. The last letter typed will be added to the state of my parent component, but it's not displayed in the text editor. This last letter will just keep getting replaced, as if the state of quill is stuck.

Quill version: 
- [ ] master
- [X] 0.4.1
- [ ] 1.0.0-beta-1
- [ ] Other (fork)

**Comment by alexkrolick** [comment]
Thanks for reporting. Have you tried updating to the latest version to see if it still persists?

**Comment by simond** [comment]
I don't have this issue (version 1.0.0-beta-1)

**Comment by mvincent7891** [comment]
Hey thanks for the response, Alex. I'm closing this issue because it had nothing to do with your editor. 

For posterity's sake - this was happening with _any_ RTE that I plugged in. The issue was that I was using a [react-timeago](https://www.npmjs.com/package/react-timeago) component that live updated its state every second. Once I killed live update on it, everything worked fine.
