### ISSUE TITLE
show browser support

### ISSUE THREAD

**Issue by jinsihou19** [zenoamaro/react-quill#157]
please show the browser support. I found not support ie10 and before when I used it in my project.Very crashing.

**Comment by alexkrolick** [comment]
It's a React wrapper around Quill. It supports whatever you can transpile or polyfill on the React side, plus whatever Quill requires: https://github.com/quilljs/quill

Currently this is the support table for Quill:

![image](https://cloud.githubusercontent.com/assets/1571667/23198288/5d515982-f87b-11e6-9748-297698ba9e57.png)
