### ISSUE TITLE
Revisit packaging/distribution

### ISSUE THREAD

**Issue by alexkrolick** [zenoamaro/react-quill#162]
See #161 

It makes sense to remove `dist` from source control, but we should probably add another mechanism to get master built and available in a CDN. Perhaps we could have Travis bundle successful builds and push the files to Github Releases.

Also, is `src` needed in the NPM package? Probably not.

**Comment by alexkrolick** [comment]
We can use [unpkg] to solve the CDN issue, so I'm in favor of moving the dist files out of source control in this release.

[unpkg]: https://unpkg.com/react-quill@1.0.0-beta-1/

**Comment by alexkrolick** [comment]
Webpack2 is reported to have issues due to the recent switch of `package.json`.`main` to `dist/react-quill.min.js` from `src/index.js` (#178).

I think it is safe to go back to the previous approach, unless we identify an issue with a specific bunder workflow:

- Ship a `<script />`-compatible bundle in `dist` in the NPM package.
- Ship an *unbundled* ES5-compatible module in the NPM package using CommonJS `require` and `module.exports` syntax. The library consumer's bundler can optimize the bundling of the dependencies.

Questions:

- What happens when we add ES6 to the mix - do we transpile it but not bundle it?
- Should the webpack target still be UMD? As a library it might make more sense to be CommonJS.

There are lots of opinions on this - see  https://github.com/webpack/webpack/issues/1617. 

cc @zenoamaro

**Comment by zenoamaro** [comment]
I don't think it's right to point `main` to `dist` at all – Quill itself also does this, and it causes unnecessary issues. I'd switch it back to `src`. The end user's minifier will already take care of that. Dist will only be needed for `<script>` users.

Webpack target should still be `UMD`, `dist` should be compatible with all bundlers. Right now we don't need to transpile anything, but when we switch to ES6 I'd transpile everything to `lib` and point `browser` to that.

How does that sound?

**Comment by alexkrolick** [comment]
Sounds great, let's push that out as the release candidate

**Comment by alexkrolick** [comment]
The new package is up on NPM: https://unpkg.com/react-quill@1.0.0-rc-1/

- `browser` points at `lib/index.js` in anticipation of ES6 transpilation, but it's just a copy of `src` for now (see Makefile)
- `main` also points at `lib/index.js` - we can revisit this later if we transpile, but transpilation of `node_modules` seems relatively uncommon and has big edge cases where the consumer uses a different babel preset stage than the client, or no transpiler at all. To be safe we could target pure ES2015, though.

**Comment by zenoamaro** [comment]
Yes, good point on transpilation – if we stick `main` to `lib` we won't even need `browser` I guess.
