### ISSUE TITLE
Cant install v1.0.0-beta-2 or beta-3 from npm

### ISSUE THREAD

**Issue by LeoIannacone** [zenoamaro/react-quill#166]
Hi,

npm install does not work with v1.0.0-beta-2

**Comment by eliwinkelman** [comment]
I think the current version is beta-1
`npm install react-quill@1.0.0-beta-1` worked for me

**Comment by alexkrolick** [comment]
`beta-2` is not on NPM yet. You can point package.json at `react-quill: zenoamaro/react-quill@1.0.0-beta-2` if you want, but unless you are affected by the bugs that have recently been fixed, you can wait for the NPM module to be updated.

cc @zenoamaro

**Comment by LeoIannacone** [comment]
Due to your `.npmignore` I can't install from github (the directory will be ready)

**Comment by alexkrolick** [comment]
Oh, you can point it at the tarball I uploaded though.

**Comment by alexkrolick** [comment]
```sh
npm install https://github.com/zenoamaro/react-quill/releases/download/v1.0.0-beta-2/react-quill-v1.0.0-beta-2.tgz
````

```json
{
   "react-quill": "https://github.com/zenoamaro/react-quill/releases/download/v1.0.0-beta-2/react-quill-v1.0.0-beta-2.tgz"
}
```

**Comment by yfilali** [comment]
@alexkrolick The tarballs for beta-2 and beta-3 have empty dist folders (at least as far as I can see on OSX)

Without at least beta-2, Quill isn't exposed and the examples for custom formats don't work at the moment.

**Comment by alexkrolick** [comment]
Thanks for reporting. Looks like a Yarn bug: https://github.com/yarnpkg/yarn/issues/2851/

Fell back to `npm pack` and uploaded a new one for beta-3. https://github.com/zenoamaro/react-quill/releases/tag/v1.0.0-beta-3

**Comment by yfilali** [comment]
Worked like a charm. Thanks for the quick fix!

**Comment by yfilali** [comment]
Ooh, I thought we had it , but I now get a module not found (which I think is because the entry file src/index.js is missing)

Module not found: Error: Cannot resolve module 'react-quill'

**Comment by alexkrolick** [comment]
Does it work if you change the entry in package.json in your node_modules/react-quill to `"main": "dist/react-quill.min.js"`

If so I'll push that

**Comment by yfilali** [comment]
Yes, that works. Everything is loading properly including the Quill export and the styles.

**Comment by alexkrolick** [comment]
OK, updated the release and tag.

**Comment by yfilali** [comment]
New tar ball is working properly now:

`rm -rf node_modules && npm cache clean && npm install`

**Comment by alexkrolick** [comment]
The betas should now be available on NPM!
