### ISSUE TITLE
onChange function delta and source incorrect

### ISSUE THREAD

**Issue by eliwinkelman** [zenoamaro/react-quill#167]
I am using an onChange function. The delta var is returning the change type, and the source is giving either the selection state or the delta. I think the problem is in the Mixins:

```javascript
editor.on('editor-change', function(delta, oldDelta, source) {
			if (this.onEditorChange) {
				this.onEditorChange(
					editor.root.innerHTML, delta, source,
					unprivilegedEditor
				);
				this.onEditorChangeSelection(
					editor.getSelection(), source,
					unprivilegedEditor
				)
			}
		}.bind(this));
```
This doesn't fit the Quill 1.0 [editor-change event api](http://quilljs.com/docs/api/#editor-change.) If the purpose of this was to work on text change, you should change it to `editor.on('text-change', function(delta, oldDelta, source)`

Additionally, importing Quill and using `Quill.on('text-change', ...)` give a Quill.on is not a function error.

Ideas?

**Comment by eliwinkelman** [comment]
Changing the code block from Mixins above to

```javascript
editor.on('text-change', function(delta, oldDelta, source) {
			if (this.onEditorChange) {
				this.onEditorChange(
					editor.root.innerHTML, delta, source,
					unprivilegedEditor
				);
				this.onEditorChangeSelection(
					editor.getSelection(), source,
					unprivilegedEditor
				)
			}
		}.bind(this));
```
Seems to solve the problem. However, I don't know what the intention for this function was (i.e. to provide editor change information, or to provide text-change information).

**Comment by alexkrolick** [comment]
Thanks for the report. It looks like your src is slightly out of date with master (the helpers have been extracted) but still functionally the same. Will look into what the 

> Additionally, importing Quill and using Quill.on('text-change', ...) give a Quill.on is not a function error.

You need a ref to an instance of Quill: https://github.com/zenoamaro/react-quill#methods

**Comment by eliwinkelman** [comment]
Thanks, I was trying to figure out how to access the editor methods.

**Comment by alexkrolick** [comment]
Pushed change in a pre-release bundle here: https://github.com/zenoamaro/react-quill/releases/tag/v1.0.0-beta-3
