### ISSUE TITLE
Video doesn't seem to work on beta-3 

### ISSUE THREAD

**Issue by dancrisan** [zenoamaro/react-quill#170]
Video doesn't seem to work on beta-3, got "Refused to display '<video link here>' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'."

**Comment by alexkrolick** [comment]
I think that is a CORS issue with your video source, not with Quill or this library.

I can embed a video just fine here: https://codepen.io/alexkrolick/pen/evGLwW?editors=0010

**Comment by alexkrolick** [comment]
Were you able to see if there is an issue with your video source, @dancrisan?
