### ISSUE TITLE
Strange behavior on headers (h1,h2,etc) dropdown on toolbar

### ISSUE THREAD

**Issue by gustavoelizalde** [zenoamaro/react-quill#171]
Hello,

I'm having a strange behavior when I try to use the header dropdown on the toolbar to use `<h1>`, `<h2>`, etc. tags.

Basically what happens is that when I click the dropdown, is open and close immediately. I don't have time to select a header, but... when I left the click button down, and I move to the options container, I can select a header. 

Here's my component code:

```
ReactQuill = require 'react-quill'

class QuillWrapper extends React.Component

  constructor: (props)->
    super props

    @modules = {
      toolbar: [
        [{ 'header': [1, 2, 3, 4, 5, 6, false] }],
        ['bold', 'italic', 'underline','strike', 'blockquote'],
        [{'list': 'ordered'}, {'list': 'bullet'}, {'indent': '-1'}, {'indent': '+1'}],
        ['link'],
        ['clean']
      ],
    }

    @formats = [
      'header',
      'bold', 'italic', 'underline', 'strike', 'blockquote',
      'list', 'bullet', 'indent',
      'link'
    ]

  displayName: 'QuillWrapper'

  shouldComponentUpdate: (nextProps,nextState)->
    nextProps.value isnt @props.value

  changeHandler: (value, delta, source)=>
    console.log "On Change..."

  onEditorChangeSelection: (range, source)=>

  render: =>

    return(

        <ReactQuill theme="snow"
                    modules={@modules}
                    formats={@formats}
                    readOnly=false
                    onChange={@changeHandler}
                    onChangeSelection={@onEditorChangeSelection}
                    value={@props.value}/>

    )

module.exports = QuillWrapper if module?.exports?

```
Can be this caused because it's used as a component called from other components?

That's the only toolbar option with problems, other buttons works fine.

Quill version: 
- [ ] 1.0.0-beta-3

**Comment by gustavoelizalde** [comment]
Ok, the issue was that the parent component had a <label> wrapping this Quill component, that was causing the auto-open / auto-close behavior.

Sorry for the inconvenient :)

**Comment by gsimone** [comment]
Hey @gustavoelizalde can you explain what was the problem? I'm having the same exact issue you described

**Comment by gavinpatkinson** [comment]
@gsimone @gustavoelizalde can anyone post the solution to this? I'm experiencing the same thing.

**Comment by gustavoelizalde** [comment]
@gavinpatkinson in my case the issue was a <div> tag I had wrapping the Quill-component.

Are you using the last version of 'react-quill' ?

**Comment by Angelmas** [comment]
can you explain how dyou resolve the issue?, I don't know what to add to the parent(wrapper) element to prevent the autoclosed behavior

**Comment by IHakoda** [comment]
I had the same problem, tried to figure it out for a long time and finally found this solution, thanks

Don't wrap the ReactQuill component with a label tag

**Comment by ianpetzer** [comment]
Thanks @andykotov A label tag was also causing the problem for me!
