### ISSUE TITLE
Migration guide is missing

### ISSUE THREAD

**Issue by davidfurlong** [zenoamaro/react-quill#174]
The links in the README to the migration guide don't work.

Quill version: 
- [ x ] master
- [ ] 0.4.1
- [ ] 1.0.0-beta-1
- [ ] Other (fork)

**Comment by zenoamaro** [comment]
Will be fixed with https://github.com/zenoamaro/react-quill/pull/168/commits/fe4cf329060185e71f6d71b4744de6e72e46738f
