### ISSUE TITLE
Is this editor good for writing custom emails?

### ISSUE THREAD

**Issue by mehulcse** [zenoamaro/react-quill#176]
Hi
This is not an issue as such I just want to know if this editor can be used as custom email editor? 

Because the output HTML consist of quill specific classes for alignment and that won't be reflected in email if I send this html as an email.

**Comment by alexkrolick** [comment]
Email markup in general is tricky. AFAIK the best practice is to inline all the styles. I'd ask this question upstream in Quill https://github.com/quilljs/quill/

**Comment by mehulcse** [comment]
Thanks a lot @alexkrolick 👍
