### ISSUE TITLE
webpack2 es6 module support

### ISSUE THREAD

**Issue by jtomaszewski** [zenoamaro/react-quill#178]
Webpack2, using webpack es6 module functions (without transpiling them with babel); react-quill 1.0.0-betav4 .

I get this error on production:

> Uncaught ReferenceError: require is not defined

Which is pointed to react-quill.min.js file.

Which is strange, everything is okay on dev environment.

When I switched `import ReactQuill from "react-quill"` to `import ReactQuill from "react-quill/dist/react-quill"` , everything works correctly.

Additional note: everything was good with `import ReactQuill from "react-quill"` in beta-v1.

Should we switch `"main": "dist/react-quill.min.js",` in package.json to use non-minified file?

**Comment by alexkrolick** [comment]
`beta-1` didn't point at the dist files: https://github.com/zenoamaro/react-quill/blob/v1.0.0-beta-1/package.json#L16

Where is the error being thrown? In the compilation step?

**Comment by alexkrolick** [comment]
@jtomaszewski Thanks again for reporting - do you think you can provide a sample configuration to reproduce the bug?

**Comment by alexkrolick** [comment]
Without confirming the issue I think the problem is related to the change to the packaging in https://github.com/zenoamaro/react-quill/issues/166#issuecomment-28489133. Seems bundling and distribution are quite a contentious topic https://github.com/webpack/webpack/issues/1617 so I'll reopen #162 for discussion.

cc @zenoamaro

**Comment by alexkrolick** [comment]
Also @jtomaszewski do you think it could be related to this bug: https://github.com/webpack/webpack/issues/4511?

**Comment by alexkrolick** [comment]
@jtomaszewski packaging reverted to previous style in `1.0.0-rc-1`. Give it a go?

**Comment by jtomaszewski** [comment]
Yup, it's good now.
