### ISSUE TITLE
Image handling

### ISSUE THREAD

**Issue by remy-poirier** [zenoamaro/react-quill#187]
Hello, 

I'm using the version 1.0.0-rc-1 and I would like to have more informations about how to use image handling please, I couldn't find documentation anywhere.

I simply would like to know if I can pass a method that will upload the file to the server and then return the file URL.

How can I do that please ? 

Do I have to create a custom component ? If so, why is the image button present ? 

Thank you !

**Comment by alexkrolick** [comment]
Hi Remy,

Images are handled by the underlying Quill instance. 

Here are some links to get started:

- http://quilljs.com/docs/formats/
- https://github.com/quilljs/quill/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20image

**Comment by remy-poirier** [comment]
Okay but I can add images already thanks to the toolbar, however the image in the HTML has an URL that is far too long.

Ideally I want to handle the file upload by my side, so I would like to know if I can create a custom method that will be called once the user has selected a file and that will simply upload it ? 

I've seen an example showing how to create a custom plugin so if there is no easy solution I will have to create a image upload plugin by myself I think
