### ISSUE TITLE
Add link button to toolbar

### ISSUE THREAD

**Issue by freakycue** [zenoamaro/react-quill#19]
I was trying to add link button to toolbar (like original quill editor has https://quilljs.com/), but with no luck. Button appears but it's not working, e.g. tooltip not appears at all.

**Comment by zenoamaro** [comment]
The `link-tooltip` module has to be enabled for the link interface to work.

Both the button and the module are enabled by default in v0.2.1.

**Comment by freakycue** [comment]
@zenoamaro, thanks!
