### ISSUE TITLE
Link pops up outside of editor

### ISSUE THREAD

**Issue by aliciawood** [zenoamaro/react-quill#190]
In the quill repo this bug was fixed a while ago, but I'm still seeing this issue:
https://github.com/quilljs/quill/issues/360.

I've tried playing with the styling and it doesn't seem to change anything.  Open the given codepen and create a link - the pop up opens outside of the editor.  

http://codepen.io/alexkrolick/pen/xgyOXQ/left?editors=0010#0

![screen shot 2017-04-14 at 4 50 45 pm](https://cloud.githubusercontent.com/assets/3421814/25058004/8d6f4d1a-2132-11e7-8d6f-a3240bbd3671.png)

Quill version: 
- [ ] master
- [ ] 0.4.1
- [ ] 1.0.0-beta-1
- [ ] 1.0.0-beta-2
- [ ] 1.0.0-beta-3
- [ ] 1.0.0-beta-4
- [ ] 1.0.0-beta-5
- [ X] 1.0.0-rc-1
- [ ] Other (fork)

**Comment by alexkrolick** [comment]
Add the bounds prop:

```
bounds={'.app'}
```

**Comment by dasm30** [comment]
Hi, I have same issue and when adding the bound prop I keep getting:
`Warning: Failed prop type: Invalid prop `bounds` supplied to `Quill`` no matter what value I pass, even tried with document.body and got the same error.

**Comment by harrisonlo** [comment]
For anyone like @dasm30, you have to pass in a string instead of the node (ref: https://github.com/zenoamaro/react-quill/issues/519)
