### ISSUE TITLE
Link pops up outside of editor - Multiple editors

### ISSUE THREAD

**Issue by aliciawood** [zenoamaro/react-quill#192]
Similar to issue #190.  When I have multiple editors on the same page, when creating a link in the second editor, it stays within the bounds of the first editor's class.  Is there some unique class or id on each editor that I can reference?

![screen shot 2017-04-20 at 10 42 45 am](https://cloud.githubusercontent.com/assets/3421814/25242250/36805cd2-25b6-11e7-8db8-ab1349fca1b9.png)

**Comment by alexkrolick** [comment]
The `bounds` prop can be any selector - you can give each editor container an id and use that.
