### ISSUE TITLE
It's broken on a fresh install

### ISSUE THREAD

**Issue by dekkofilms** [zenoamaro/react-quill#196]
**Quill version:** 
react-quill: 1.0.0-rc.2

I'm not sure what is going on, there are no obvious errors, other than it can't read the value prop for some reason. But even when i'm just commenting that out, and posting in Quill, it just looks like everything isn't formatted properly. Any help with this issue would be awesome, all I have done is import in the component, and place it in the code:

```
<ReactQuill
    modules={CustomPagesForm.modules}
    formats={CustomPagesForm.formats}
    value={value.text}
    onChange={props.onChange}
/>
```

And the result is as such:

<img width="550" alt="screen shot 2017-05-08 at 10 55 31 am" src="https://cloud.githubusercontent.com/assets/14862852/25812764/e98a045c-33dc-11e7-8b0c-d664695bf701.png">

**Comment by dekkofilms** [comment]
I tried putting in the link tag for the theme and what not, and that doesn't work, so then i just used this statement:

`import theme from '../../../node_modules/react-quill/dist/quill.snow.css';`

Is this the correct way of doing it? The docs just made it seem for the quick start, that you can through in the ReactQuill component, and it will be up and running with not much config.

**Comment by alexkrolick** [comment]
The way you include CSS will vary depending on your project setup. 

In your case it sounds like you have a CSS loader for webpack, so that will work.

Alternately you can load the CSS from a CDN, or add an `@import` to your (S)CSS main files.
