### ISSUE TITLE
Image-resize and Image-drop

### ISSUE THREAD

**Issue by Deelux** [zenoamaro/react-quill#197]
Hi there, 

This is not an issue but more a question. I was wondering if it is possible to use image-resize(https://www.npmjs.com/package/quill-image-resize-module) and image-drop(https://www.npmjs.com/package/quill-image-drop-module) with this ReactQuill module?

And if so, how do I combine the two?

Kind regards, 
Dominic

**Comment by alexkrolick** [comment]
```jsx
import ReactQuill, {Quill} from 'react-quill'
import { ImageResize } from 'quill-image-resize-module';
 
Quill.register('modules/imageResize', ImageResize);
```

Include `imageResize` in the modules prop passed to ReactQuill.

**Comment by Deelux** [comment]
So I have been trying to get this to work but I am getting an error every time I try to add this module.

I now have it like this:

`
import ReactQuill, {Quill} from 'react-quill'; 
import { ImageResize } from 'quill-image-resize-module';
export default class AddSparkShanghai extends Component {
  constructor(props) {
    super(props);
[...]
    };
  }


 return (
      <div className="background-container">
        <form ref={(input) => this.sparkForm = input} onSubmit={(e) => this.createSpark(e)}>
            <ControlLabel>Content</ControlLabel>
              <div className='_quill'>
                <ReactQuill
                  modules={imageResize}
                  toolbar={false} 
                  theme="snow"
                  ref='editor'
                  onChange={this.onChange}
                  events={events} />
               </div>
`

Then I receive this error in the console:
modules.js?hash=3930240…:142065 Uncaught TypeError: Cannot read property 'imports' of undefined
    at Object.<anonymous> (modules.js?hash=3930240…:142065)
    at e (modules.js?hash=3930240…:142065)
    at Object.<anonymous> (modules.js?hash=3930240…:142065)
    at e (modules.js?hash=3930240…:142065)
    at t.exports (modules.js?hash=3930240…:142065)
    at modules.js?hash=3930240…:142065
    at n (modules.js?hash=3930240…:142065)
    at image-resize.min.js (modules.js?hash=3930240…:142065)
    at fileEvaluate (modules-runtime.js?hash=8587d18…:343)
    at require (modules-runtime.js?hash=8587d18…:238)

What am I doing wrong?

**Comment by alexkrolick** [comment]
See this issue in quill-image-resize-module: https://github.com/kensnyder/quill-image-resize-module/issues/7#issuecomment-304463415

**Comment by rajuashok** [comment]
I really wish people would provide detailed answers. The first answer to this really didn't describe how to include `imageResize` in the modules. So I had to go search around to understand this. Anyway here is detailed code of everything you need to include ImageDrop / ImageResize in your ReactQuill editor:

```
import ReactQuill, { Quill } from 'react-quill';
import { ImageDrop } from 'quill-image-drop-module';
...
...
...
Quill.register('modules/imageDrop', ImageDrop);
const modules = {
  toolbar: [
    ['image']
  ],
  imageDrop: true // Make sure to add this!!!
};
const formats = ['image'];
...
...
...
return (
  <ReactQuill
    modules={modules}
    formats={formats}
    value={this.state[item.key]}
    onChange={value => {this.handleQuillChange(item.key, value)}} />
);
```

I believe for ImageResize the toolbar would look like this:

```
const modules = {
  toolbar: [
    ['image']
  ],
  imageDrop: {} // Make sure to add this!!!
};
```

This answer was helpful in figuring this out: https://github.com/kensnyder/quill-image-resize-module/issues/7#issuecomment-307737790

**Comment by FabioFortini** [comment]
@rajuashok In my case I passed a string to `imageDrop` field. So:
```
import ReactQuill, {Quill} from "react-quill";
import { ImageDrop } from 'quill-image-drop-module';
...
...
Quill.register('modules/imageDrop', ImageDrop);
const modules = {
    toolbar: [... ... ...],
    imageDrop: "false"
  };
...
...
return
<ReactQuill
       ....
        modules={modules}
      />
```
