### ISSUE TITLE
Doesn't work with browserify

### ISSUE THREAD

**Issue by WickyNilliams** [zenoamaro/react-quill#2]
If i require the module with browserify I get issues: 

    Fatal error: Invalid mapping: {"generated":{"line":14084,"column":7},"source":"webpack:///webpack/universalModuleDefinition","original":{},"name":null}

It works if i require the raw file from the src directory: `require("react-quill/src")`

**Comment by zenoamaro** [comment]
Hi, thanks for reporting this.

I've updated the `package.json` to point to `src/index.js`, while the precompiled is only sent to the browser.

I don't use browserify, rather webpack, and I haven't got time to test it yet, so please tell me if this works.

**Comment by zenoamaro** [comment]
Hi @WickyNilliams, did you solve your issues with browserify?

I've updated the quill version in the package to the latest, and they committed some fixes for browserify not too long ago. Can you check if this works for you?

**Comment by smvilar** [comment]
Hi @zenoamaro, I ran into the same issue that @WickyNilliams with the `src/index.js`. I changed the `browser` setting in package.json to `src/index.js` too and that worked. I'm not too familiar with npm packages and browserify so I don't know if that makes sense or not.

**Comment by zenoamaro** [comment]
Hey, I've removed the `browser` key from `package.json`.

This should default you to use `src/index.js` like you are doing now.

This should fix your case, but let me know if it doesn't.

**Comment by WickyNilliams** [comment]
Sorry for delay in response. Haven't been able to test as I've been travelling without a computer for the last month.

**Comment by smvilar** [comment]
Thanks a lot! It works now.
