### ISSUE TITLE
Does anyone have an example of custom toolbar working with tables? 

### ISSUE THREAD

**Issue by bvn13** [zenoamaro/react-quill#200]
I search for described functionality.

**Comment by alexkrolick** [comment]
Table layout inside the toolbar, or enabling a table format in the editor? Quill does not have a table format out of the box, but you should be able to enable a custom one by adding registering the format and adding it to the toolbar: https://github.com/zenoamaro/react-quill#custom-toolbar

**Comment by bvn13** [comment]
@alexkrolick I want to insert and manage html tables. So, buttons for inserting html table, inserting columns, lines etc. are needed.

**Comment by alexkrolick** [comment]
I see. You'll want to look into that upstream in Quill then: https://github.com/quilljs/quill/issues/117
