### ISSUE TITLE
How can we use formula with this 

### ISSUE THREAD

**Issue by gmchaturvedi1** [zenoamaro/react-quill#201]
Kindly tell us how to use formula with this.

Regards
gmchaturvedi

Thanks for filing an issue! 

If at all possible, please provide a Codepen to demonstrate the problem you're having with React Quill. Here's a [template] to get you started.

[template]: 
http://codepen.io/alexkrolick/pen/xgyOXQ/left?editors=0010#0

Quill version: 
- [ ] master
- [ ] 0.4.1
- [ ] 1.0.0-beta-1
- [ ] 1.0.0-beta-2
- [ ] 1.0.0-beta-3
- [ ] 1.0.0-beta-4
- [ ] 1.0.0-beta-5
- [ ] 1.0.0-rc-1
- [ ] Other (fork)

**Comment by alexkrolick** [comment]
It should work if you add `formula` to the `modules.toolbar` and the `formats` props? https://github.com/zenoamaro/react-quill#custom-toolbar
