### ISSUE TITLE
React Quill + ShareDB - Update Content by Deltas

### ISSUE THREAD

**Issue by darioAnongba** [zenoamaro/react-quill#202]
Hi, 

I've recently been trying to implement React-Quill with ShareDB to make it collaboratively editable, as done in this example in the ShareDB repo : https://github.com/share/sharedb/tree/master/examples/rich-text

Sadly, while doing so, I realised that it is not possible to set the content of ReactQuill by Delta, which I think is the default behavior of Quill. So I was wondering if you had any idea of how to do it (maybe I'm missing something). Without this functionality, I think that it is impossible to use ReactQuill and ShareDB together.

Here is the reason why:

On every change in the Quill editor, I check if the change is done by the source "user". If it is the case, I send an update operation (a delta) to the data on the server (via a ShareDB document).
Then, on every client subscribed to the same document, I receive an "operation" event containing the operation (the Delta). And I'm blocked here since I should update the content of the editor with this Delta operation by using the API method "updateContents".

Would you do it differently ? If so, how ? 

Thank you for your time,
Dario Anongba Varela.

Quill version: 
- [x] master

**Comment by darioAnongba** [comment]
Sorry, I just saw now that I could use the Quill API via getEditor().updateContents()... Sorry about that.

Still, the question remains on how to edit or set the content of the editor by using  a Delta instead of a String. Basically passing a Delta as a "value" in the ReactQuill component, like:
```jsx
<ReactQuill
        value={this.state.doc.data}
      />
```
where `this.state.doc.data` is a delta instead of a String. With a function "setEditorContents" that accepts a Delta as attribute instead of a String.

I'm willing to contribute on the code if you think that this is a good idea.

Thank you again,
Dario

**Comment by alexkrolick** [comment]
Dupe of #101 

We're in feature freeze for 1.0 right now but would certainly welcome a contribution to enable setting the contents with a delta. 

In the collaborative case I'm not sure if declaratively setting `value` would do what you want - you might want to start with `defaultValue` and apply deltas as they come in with `updateContents`.

**Comment by darioAnongba** [comment]
Yes but #101 is one year old so I was wondering.

Yes, for the collaborative part, I used setContents to initialize and then updateContents on every new Delta update. It works pretty well.

Fine, I'll look into the code and see if I can make it happen.

**Comment by zhenchaochen** [comment]
I am surprised that setContents is not supported.
@darioAnongba: how did you fix this eventually? 
Thanks.

**Comment by mubark75** [comment]
<h1>

</h1>

**Comment by mubark75** [comment]
mm

**Comment by nimish-kumar** [comment]
Adding a snippet, just in case someone comes across this issue again.

```
export default function TextEditor() {
  const quillRef = useRef()
  const [socket,setSocket] = useState();

  const [value, setValue] = useState("");

  useEffect(() => {
    const socket = io("http://localhost:8001");
    setSocket(socket);

    socket.on("receive-changes", delta => {
      if (quillRef.current == null) return
     
      // THIS IS HOW YOU UPDATE CONTENT USING DELTA
      quillRef.current?.getEditor()?.updateContents(delta)
    })

    return () => {
      socket.off("receive-changes")
      socket.disconnect();
    };
  }, []);

  const changeHandler = (value, delta, source) => {
    setValue(value)
    if(socket == null) return
    if(source!=="user") return
    socket.emit("send-changes", delta)
  }
  return (
    <ReactQuill
      theme="snow"
      value={value}
      onChange={changeHandler}
      modules={{ toolbar: TOOLBAR_OPTIONS }}
      ref = {(node) => quillRef.current = node}
    />
  );
```
