### ISSUE TITLE
Tooltips don't work

### ISSUE THREAD

**Issue by elghali** [zenoamaro/react-quill#206]
hey, tooltips with react-quill toolbar are not working using theme "snow" and when i try to use a different theme, i get the following error : "Error: Invalid theme undefined. Did you register it?" usage:
`import '../node_modules/react-quill/dist/quill.core.css';`
```
 render() {
    console.log('this.state.text', this.state.text);
    let modules = {
      toolbar: [
        [{'header': [1, 2, 3, false]}],
        ['bold', 'italic', 'underline', 'strike', 'blockquote'],
        [{'list': 'ordered'}, {'list': 'bullet'}, {'indent': '-1'}, {'indent': '+1'}],
        ['link', 'image'],
        ['clean']
      ],
    };
    let formats = [
      'header',
      'bold', 'italic', 'underline', 'strike', 'blockquote',
      'list', 'bullet', 'indent',
      'link', 'image'
    ];
    return (
      <div>
        <ReactQuill
          value={this.state.text}
          onChange={this.handleChange}
          theme="null"
          modules={modules}
          formats={formats}
        />
      </div>
    );
  }
```

- [+ ] 1.0.0-beta-2

**Comment by alexkrolick** [comment]
- Which alternate theme are you trying to register? `snow` and `bubble` should be available; `null` should not be a string if you want to use the default.
- Quill [does not have tooltips on toolbar items out of the box](https://github.com/quilljs/quill/issues/1084) in the Snow theme - you can see the default behavior here: https://quilljs.com/

**Comment by elghali** [comment]
I'm not registering any other theme, i get the error whenever i use base as theme, anyway this is not my main problem, what i care about is tooltips thank you
