### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by logs12** [zenoamaro/react-quill#207]
1.Please correct replace React.PropTypes on PropTypes ("import PropTypes from 'prop-types';")
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
2.Warning: Quill: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

**Comment by alexkrolick** [comment]
See #191
