### ISSUE TITLE
Paste as plain text inserts line breaks

### ISSUE THREAD

**Issue by kdejaeger** [zenoamaro/react-quill#208]
https://codepen.io/kdejaeger/pen/gRpaGv?editors=0010 (can someone fix the import of 'Delta'?)

As you can see in the code, we added a clipboard matcher to remove the html code.
The attached document contains 1 line of text. However, when I copy past it into the quill editor, I get 2 paragraphs and thus 2 lines.
Anyone understands why?

[20120503 Gebruikersdocumentatie.docx](https://github.com/zenoamaro/react-quill/files/1055089/20120503.Gebruikersdocumentatie.docx)
![after pasting](https://cloud.githubusercontent.com/assets/279268/26830509/62f6ae6e-4ac9-11e7-8494-edc50890c6cd.png)

**Comment by alexkrolick** [comment]
This is an issue with Quill's pasteHTML method - please file upstream.
