### ISSUE TITLE
Toolbar Link not working

### ISSUE THREAD

**Issue by Predjo** [zenoamaro/react-quill#21]
The button is added, but clicking on it does nothing.

**Comment by zenoamaro** [comment]
Hello, here is a list of buttons that are [currently supported by the quill editor](http://quilljs.com/docs/modules/toolbar/). Could you verify that the button you want is in that list?

Otherwise, could you share some code so I can try to reproduce? Thanks.

**Comment by zenoamaro** [comment]
Sorry, is this the same issue as #19?

**Comment by Predjo** [comment]
Hey yap sorry didn see it. You can close this one.

**Comment by zenoamaro** [comment]
Thanks anyway! I'll see to prioritize that fix.

**Comment by paduvi** [comment]
It happened again. Had try:

```
const modules = {
    'link-tooltip': true,
    toolbar: [...]
}
```

Browser log warn: 

> quill Cannot import modules/linkTooltip. Are you sure it was registered?

**Comment by alexkrolick** [comment]
That's not a stock Quill module, you have to register it like this: https://github.com/zenoamaro/react-quill#custom-formats

**Comment by paduvi** [comment]
@alexkrolick But the main problem is default Link button not working... 

I inspected element on Browser and found out that 'tooltip div' has strange style left-top, which makes it can't popup on window.

![image](https://cloud.githubusercontent.com/assets/15514657/24443194/d20633c0-148b-11e7-906a-fa56e0931360.png)

**Comment by paduvi** [comment]
At the moment I have a quick fix for this problem by using `bounds` prop:
```
<ReactQuill theme="snow"
	value={this.state.content}
	onChange={this.handleChangeContent}
	modules={modules}
	placeholder="Write something..."
	bounds={'#quill-container'}
>
	<div style={{minHeight: 200}} id="quill-container"/>
</ReactQuill>
```

**Comment by alexkrolick** [comment]
Try upgrading to v1.0.0-beta-4 and see if the problem still exists
