### ISSUE TITLE
Grammarly doesn't work with ReactQuill 

### ISSUE THREAD

**Issue by jamesmgg** [zenoamaro/react-quill#210]
1. Install Grammarly Chrome extension
2. On any ReactQuill component, Grammarly does not work.

I'm not sure how Grammarly works, but it also seems to have this problem with iframes. Any advice for work arounds or fixes?

Quill version: 
- [ ] master
- [ ] 0.4.1
- [ ] 1.0.0-beta-1
- [X ] 1.0.0-beta-2
- [ ] 1.0.0-beta-3
- [ ] 1.0.0-beta-4
- [ ] 1.0.0-beta-5
- [ ] 1.0.0-rc-1
- [ ] Other (fork)

**Comment by alexkrolick** [comment]
It's a known issue with Quill - see discussion here https://github.com/quilljs/quill/issues/574

**Comment by jamesmgg** [comment]
I just realized that the reason it's not working is because starting in version 1.2.6, Grammarly is being turned off by default. 
https://github.com/quilljs/quill/commit/fba09b116146f7403c9be6ccfabf3d08a83f1acb

**Comment by alexkrolick** [comment]
Thanks for the additional info on that

**Comment by satishav** [comment]
@jamesmgg not sure if you got this working. Still, Grammarly does not work for me in react-quill. 1.3.5
