### ISSUE TITLE
react-quill renders arrows !?!?!?

### ISSUE THREAD

**Issue by suziesirena** [zenoamaro/react-quill#211]
Hi,

I've installed the last version and the component renders arrows...

<img width="235" alt="capture d ecran 2017-06-15 a 21 46 12" src="https://user-images.githubusercontent.com/1114738/27198817-1c021726-5214-11e7-8c08-68d876c8387a.png">

I don't understand why... Could you help me ?

Here is my code :

import React from 'react'
import ReactDom from 'react-dom'
import ReactQuill from 'react-quill'

export default class Test extends React.Component {
  constructor(props) {
    super(props)
    this.state = { text: '' }
  }

  handleChange(value) {
    this.setState({ text: value })
  }

    render() {

      var modules= {
        toolbar: [
          [{ 'header': [1, 2, false] }],
          ['bold', 'italic', 'underline','strike', 'blockquote'],
          [{'list': 'ordered'}, {'list': 'bullet'}, {'indent': '-1'}, {'indent': '+1'}],
          ['link', 'image'],
          ['clean']
        ]
      }

      var formats= [
        'header',
        'bold', 'italic', 'underline', 'strike', 'blockquote',
        'list', 'bullet', 'indent',
        'link', 'image'
      ]

      return (
        <div className="text-editor">
          <ReactQuill theme="snow"
                      modules={modules}
                      formats={formats}>
          </ReactQuill>
        </div>
      )
    }

  }

**Comment by alexkrolick** [comment]
You are missing the CSS files - see here for docs https://github.com/zenoamaro/react-quill#theme

**Comment by suziesirena** [comment]
Thanks... It works
