### ISSUE TITLE
Editor doesn't show correctly

### ISSUE THREAD

**Issue by rahmatkruniawan** [zenoamaro/react-quill#215]
I install but when I try it in my reactjs.
it's not rendered correctly. This what I got.
Ithink the problem is css not loaded 
![quil](https://user-images.githubusercontent.com/9253817/27371332-8fee6ea8-568a-11e7-8dbc-0957a34d2c74.jpg)

**Comment by alexkrolick** [comment]
Yep, looks you are missing CSS: https://github.com/zenoamaro/react-quill#theme

**Comment by jdh2550** [comment]
I get this same problem but the CSS is loading (I checked the network tab).

I created my app using the create-react-app helper and then just copy and pasted the quick start code as a new component...

I'm sure I'm doing something dumb...

Help ?  Please/Thanks.

**Comment by abhi12299** [comment]
How did you solve the issue? I have the same problem.
Here is my webpack config

      test: /\.css$/,
        use: [
          {
            loader: 'style-loader',
          },
          {
            loader: 'css-loader',
            options: {
              modules: true,
              importLoaders: 1,
              localIdentName: '[name]_[local]_[hash:base64]',
              sourceMap: true,
              // minimize: true,
            },
          },

**Comment by Jayjaynoplays** [comment]
Just add the `import 'react-quill/dist/quill.snow.css';` in your _app file
