### ISSUE TITLE
Small and Huge Font Sizes Don't Work

### ISSUE THREAD

**Issue by mbenjamin618** [zenoamaro/react-quill#216]
[template]: 
https://codepen.io/anon/pen/bRRdpp?editors=0010

Quill version: 
- [ X] master
- [ X ] 1.0.0-rc-2

As you can see in the template, I haven't added any formatting and I'm using the snow theme, but the only two font sizes that work are normal and large. Small and Huge have zero effect on the font size.

**Comment by alexkrolick** [comment]
Thanks for reporting - it appears we can safely remove the custom inline formats in favor of the Quill size and font modules. If someone wants a custom format they can still register it using the Quill export from `index.js`.

**Comment by mbenjamin618** [comment]
@alexkrolick just to make sure, this implies that the format prop is irrelevant?

**Comment by alexkrolick** [comment]
No, it means it uses the native Quill format instead of a custom format of the same name. You can still enable/disable `size` and `font` using the keys in the module prop.
