### ISSUE TITLE
Range deletion issue 

### ISSUE THREAD

**Issue by andrewmiroshnichenko** [zenoamaro/react-quill#218]
Quill version: 
- [ x] master

Hi. Sorry, but I can't reproduce this issue on CodePen, so I just made I video of it.
https://youtu.be/1N6CTtkxx28
I install component today by npm install react-quill@v1.0.0-rc.3.
No hooks and callbacks are used, this is how it's used:
<ReactQuill data-path="TYEmailBody" className="settings-item-input" />

Basically, something is wrong with selection deleting. When I select a range inside editor(0:11) and delete it via "Del" key(0:12) - console throws error(error path is below) and one additional symbol is deleted(sometimes before, sometimes after selection). When I delete range by inserting other symbol (for example, by pressing "e" key, 0:19) no errors are thrown. In both cases if I'll try to undo changes(on 0:15 and 0:20) by ctrl+z same error will be thrown.
Error path:
react-quill.js:2772 Uncaught TypeError: leaf.domNode.getBoundingClientRect is not a function
    at Selection.getBounds (react-quill.js:2772)
    at Selection.scrollIntoView (react-quill.js:2901)
    at Quill.setSelection (react-quill.js:1626)
    at History.change (react-quill.js:6168)
    at History.undo (react-quill.js:6219)
    at react-quill.js:5173
    at Array.some (<anonymous>)
    at HTMLDivElement.<anonymous> (react-quill.js:5150)

**Comment by alexkrolick** [comment]
I also can't reproduce - these details might help if you can provide them:

- Resolved package versions for ReactQuill, React, and Quill. You can get this from yarn.lock for Yarn or package-lock.json for npm 5+. The demo uses Quill 1.2.6, RQ rc.3, and React 15.6.1.
- A snippet of the React code you used to render/configure the editor in your video.

**Comment by andrewmiroshnichenko** [comment]
After few hours of brainstorming I found the root of issue. One of components in our app was named Text and it consumed according variable in global scope. It creates conflict with ReactQuill which is result is this weird behavior. When I rename our component(thankfully it was possible) all become fine and ReactQuill now works very well.
I'm closing issue, but can you do something with naming inside your component? It's not a huge problem but can consume significant time if you face it. Maybe, at least, list of variables in global scope, that are used by ReactQuill. I don't know.
Thank you for your time.

**Comment by alexkrolick** [comment]
There should not be any source code using globals because strict mode ('use strict') is enabled for each module.

Glad you figured out your issue.
