### ISSUE TITLE
How can I determine if the enter key was pressed?

### ISSUE THREAD

**Issue by hackingbeauty** [zenoamaro/react-quill#22]
The onTextChange function provides a delta argument that gives you the last keystroke.

If I hit the enter key, the delta returns "↵", but I can't query for that in my JS code.

Is there another way to query for certain key strokes?

**Comment by zenoamaro** [comment]
You can bind `onKeyDown` or `onKeyUp` on the element containing the editor and you'll receive an event as usual. You can wrap the editor into another component, or build a custom component using the mixin.

I want to allow a few more events on the editor, such as keypress events, but I want to hear what they would be used for before. Do you have a specific use-case?

**Comment by hackingbeauty** [comment]
The methods onKeyDown/onKeyUp do not listen for the "enter" key button press (but they do for other keys).  I just tested this by binding them to the element containing the editor.

However, I did find an alternate solution.  Via the onChange method on the ReactQuill component, I can query for the "enter" key button using this statement which yields a value of 10: 

```javascript
delta.ops[delta.ops.length -1].insert.charCodeAt(0);
```

My use case is very specific.  I'm allowing users to use the text editor while watching videos.  When pressing letter keys the video automatically pauses.  When pressing the "enter" key, the video resumes playing.

**Comment by zenoamaro** [comment]
It seems there is an issue where Quill prevents `keydown` events for `enter`, `backspace` and `delete` from bubbling up. But you can still receive them when using `onKeyUp`.

I've just pushed some "official" hooks for keypress events so that you won't have to bind them on a container. See also [the note about `onKeyDown`] in the README.

[the note]: blob/86065048cbc97e72afe1d9e344423b48a2fe0287/README.md#api-reference

**Comment by hackingbeauty** [comment]
I just downloaded version 0.2.2, and onKeyPress does not work for me. Neither does onKeyDown.

**Comment by zenoamaro** [comment]
There is a note in the README that explains that why you have to bind to `onKeyUp` to receive events from keys like `enter`, `backspace` or `delete`. Please try this and let me know.
