### ISSUE TITLE
Paste without html(only text)

### ISSUE THREAD

**Issue by lexxizz** [zenoamaro/react-quill#222]
Hello. How can I paste text without html tags? Only text. I need to format my text manually.

**Comment by alexkrolick** [comment]
Do you want to intercept *all* pastes, or just manually paste plaintext sometimes? The OS provides a shortcut (usually Ctrl-Shift-V) to do plaintext paste. If you're intercepting all of them, you can look into https://www.npmjs.com/package/sanitize-html. You can also disallow certain types of [Quill formats](http://quilljs.com/docs/formats/).
