### ISSUE TITLE
Problems with quick start & documentation

### ISSUE THREAD

**Issue by jdh2550** [zenoamaro/react-quill#225]
Having some issues with the quick start:
* The quick start implies you don't need a CSS loaded (as CSS isn't discussed until the "Advanced Options" section).  But if I don't include a CSS I get the "big arrows".
* The documentation says you can specify theme="base" but if you do quill throws an error that it's not a recognized theme
* I can't get base/core working - if I don't include the theme prop then the documentation says it will default to base/core but then I get the "big arrows" (I have imported the core.css).
* The quick start might want to mention how to get things working if you generate your app with create-react-app (as that's kind of the official FB way of starting a react project, right?)  Or at least list some of the ways you might need to import the CSS files.  Just a suggestion.
* If using the quick start code with create-react-app then you need to correctly bind the handleChange function (see below).

I'm trying to get a quill editor with no toolbar and no bubble - how can I achieve that?  

Thanks!

This works (except I don't want a toolbar):
```
import React, { Component } from 'react';

import ReactQuill from 'react-quill';
import 'react-quill/dist/quill.snow.css';

class Editor extends Component {
  constructor(props) {
    super(props)
    this.state = { text: '' }
  }

  handleChange = (value) => {
    this.setState({ text: value })
  }

  render() {
    return (
      <ReactQuill theme="snow" value={this.state.text}
                  onChange={this.handleChange} />
    )
  }
}

export default Editor;
```

This doesn't: work (displays the "big arrows"):
```
import React, { Component } from 'react';

import ReactQuill from 'react-quill';
import 'react-quill/dist/quill.core.css';

class Editor extends Component {
  constructor(props) {
    super(props)
    this.state = { text: '' }
  }

  handleChange = (value) => {
    this.setState({ text: value })
  }

  render() {
    return (
      <ReactQuill value={this.state.text}
                  onChange={this.handleChange} />
    )
  }
}

export default Editor;
```

**Comment by alexkrolick** [comment]
How you import CSS really depends on your build system - we don't (can't, shouldn't) prescribe how that happens, but we can add a note about that and the other imports to the first section. We can also rename "Advanced Options" to just "Options" to emphasize their importance, and add a bind in the constructor (the class property declaration spec requires transpilation beyond ES2015 + JSX)

If "core" isn't working, that should be filed as another bug, but in the meantime you can pass `theme={null}`.

**Comment by alexkrolick** [comment]
Per Quill docs, the correct way to use the base theme is pass a falsy value in the config (*not* `core` or `base`); the ReactQuill README will be updated to reflect that.

<img width="894" alt="screen shot 2017-06-28 at 8 36 39 pm" src="https://user-images.githubusercontent.com/1571667/27670464-f79d9b20-5c41-11e7-812d-cd1783fb8273.png">

**Comment by alexkrolick** [comment]
closed via 7dc468241e787c31959430e19e938031081890fe

**Comment by box4soumendu** [comment]
In the head section of the index.html file link the CSS file required for the React-Quill element.

<link rel="stylesheet" href="//cdn.quilljs.com/1.2.6/quill.snow.css" />

Hope this will solve the issue. :)

**Comment by box4soumendu** [comment]
See the code mentioned below...

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />

    <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />

    **<link rel="stylesheet" href="//cdn.quilljs.com/1.2.6/quill.snow.css" />**

    <title>Evernote</title>
  </head>
  <body>
    <div id="evernote-container"></div>
  </body>
</html>
