### ISSUE TITLE
Quick Start Example missing theme="snow"

### ISSUE THREAD

**Issue by jdh-invicara** [zenoamaro/react-quill#226]
Great documentation updates.  Thanks!

One more:
```
<ReactQuill value={this.state.text}
                  onChange={this.handleChange} />
```

Should be:
```
<ReactQuill value={this.state.text}
                  theme="snow"
                  onChange={this.handleChange} />
```

**Comment by alexkrolick** [comment]
That is the default

**Comment by jdh-invicara** [comment]
I could have sworn last night that when I didn't include theme="snow" I got the non-styled version of the editor (even when the snow.css was included).  I'm at work right now but I'll retest tonight.

**Comment by alexkrolick** [comment]
You can try removing the theme prop from this: https://codepen.io/alexkrolick/pen/xgyOXQ?editors=0010

If you confirm it's not working later, it's a bug to be fixed.
