### ISSUE TITLE
input chinese bug, onchange can not trigger!

### ISSUE THREAD

**Issue by fashman** [zenoamaro/react-quill#229]
i have a bug in my project;
when i input chinese with some formats, the method onChange can not trigger;(Chinese input method need keydown space to get chinese last);
my code:
<pre><code>
export default class EditorCom extends React.Component {
	handleChange = (value) => {
		console.log('onchange', value);
		this.props.callback( {[this.props.keyName]: value} );
	}
	render() {
		return (
			&lt;ReactQuill
				placeholder={this.props.placeholder || '请输入信息'}
				value={this.props.value}
				theme="snow"
				onChange={this.handleChange}
				modules={modules}
				readOnly={this.props.readOnly || false}
			/&gt;
		)
	}
}
</pre></code>
PS: such as this -- [picture](http://static.quimg.com/data-manager/supplier/dist/6f8e8027-3b10-478b-b809-19a65170be97.png)
i input chinese with space last, but onchange did not trigger and the placeholder text is still in;
thanks!!!

**Comment by alexkrolick** [comment]
Does it look like this is related to any of the Chinese bugs upstream in Quill? https://github.com/quilljs/quill/issues

**Comment by fashman** [comment]
the problem is still in;

**Comment by alexkrolick** [comment]
OK, we'll watch Quill for the fix.
