### ISSUE TITLE
How can I edit markup in editor?

### ISSUE THREAD

**Issue by hackingbeauty** [zenoamaro/react-quill#23]
Hi,

I'd like to tweak the markup of the react-quill editor after a user hits the enter key.  Specifically, I'd like to add a span tag inside of the last sentence a user has entered.

I tried using the method dangerouslySetInnerHTML(), but it doesn't work.  The react-quill component strips out any markup I specifically try to inject into the editor.

Is there any way for me to override this?

**Comment by zenoamaro** [comment]
Hello,

you should avoid modifying values imperatively or in-place when working with React.

Instead, do it the declarative way. Find where the newline has been added, edit your copy of the value accordingly, and pass it to the editor as a prop.

You can find where the newline has been entered by parsing the `delta` object that is sent during `onChange`, or by keeping track of the cursor in `onSelectionChange` and waiting for <kbd>Enter</kbd> during `onKeyUp`.

**Comment by zenoamaro** [comment]
Assuming this is solved. Feel free to re-open otherwise.
