### ISSUE TITLE
Text color changer does not work (does work in QuillJS)

### ISSUE THREAD

**Issue by aliciawood** [zenoamaro/react-quill#231]
Browser: IE 11 (looks like it's not working in other browser too)

https://codepen.io/anon/pen/YQdqLa?editors=0010#0

Repro:
1. Type a word of text, select the word. 
2. Try to change the color

Expected:
-word that was selected changes color

Actual:
-nothing changes about the text color.

This is not a Quill JS issue

#### Quill version 
- [X ] 1.0.0-rc-3

**Comment by alexkrolick** [comment]
![image](https://user-images.githubusercontent.com/1571667/28091012-41a3b6fe-6643-11e7-9248-2978cc98de0a.png)

You need to whitelist 'color' in the enabled format, or remove the prop to enable the default set (which is currently everything).
