### ISSUE TITLE
Provide tabIndex prop to allow for sequential tabbing in forms

### ISSUE THREAD

**Issue by haxxxton** [zenoamaro/react-quill#232]
When quill is part of a form where previous/next inputs have `tabindex` > 0, sequential tabbing is lost, as elements of quill do not allow for tabIndex to be specified. It would be great if all elements generated by quill had their tabIndex explicitly set to a defined prop that defaulted to 0.

[template]: 
https://codepen.io/anon/pen/bROgwN?editors=0010#0

#### Quill version 
- 1.0.0

**Comment by zenoamaro** [comment]
I think `tabIndex` support for the built-in editing area is a sensible request. I'm all for this being in the next release.

However, I can't see how the same could be done for the toolbar, without either providing a custom toolbar, or monkey patching the elements (which I won't do). I suggest pushing your proposal [upstream to Quill itself](https://github.com/quilljs/quill/issues).

In the meantime, you can accomplish both, in a slightly more verbose way, this by providing a [custom editing area](https://github.com/zenoamaro/react-quill/tree/6cb374d2645b944789611c6321fdf745c3c788b0#custom-editing-area) and a [custom toolbar](https://github.com/zenoamaro/react-quill/tree/6cb374d2645b944789611c6321fdf745c3c788b0#custom-toolbar).

**Comment by herrherrmann** [comment]
The new `tabIndex` prop unfortunately does not seem to work for me. The `tabindex` property only seems to be applied to the ql-clipboard div but not to the ql-editor (which seems to still get focus now through tabbing).

![ql tabindex](https://user-images.githubusercontent.com/6429568/36783361-0fbfb7b0-1c7c-11e8-808e-9056cb97d829.png)
