### ISSUE TITLE
Text loses highlight after trying to change font. 

### ISSUE THREAD

**Issue by factsfinder** [zenoamaro/react-quill#233]
When I highlight a text to change font, the text loses the highlight after I click on toolbar to select a font. Once I select the font, the text gets highlighted back. 

Expected behaviour is, the text should be highlighted all the time. 

Appreciate the help in advance. Thank you.

**Comment by alexkrolick** [comment]
Plain Quill does this, too: https://codepen.io/alexkrolick/pen/awRxWz

I'd check upstream if there is a fix.
