### ISSUE TITLE
Custom Format create method firing twice with different values

### ISSUE THREAD

**Issue by Paddy-Hamilton** [zenoamaro/react-quill#234]
## What I am trying to do
Create a custom toolbar with buttons that format selected text with the same tag and but variable attribute values based on data passed into the handler on click (similar to the link blot). I believe I should be able to pass values into a blots create method (just like in the link blot being passed the url).  

## Issue
The value i pass into the blot works and the node gets created, HOWEVER the blots create function is immediately called again with a different value (i think just the blot name) and this value overrides the original attribute value / or maybe the node entirely.  

###  Q: Why is the create method running twice, where is it being called from

 [Here is a codepen,](https://codepen.io/Paddy-Hamilton/pen/awrqee) check the console for logs.

Any help here greatly appreciated, going nuts trying to work it out atm

Cheers,
Paddy

#### Quill version 
- [ ] 1.0.0

@zenoamaro

**Comment by alexkrolick** [comment]
Do you know if this is issue affects plain Quill or only React-Quill?

**Comment by Paddy-Hamilton** [comment]
@alexkrolick thanks for getting back to me :)

I tried tried it with plain Quill and it didn't happen, so I believe it is an issue with React-Quill, hence logging the issue in this repo :)

I have found that it is something to do with the static formats and format functions and how they trigger calls on each other I have updated the [codepen ](https://codepen.io/Paddy-Hamilton/pen/awrqee?editors=0010) to include more console logs, and its shows that static formats calls gets stuck in a loop calling itself. Also, not sure why the format function is being called with a null value? what is triggering that call?

**Comment by alexkrolick** [comment]
`alert` is not a valid HTML tag - it seems to work if I change the tagName of the custom blot to something like `b`

https://developer.mozilla.org/en-US/docs/Web/HTML/Element

**Comment by alexkrolick** [comment]
Did that fix your problem?

**Comment by Paddy-Hamilton** [comment]
@alexkrolick  Hey, thanks for checking 

I know that `alert` is not a valid HTML tag, however I was under the impression that you could add in custom tags by creating new blots. I need to be able to create these custom tags for the xml schema that I will be using the editor content with. 

Unfortunately it seems that the requirements of my project don't quite match the current capabilities of quill so have moved onto using another editor tool.

Thanks for you help though.

**Comment by alexkrolick** [comment]
For future reference:

You can create custom blots, but they have to have HTML tags as the base. You might be able to change the allowed tags using the Custom Elements spec: http://w3c.github.io/webcomponents/spec/custom/#element-definition
