### ISSUE TITLE
Upgrade Quill to 1.3?

### ISSUE THREAD

**Issue by stinoga** [zenoamaro/react-quill#238]
Any plans to upgrade to Quill 1.3?

**Comment by alexkrolick** [comment]
Yes, in fact it might makes sense to relax the version constraint to only major versions since Quill is pretty strict about semver and breaking changes.

**Comment by zenoamaro** [comment]
@stinoga, @alexkrolick, we already depend on `quill^1.2.6`, which is any `quill` up to `2.0.0`, as per the [npm semver](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004) guide.

So this should not be an issue. Worst case, If npm refuses to update your subdependency, just uninstall and reinstall `react-quill`.
