### ISSUE TITLE
Should expose `scrollingContainer`

### ISSUE THREAD

**Issue by haihonglicom** [zenoamaro/react-quill#239]
[scrollingcontainer](http://quilljs.com/docs/configuration/#scrollingcontainer)

Necessary to fix scroll jumping bugs when Quill is set to auto grow its height, and another ancestor container is responsible from the scrolling.

**Comment by spaceraccoon** [comment]
Would love for this!

**Comment by SinnerAiZ** [comment]
Finally i find the answer form your issue！
