### ISSUE TITLE
Image upload will be saved in that location ?

### ISSUE THREAD

**Issue by Q-Angelo** [zenoamaro/react-quill#243]
Image upload will be saved in that location ?

![image](https://user-images.githubusercontent.com/17956058/28742560-7641001c-7465-11e7-942c-450632a2e41e.png)

**Comment by zenoamaro** [comment]
It will embed the picture in the HTML itself, as a [Data URLs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs).

As far as I know, server-side image upload is not available in Quill at the moment, but is [currently being proposed for inclusion](https://github.com/quilljs/quill/pull/995) upstream. 

This is a feature of [Quill](https://github.com/quilljs/quill), not ReactQuill, so I suggest discussing this topic there. Thanks!
