### ISSUE TITLE
Image Upload module

### ISSUE THREAD

**Issue by ssageghi** [zenoamaro/react-quill#248]
Hi 
I used your editor for posting blog to my website
the problem is if a user adds a photo, the text attribute is too long and I can't save it properly and I get Error.
Is there an option that doesn't convert the image to base64? maybe blob?

**Comment by zenoamaro** [comment]
At the moment, as far as I know, the [Quill](https://quilljs.com) editor does not support it. 

This is not a ReactQuill issue, though, so we have little power to change it. 

I suggest raising this problem to the [Quill devs](https://github.com/quilljs/quill/issues) themselves.

**Comment by ssageghi** [comment]
@zenoamaro can you give me a codepen example to add image handler like this? 
[https://codepen.io/jackmu95/pen/EgBKZr](url)
I really appreciate that 
thank
