### ISSUE TITLE
How do I focus()?

### ISSUE THREAD

**Issue by That-David-Guy** [zenoamaro/react-quill#25]
Hi

I'm trying to set the input focus to my react-quill component.

I tried the following but it doesn't seem to do anything (it works for a normal input field though).

    componentDidMount: function(){
      React.findDOMNode(this.refs.quillRef).focus();
    },

Any help would be super!

**Comment by zenoamaro** [comment]
Passing a selection should be the way to focus. Can you try this real quick?

~~~
render: function() {
  return (
    <ReactQuill ... selection={{start:0, end:0}}/>
  );
}
~~~

Or, if that fails:

~~~
componentDidMount: function() {
  this.refs.quillRef.state.editor.focus();
}
~~~

**Comment by That-David-Guy** [comment]
Thanks for the quick reply, but it still is not working for me. 

The first way does nothing, and the second way throws an error.

Here is the full component:

    var SpeechBodyEditor = React.createClass({

    componentDidMount: function(){
        // This line throws an error, editor does not exist
        // this.refs.bodyInput.state.editor.focus();
      },
    
      render: function() {
        return (
          <ReactQuill
            className="body-editor"
            id="bodyInput"
            onChange={this._handleChange}
            selection={{start:0, end:0}}
            value={this.props.body}
            ref="bodyInput" />
        );
      },
    
      _handleChange: function(value, delta, source) {
        if (source == 'user' && value != this.props.body) {
          SpeechActionCreators.updateBody(this.props.speechId, value);
        }
      }
    });

**Comment by zenoamaro** [comment]
Can you try branch `focusing`?

You should be able to focus and blur like so:

~~~js
this.refs.bodyInput.focus();
this.refs.bodyInput.blur();
~~~

This should alleviate your issue for the time around, though I'm not really sold on this. I'd rather not to introduce an imperative API if I can. Anyway, let me know if this works for you.

**Comment by That-David-Guy** [comment]
Still causing an error. 

    component.js:268 Uncaught TypeError: Cannot read property 'focus' of undefined

Does it work for you? If so, then it must be something else in my project. I can try to track it down more over the weekend.

My use case is:
1. User types into the Title field (not quill component)
2. User presses enter and is automatically taken to the Body field (which is the quill component)

I'm open to other, more declarative, ways of solving this.

**Comment by zenoamaro** [comment]
component.js:268 Uncaught TypeError: Cannot read property 'focus' of undefined

I went with what you used in your last example, `<ReactQuill … ref="bodyInput" />`, so please substitute `this.refs.bodyInput.focus()` (called from inside the component holding the ref) with the correct ref that you are actually using there. For example, I see that in the original post you used `ref="quillRef"`, so edit accordingly.

The use case is sound. React doesn't provide other means to focus or blur elements, rather than resorting to `getDOMNode()` and calling `focus` directly, so I guess it can't really be helped.

Once I get confirmation that you got it working, I'll merge the branch.

**Comment by That-David-Guy** [comment]
Still doesn't seem to be working. I'm getting an error from your component.js

    component.js:268 Uncaught TypeError: Cannot read property 'focus' of undefined

I've simplified my component a lot. This is the full file:

    var React = require('react');
    var ReactQuill = require('react-quill');

    var SpeechBodyEditor = React.createClass({
      componentDidMount: function(){
        this.refs.bodyInput.focus();
      },
      render: function() {
        var value = "hello";
        return (
          <ReactQuill
              onChange={this._handleChange}
              value={value}
              ref="bodyInput" />
        );
      },
      _handleChange: function() {

      }
    });

    module.exports = SpeechBodyEditor;

**Comment by zenoamaro** [comment]
I've merged this API in master. You can try it, make sure you do a `make build` before to ensure the js files are fresh built.

**Comment by Predjo** [comment]
This still seems to be a problem. Seems that editor doesnt get saved into state for some reason.

**Comment by tomlagier** [comment]
Same issue - can't get a ref in the parent component.

**Comment by abhi-nav** [comment]
Hi guys,

This worked for me 

`this.reactQuillRef.getEditor().focus();`

ref={(el) => { this.reactQuillRef = el }}

**Comment by Abdulmoiz-Ahmer** [comment]
The below code worked for me: 
 This is my constructor:
```
 constructor(props) {
        super(props);
        this.contentRef = React.createRef();
    }
```


Below is my component in render method:
```
   <ReactQuill
                            value={this.state.fields.content}                     
                            ref={this.contentRef}
                         ></ReactQuill>
```

In my componentDidMount i focused on this component and it is below:
```
  componentDidMount() {
        this.contentRef.current.focus();
  }
```

**Comment by jMuzsik** [comment]
if using react hooks:

``` js
// custom hook
export const useFocusAndSetRef = (ref) => {
  ref = useCallback(
    (node) => {
      if (node !== null) {
        ref.current = node; // it is not done on it's own
        const len = node.unprivilegedEditor.getLength();
        const selection = { index: len, length: len };
        node.setEditorSelection(node.editor, selection);
      }
    },
    [ref]
  );
  return ref;
};

// in some component where the editor is used

  let editorRef;
  editorRef = useFocusAndSet(editorRef);
  ...
  <Editor
    editorRef={editorRef}
    editorState={editorState}
    setEditorState={setEditorState}
    theme="snow"
  />

// in the editor component (wrapper around react-quill

return (
    <ReactQuill
      ref={editorRef}
     ....
    />
)
```

This will focus at end of whatever content is already stored on load. To go to a specific part, `setEditorSelection` needs to be set accordingly

**Comment by Ashesashu860** [comment]
Just use ref to get the data as `editor.current.state.value` 

`<ReactQuill
      ref={editorRef}
     ....
    />`

**Comment by RikhsimovSunnatilla** [comment]
Dynamically importing <ReactQuill /> caused me to have ref and focus() not working.

**Comment by tanmayaBiswalOdiware** [comment]
> The below code worked for me: This is my constructor:
> 
> ```
>  constructor(props) {
>         super(props);
>         this.contentRef = React.createRef();
>     }
> ```
> 
> Below is my component in render method:
> 
> ```
>    <ReactQuill
>                             value={this.state.fields.content}                     
>                             ref={this.contentRef}
>                          ></ReactQuill>
> ```
> 
> In my componentDidMount i focused on this component and it is below:
> 
> ```
>   componentDidMount() {
>         this.contentRef.current.focus();
>   }
> ```

This works as long as a person wants to take away focus from other elements programmatically and put it on referenced editor. But you can't just start typing out form this focus. But it does bring up the editor toolbar if hidden. 

Worked for my use case.

**Comment by SKobilarov** [comment]
oljkilčlčkjčlč "@ @tomlagier 
![bike](https://user-images.githubusercontent.com/81570295/205930251-4e6da2a2-d676-413d-84ea-9ad2e29410a1.jpg)

**Comment by t-ashraf** [comment]
For function components, this is what I did to get 'autofocus' to work:

`useEffect(() => {
    let interval: NodeJS.Timer = null;
    if (autofocus) {
      if (reactQuillRef) {
        // reactQuillRef.current does not appear straight away due to dynamic import and NextJS
        // so we call 'setInterval' until we have access to the editor
        if (
          reactQuillRef.current === null ||
          reactQuillRef.current.editor === null
        ) {
          interval = setInterval(() => {
            if (reactQuillRef.current && reactQuillRef.current.editor) {
              reactQuillRef.current.editor.focus();
              clearInterval(interval);
            }
          }, 500);
        } else {
          reactQuillRef.current.editor.focus();
        }
      }
    }

    return () => {
      if (interval) {
        clearInterval(interval);
      }
    };
  }, [autofocus]);`

**Comment by AbduSalam08** [comment]
Hello

**Comment by AbduSalam08** [comment]
Hi
