### ISSUE TITLE
Unneeded <p><br/></p> gets inserted on editor intialization

### ISSUE THREAD

**Issue by lakesare** [zenoamaro/react-quill#250]
Codepen: https://codepen.io/alexkrolick/pen/xgyOXQ?editors=0010.

If I initalize an editor with `<p>Hi</p><h1>h1</h1>`, It gets transformed into
```html
<p>Hi</p>
<p><br></p>
<p><br></p>
<h1>h1</h1>
```

Notice inserted `<p><br></p>`.

I checked this with Quill, and it didn't have that issue.
`<p><br><p>` is inserted before any block elements, not only `h1`s.

**Comment by alexkrolick** [comment]
This could be due to the match visual option in Quill 1.3. Did you try updating your Quill dep and passing that flag in the clipboard config?

**Comment by lakesare** [comment]
@alexkrolick, hm hm.
What is a 'clipboard config' (I'm using Webpack, are we talking about some bundling options)?
My Quill is already version 1.3.0, and React-Quill is 1.0.0, should they be some other version?

**Comment by alexkrolick** [comment]
https://quilljs.com/docs/modules/clipboard/#matchvisual

You can pass something like this to the modules prop:
```
{
  clipboard: {
    matchVisual: false,
  }
}
```

**Comment by lakesare** [comment]
@alexkrolick, this worked! Thank you for beautiful library and fast support.
Also just found this issue: https://github.com/zenoamaro/react-quill/issues/235, they seem to be connected.

**Comment by the-simian** [comment]
This fixed a problem for me also.

**Comment by joelcolucci** [comment]
Thanks. The fix worked for me as well.

Working code below:
```javascript
<ReactQuill
    value={this.state.content}
    onChange={this.handleChange}
    theme="snow"
    modules={{
        clipboard: {
            matchVisual: false
        }
    }} />
```

**Comment by douglasrcjames** [comment]
I tried implementing the matchVisual, but it still seems to be giving me that paragraph and br tags in there. Here is a code pen showing simple changes to the quill demo setup, and it still doesn't work. https://codepen.io/douglasrcjames/pen/zYGvMPd 

I am probably doing something just a tad bit wrong, any ideas?

**Comment by Maclay74** [comment]
It doesn't work, `matchVisual` was even deprecated and removed.

**Comment by adrianszablowski** [comment]
What to use instead of `matchVisual`?
