### ISSUE TITLE
Remove empty spaces after and before the text

### ISSUE THREAD

**Issue by hmontes** [zenoamaro/react-quill#251]
How can i remove the empty spaces after and before the text?

from
```
<p>     </p><p><br></p><p>Text</p><p><br></p><p>      </p><p><br></p><p>Another Text</p><p>                </p>
```

to
```
<p>Text</p><p><br></p><p>      </p><p><br></p><p>Another Text</p>
````

Or .. if you see
From
```


Text



Another Text

```

To
```
Text



Another Text
```

Thank you

(Maybe a trip() between tags can help)

**Comment by alexkrolick** [comment]
Does the fix from https://github.com/zenoamaro/react-quill/issues/235 help?

**Comment by hmontes** [comment]
Temp fix. (Not ideal)

```
export const cleanHtml = (html) => {
  // Clean spaces between tags
  var newText = html.replace(/(<(pre|script|style|textarea)[^]+?<\/\2)|(^|>)\s+|\s+(?=<|$)/g, "$1$3")
  
// Clean empty paragraphs before the content
  // <p><br/><p> && <p></p>
  var slicer;
  while (newText.slice(0, 7) === '<p></p>' || newText.slice(0, 11) === '<p><br></p>') {
    if (newText.slice(0,7) === '<p></p>') slicer = 7
    else slicer = 11
    newText = newText.substring(slicer, newText.length)
  }

    // Clean empty paragraphs after the content
  while (newText.slice(-7) === '<p></p>' || newText.slice(-11) === '<p><br></p>') {
    if (newText.slice(-7) === '<p></p>') slicer = 7
    else slicer = 11
    newText = newText.substring(0, newText.length - slicer)
  }
  // Return the clean Text
  return newText
}
```

So. For your solution. I need to upgrade core Quill to 1.3.0. But i don't understand the instructions.

I need to modify the ./node_modules/react-quill/packaje.son file? From "quill": "^1.2.6" to 

```
"dependencies": {
    "lodash": "^4.17.4",
    "quill": "^1.3.0"  
  },
```

And run npm install ??

**Comment by hmontes** [comment]
Okey. I saw the solution but you don't understand me. The problem is not when your paste content.

In Github. Try to Click the word "Text" and hit three times enter

**Comment by hmontes** [comment]
Text

**Comment by hmontes** [comment]
If you see. You only see the "Text" word and don't see the two lines after the content. In Quill you see the line breaks. So. I want to fix that issue.

**Comment by alexkrolick** [comment]
Quill is a WYSIWYG editor, so removing whitespace automatically would be surprising. How you post-process the HTML is up to you; your regex parser seems to be doing the trick.

**Comment by hmontes** [comment]
The regex only remove empty lines between tags.  from <p>    some content   </p> to <p>some content</p>

I'm looking an easy way to drop (delete, eliminate, trim. Sorry. I'm not english native) the blank space between the main content. Like Facebook, Linkedin, Github, Slack and almost all text editors. Do you know another one way to handle this problem?

**Comment by ShirlyChan** [comment]
Now I need to retain the white space between tags, such as <p> some content </p>,but now it becomes <p>some content</p>, any solutions? ths~

**Comment by ShirlyChan** [comment]
Now I need to retain the white space between tags, such as
<p> some content </p>,but now it becomes <p>some content</p>, any solutions? ths~
