### ISSUE TITLE
onHover (on entire editor area) results in selecting bold

### ISSUE THREAD

**Issue by shman2000** [zenoamaro/react-quill#254]
Every time when I hover over quill editor Bold in the toolbar is highlighted and on click (anywhere on the editor area) it gets selected.

Component code looks as follows:

```jsx
import React, { Component } from 'react'

import theme from 'react-quill/dist/quill.snow.css'

export default class JobHtmlEditor extends Component {
  constructor(props) {
    super(props)
    if (typeof window !== 'undefined') {
      this.ReactQuill = require('react-quill')
    }
  }

  render() {
    var { onContentChange } = this.props;
    const ReactQuill = this.ReactQuill;

    if (typeof window !== 'undefined' && ReactQuill) {
      return (
        <ReactQuill
          onChange={onContentChange.bind(this)}
          value={this.props.value}
          modules={{toolbar: [
            ['bold', 'italic'],
            [{'list': 'ordered'},{'list': 'bullet'}]
          ]}}
          formats={[
            'bold', 'italic',
            'list', 'bullet'
          ]}
          className={"m-t-2"}
        />
      )
    } else {
      return <textarea />;
    }
  }
}
```

And I use it this way:

```jsx
<JobHtmlEditor value={this.state.description}
     onContentChange={this.handleChangeDescription.bind(this)} />
```

Any ideas?

#### Quill version 
- [ ] 1.0.0

**Comment by alexkrolick** [comment]
@shman2000 Unfortunately I cannot reproduce this behavior: https://codepen.io/alexkrolick/pen/xLgPMe?editors=0010

It is probably due to something outside the component.

**Comment by maxim-pushchinskiy** [comment]
I had the same problem. In my the reason of bug was the `label` wrapper. Maybe it will save time for someone.

**Comment by brandonleboeuf** [comment]
> I had the same problem. In my case the reason of bug was the `label` wrapper. Maybe it will save time for someone.

This was my problem!! Thank you

**Comment by emillium** [comment]
I am having this issue, and when I remove the label I no longer have the issue. However, for Formik validation and behaviour, I need the component to be within the label. Why would this be occurring inside the label? Is there a fix or workaround that does not involve removing the label?

**Comment by sgtpenguin** [comment]
Incredible.  Thank you @maxim-pushchinskiy!  Saved my morning.

@emillium The reason the `label` breaks it (I realize now) is that clicking on a `label` focuses any wrapped input and in this case the first focus target in quill is the first button in the toolbar.
