### ISSUE TITLE
TypeError: Cannot read property 'renderToStaticMarkup' of undefined

### ISSUE THREAD

**Issue by Nemsae** [zenoamaro/react-quill#256]
The issue occurs when I am trying to render ReactQuill as a component. This project doesn't use 'imports/requires' for libraries, instead we're accessing the libraries via globals. So even though React isn't defined in the file, I still can create components as React is a global. I am doing the same with ReactQuill.

This is my component: 
```
console.log('ReactQuill: ', ReactQuill, typeof ReactQuill)

export default class TextEditor extends React.Component {
  constructor () {
    super()
    this.state = {
      text: '',
    }
    this.handleTextEditorChange = (text) => this.setState({ text })
  }

  render () {
    return (
      <div className='editor-container'>
        TextEditor.jsx
        <ReactQuill
          value={this.state.text}
          onChange={this.handleTextEditorChange}
        />
      </div>
    )
  }
}
```

Here is an image that shows the console log, and also the error thrown from the render() of the component:
<img width="388" alt="reactquill render error" src="https://user-images.githubusercontent.com/20247504/29244954-8186a440-7f7d-11e7-876e-f495c7d7b7eb.png">

Any direction or advice would be greatly appreciated.

#### Quill version 
- [X] master

**Comment by alexkrolick** [comment]
Are you using the UMD build? The Codepen examples are setup similarly with script tags and seem to be functioning: https://codepen.io/alexkrolick/pen/xgyOXQ

**Comment by alexkrolick** [comment]
@Nemsae Did you resolve this issue or do you think this should stay open?

**Comment by Nemsae** [comment]
@alexkrolick Issue was that there was not react-dom to access that method renderStaticToMarkup.

**Comment by kirincc** [comment]
> @alexkrolick Issue was that there was not react-dom to access that method renderStaticToMarkup.

Hi, did you solve this error and how ?
