### ISSUE TITLE
How to upload the image to the server directly rather than saving base64 string?

### ISSUE THREAD

**Issue by Albinzr** [zenoamaro/react-quill#257]
How to upload the image to the server directly rather than saving base64 string?

Is there any handler for image upload in react-quill

#### Quill version 

1.0.0

**Comment by alexkrolick** [comment]
See #248, #243, #224 for previous discussion.

There is a package on NPM that enables auto-upload as a Quill module, which you can enable similarly to the resize module here: https://github.com/zenoamaro/react-quill/issues/224#issuecomment-311933020
