### ISSUE TITLE
Source text

### ISSUE THREAD

**Issue by khotey** [zenoamaro/react-quill#260]
Have toolbar option to show source text ? Toggle on it and see source code with html

**Comment by alexkrolick** [comment]
Like this? https://codepen.io/alexkrolick/pen/XgaVVX

**Comment by theskillwithin** [comment]
@alexkrolick  im trying to do this so users can edit the html.

like this https://codepen.io/anon/pen/ZyEjrQ

having a hard time figuring out how to with react-quill

**Comment by theskillwithin** [comment]
I get odd behavior like this. for example if i type test it puts each in its own tag
https://www.dropbox.com/s/l0u5xo3f0rra7cr/Screenshot%202017-10-10%2016.08.47.png?dl=0

however if i type in the normal quill first, then carefully only type between existing tags it will work as intended.

https://gist.github.com/theskillwithin/a2c4f9ad59216529ed157645ac217c9e

**Comment by alexkrolick** [comment]
Did you see the [codepen link](https://codepen.io/alexkrolick/pen/XgaVVX) above? It seems like it is 1-1 with what the pure Quill does.

Bear in mind that only formats allowed by the Quill config will be allowed through.

**Comment by theskillwithin** [comment]
@alexkrolick yes, but notice if you try typing into the source, if you type test it outputs this
https://www.dropbox.com/s/lc2whhomtypsph6/Screenshot%202017-10-11%2010.45.03.png?dl=0

making it hard for someone who wants to just write in html.

**Comment by alexkrolick** [comment]
OK, good point. Fixed the example to keep the editor HTML and raw HTML in different states, syncing when you toggle the button: https://codepen.io/alexkrolick/pen/XgaVVX

**Comment by theskillwithin** [comment]
Excellent that does the trick!  Thankyou!!!
