### ISSUE TITLE
Setting the source HTML in editor

### ISSUE THREAD

**Issue by zeeshanjan82** [zenoamaro/react-quill#263]
I have been able to add a custom 'Add HTML' button in the toolboar where users can click and a modal window opens where the user can directly enter the HTML string which I then assign to the ReactQuill editor using value property. However when I try to assign the string value as:
```HTML
<div style="vertical-align: bottom; padding: 10px 0px 0px 0px;" align="center"><a style="vertical-align: bottom; max-width: 100%;" title="Newsletter_Top_Leaderboard" href="http://axis.portfolio-adviser.com/axa-global-short-duration-bond/"><img src="http://www.portfolio-adviser.com/w-images/root_images/dd2fae41-3b39-443e-932e-4744d879cb07/3/AXIS-LB-728-90-Jun17.gif" alt="Newsletter_Top_Leaderboard" /></a></div>
```
It strips out the div tags and replaces them with <p> tags and then the style which is applied on <div> tag is also removed. I wanted to have the exact same text rendered inside the editor.

**Comment by alexkrolick** [comment]
@zeeshanjan82 This is more of a question on how to use [Quill](https://github.com/quills/quill/). Quill is a text editor, not an HTML editor, so it may not behave exactly as you like when passing inline styles. It does, however, allow you to create custom formats that behave as you want. See https://quilljs.com for docs.

**Comment by kingcc** [comment]
Do it like this,
This demo will show you how to fix `ql align` class to HTML inline-styles:
```
  parseToDOM(str) {
    let div = document.createElement('div');
    div.innerHTML = str;
    return div.childNodes;
  }
  handleChange(value, delta, source, editor) {
    let targetList = this.parseToDOM(value);
    let targetListString = '';
    for (let target of targetList) {
      target.classList.forEach((className) => {
        let hit = /^ql-align-(.*)$/.exec(className);
        if (hit) {
          target.style.textAlign = hit[1];
        }
      });
      targetListString += target.outerHTML;
    }
    this.props.onChange(targetListString);
  }
```
