### ISSUE TITLE
How to insert html tag when insert video embedded  or image ?

### ISSUE THREAD

**Issue by vominhtam** [zenoamaro/react-quill#265]
Hi all,
I want to insert html tag  when insert video embedded  or image. example I want move iframe tag into p tag.

I don't know how to do it. Please help me. 

Thank all so much

**Comment by mateosantosdev** [comment]
any idea how to solve this ? I need to move iframe tag into another div

**Comment by alexkrolick** [comment]
You would want to write a Quill Parchment blot for the tag to implement this

**Comment by mateosantosdev** [comment]
Thanks @alexkrolick
