### ISSUE TITLE
Clickable links

### ISSUE THREAD

**Issue by nickvoronin** [zenoamaro/react-quill#267]
Is there a way to make links inside the Editor clickable?

**Comment by alexkrolick** [comment]
You can highlight a piece of text and click the 🔗 icon in the toolbar, or Ctrl-K/Cmd-K.

**Comment by nickvoronin** [comment]
@alexkrolick this is not my case. I needed pasted text to become a link instantly (when it is indeed a link).
To solve it I used linkifyHtml

`import linkifyHtml from 'linkifyjs/html';`
...
`handleChange = html => {`
`    const editorHtml = linkifyHtml(html);`
`    this.setState({ editorHtml });`
`};`
It does exactly what I needed. 
Thank you anyway!

**Comment by dnajjar** [comment]
How would I enable the link format @alexkrolick ?
