### ISSUE TITLE
Toolbar Spacing Issue

### ISSUE THREAD

**Issue by slipperypenguin** [zenoamaro/react-quill#268]
Is there a way to fix the spacing between buttons in the toolbar using the snow theme?
I am using a setup almost exactly like the  example on [codepen](https://codepen.io/alexkrolick/pen/xgyOXQ?editors=0010), but getting the spacing issue in the image below.

I've tried different version of nesting the `Editor.modules` array, and have even tried finding a fix in the `react-quill/dist/quill.snow.css` file with no solution.

Any help would be greatly appreciated!

![screen shot 2017-09-14 at 12 07 53 pm](https://user-images.githubusercontent.com/3655354/30444238-3a42015a-9950-11e7-9a21-4d0219660fe2.png)

**Comment by alexkrolick** [comment]
do you have something setting `text-align: justify` or some type of flex targeting `.ql-toolbar`, `.quill`, `.ql-editor`? If you're using the same CSS file as Codepen, it's probably not an issue with the package itself.

**Comment by slipperypenguin** [comment]
@alexkrolick still no luck. I'm using [Grommet](https://grommet.github.io/) as a component library and even went through that and everything seemed fine. For now I just added the `quill.snow.css` file from the main Quill project and have been manually trying to tweak things

**Comment by alexkrolick** [comment]
Do you have a Codepen link to reproduce the issue? What classes are you adding to the wrappers around the component?
