### ISSUE TITLE
How to set video not autoplay and not loop play

### ISSUE THREAD

**Issue by Anoiing** [zenoamaro/react-quill#270]
I insert a video in the editor, but it plays auto when document loaded, I want to set video, but it rendered in a frame label, How to set it , thanks...

**Comment by alexkrolick** [comment]
You may want to look into custom Quill modules. You can set autoplay=false on HTML media tags, so it should be possible to create a Quill format that does that.

- https://quilljs.com/docs/modules/
- https://github.com/zenoamaro/react-quill#custom-formats
- https://github.com/quilljs/quill
