### ISSUE TITLE
Errors when Imported

### ISSUE THREAD

**Issue by bradennapier** [zenoamaro/react-quill#272]
Thanks for filing an issue! 

### FAQ

Using the latest from npm (just installed) , I can't even import this into my project.

```
asyncComponent.js:189 TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Object.eval (core.js:51)
    at eval (core.js:53)
    at Object../node_modules/quill/core.js (renderer.dev.dll.js:17401)
    at __webpack_require__ (renderer.dev.dll.js:21)
    at Object.eval (quill.js:2)
    at eval (quill.js:138)
```

The module is being packaged with webpack and the "noParse" value is set as described.

All I do is import

```
import ReactQuill from 'react-quill'
```

and i get the above

**Comment by alexkrolick** [comment]
It sounds like this is an error with asyncComponent, according to the issue you filed with it: https://github.com/ctrlplusb/react-async-component/issues/58
