### ISSUE TITLE
how to add more fonts to ReactQuill

### ISSUE THREAD

**Issue by tylerkrett** [zenoamaro/react-quill#273]
Hey Guys,

I am having issues with adding fonts to ReactQuill.

Currently I cannot find any help on this and I found a thread but now that way is deprecated.

Would be great if some one had a working piece to show me

**Comment by alexkrolick** [comment]
Do you want to add more fonts to the drop-down or change the default font? The latter you can do with CSS targeting the class `quill ql-editor`.

**Comment by tylerkrett** [comment]
I need to change the drop down of fonts.

I am really struggling :(

**Comment by alexkrolick** [comment]
https://codepen.io/alexkrolick/pen/NapmrE?editors=0110

Not quite done, but take a look at this and the Quill docs: https://quilljs.com/playground/#custom-fonts

**Comment by tylerkrett** [comment]
Thank you so much Alex for your assistance but I am using the html custom toolbar.

when using  the code:

const Font = this.Quill.import('formats/font'); ??? where is it finding this
        Font.whitelist = ['mirza', 'roboto'] ; is this being appended below ?
        this.Quill.register(Font, true); 
        


import React, { Component, PureComponent } from 'react';
import PropTypes from 'prop-types';
import ReactQuill, { Quill } from 'react-quill';


class CustomToolbar extends PureComponent {
    /**
    * @constant propTypes
    * @type {Object}
    */
   static propTypes = {
      
   };

   static defaultProps = {
       
   }
   /**
    * @method render
    * @return {XML}
    */
   render() {
       return (
            <div id="quill-toolbar">
                <select className="ql-size">

                </select>
                <select defaultValue="ubuntu" className="ql-font">
                    <option value="ubuntu">Ubuntu</option>
                    <option value="mirza">Mirza</option>
                    <option value="roboto">Roboto</option>
                </select>
                <button className="ql-list" value="ordered" ></button>  
                <button className="ql-list" value="bullet" ></button> 
                <select className="ql-align"></select>
                <button className="ql-bold"></button>
                <button className="ql-italic"></button>
                <button className="ql-underline"></button>
                <button className="ql-strike"></button> 
                <button className="ql-link"></button> 
                <button className="ql-video"></button> 
                <button className="ql-image"></button> 
                
            </div>
       );

   }
}

export default class TextArea extends Component {
    
    
    /**
     * @constant propTypes
     * @type {Object}
     */
    static propTypes = {
        
    };

    /**
     * @constant defaultProps
     * @type {Object}
     */
    static defaultProps = {
    };

    /**
     * @constant state
     * @type {Object}
     */
    state = {
        text: ''
    }

    handleChange(event) {
        this.setState({text: event})
    }

    /**
     * @method componentDidMount
     * @return {Promise}
     */
    componentDidMount() {
     
    }
    
      render() {
        const Font = this.Quill.import('formats/font');
        Font.whitelist = ['mirza', 'roboto'];
        this.Quill.register(Font, true);
        
        const modules = {
            toolbar: {
                container: '#quill-toolbar'
            }
        }
        
        const formats = [
            'size','bold', 'italic', 'underline', 'strike',
            'list', 'bullet', 'indent','link', 'image','font','color','background',
            'align', 'direction', 'video', 'script'
        ]

        return (
            <section className="quill-container">

                <CustomToolbar />
                <ReactQuill 
                    className="quill-editor"
                    value={this.state.text}
                    onChange={this.handleChange.bind(this)}
                    formats={formats}
                    modules={modules}
                />
            </section>
        );
    }
}

**Comment by alexkrolick** [comment]
```
const Font = ReactQuill.Quill.import('formats/font'); // <<<< ReactQuill exports it
Font.whitelist = ['mirza', 'roboto'] ; // allow ONLY these fonts and the default
ReactQuill.Quill.register(Font, true);
```

**Comment by tylerkrett** [comment]
Alex you are a star mate :)

Right now im working on making and Arbitrary colour picker for React Quill. so people can use hexadecimal values for colours. Once I am done I will make a github repo for people enjoy. Here I go hope I can do it haha

**Comment by volkandkaya** [comment]
@tylerkrett long time since your message but was wondering how the colour picker was going.

**Comment by jbowen28** [comment]
@alexkrolickc  I can't see that your custom fonts are working.  All I see in the dropdown and get rendered is 'San Serif'.

**Comment by swustzl** [comment]
@jbowen28 What is the solution to this problem? font is all 'San Serif'

**Comment by mmcshinsky** [comment]
@swustzl I did a workout for the 'San Serif' below for fonts and font sizes:
```
  .ql-picker.ql-font {
    .ql-picker-item {
      font-size: 0;
      &:before {
        content: attr(data-value) !important;
        font-size: 14px;
      }
    }
  }
```

**Comment by andrewcodes404** [comment]
@mmcshinsky I added this to get the font being used to show as the picker label
```
.ql-picker.ql-font{
  .ql-active {
    &:before {
      content: attr(data-value) !important;
      font-size: 14px;
    }
  }
}
```

I've been trying to get the selects to match the fonts, I came up with this that works but it's a bit manual  is there anyway to use the` attr(data-value)` to set the font and make it a little more dynamic? 🤔 

```
.ql-font .ql-picker-options span[data-value="Ubuntu"]::before {
  font-family: "Ubuntu";
}

.ql-font .ql-picker-options span[data-value="Raleway"]::before {
  font-family: "Raleway";
}

.ql-font .ql-picker-options span[data-value="Roboto"]::before {
  font-family: "Roboto";
}
```

**Comment by rohanmohapatra** [comment]
@mmcshinsky I tried the **css** you provided, still shows **Sans-Serif** in the picker. Is there a workaround or could you share a codepen , so that I can see it in action?

**Comment by ialeidan** [comment]
I know this is an old issue, but for future searchers, here is how I solved it:

In the examples, they did it like this (_**which did not work for me**_):
```
#toolbar-container .ql-font span[data-label="lateef"]::before {
    font-family: "Lateef", cursive;
}

#toolbar-container .ql-font span[data-label="markazi-text"]::before {
    font-family: 'Markazi Text', serif;
} 
```

This did not work for me.

**What worked is:**
```
.ql-picker.ql-font .ql-picker-label[data-value="lateef"]::before, 
.ql-picker.ql-font .ql-picker-item[data-value="lateef"]::before
{
    font-family: "Lateef", cursive;
    content: "Lateef";
}

.ql-picker.ql-font .ql-picker-label[data-value="markazi-text"]::before, 
.ql-picker.ql-font .ql-picker-item[data-value="markazi-text"]::before
{
    font-family: 'Markazi Text', serif;
    content: "Markazi";
}
```

As you can see, the changes are:
-  "data-label" is changed to "data-value".
-  added "content: "FONT_NAME";" 


Here is a sample of a not properly working example: 
[https://codepen.io/alexkrolick/pen/NapmrE?editors=0110.](https://codepen.io/alexkrolick/pen/NapmrE?editors=0110.
)

Here is the same code after modification:
[https://codepen.io/ialeidan/pen/xxwrBMK?editors=0110.](https://codepen.io/ialeidan/pen/xxwrBMK?editors=0110.)

_**I am NOT a CSS expert, but that what worked for me :)**_

**Comment by imsks** [comment]
### Finally, I found it.
### Feel free to skip steps if already done
**Step 1 - Setup** 
```
import ReactQuill from "react-quill";
import "react-quill/dist/quill.snow.css";
const Quill = ReactQuill.Quill;
var Font = Quill.import("formats/font");
Font.whitelist = ["Roboto", "Raleway", "Montserrat", "Lato", "Rubik"];
Quill.register(Font, true);`
```

**Step 2 - Setup Modules and Formats**
```
modules = {
    toolbar: [
      [{ header: "1" }, { header: "2" }, { font: Font.whitelist }],
      ["bold", "italic", "underline", "strike", "blockquote"],
      [{ color: [] }, { background: [] }],
      [{ align: [] }],
      [
        { list: "ordered" },
        { list: "bullet" },
        { indent: "-1" },
        { indent: "+1" },
      ],
      ["link", "image", "video"],
      [{ script: "sub" }, { script: "super" }],
    ],
  };

  formats = [
    "header",
    "font",
    "bold",
    "italic",
    "underline",
    "strike",
    "blockquote",
    "background",
    "code",
    "script",
    "list",
    "bullet",
    "indent",
    "link",
    "image",
    "video",
  ];
```

**Step 3 - Render on the screen** 
```
render() {
    return (
      <main>
        <ReactQuill
          theme="snow"
          modules={this.modules}
          formats={this.formats}
        />
      </main>
    );
  }
```

**Step 4 - Fix the CSS**
**Take a look and change accordingly depending on the fonts you are using**
**It's simple code written for every font**
```
.ql-picker.ql-font {
  .ql-picker-item {
    font-size: 0;
    &:before {
      content: attr(data-value) !important;
      font-size: 14px;
    }
  }
}

.ql-picker.ql-font{
  .ql-active {
    &:before {
      content: attr(data-value) !important;
      font-size: 14px;
    }
  }
}

.ql-picker.ql-font .ql-picker-label[data-value="Roboto"]::before, 
.ql-picker.ql-font .ql-picker-item[data-value="Roboto"]::before
{
    font-family: "Roboto", cursive;;
    content: "Roboto" !important;
}

.ql-picker.ql-font .ql-picker-label[data-value="Raleway"]::before, 
.ql-picker.ql-font .ql-picker-item[data-value="Raleway"]::before
{
    font-family: "Raleway", cursive;;
    content: "Raleway" !important;
}

.ql-picker.ql-font .ql-picker-label[data-value="Montserrat"]::before, 
.ql-picker.ql-font .ql-picker-item[data-value="Montserrat"]::before
{
    font-family: "Montserrat", cursive;;
    content: "Montserrat" !important;
}

.ql-picker.ql-font .ql-picker-label[data-value="Lato"]::before, 
.ql-picker.ql-font .ql-picker-item[data-value="Lato"]::before
{
    font-family: "Lato", cursive;;
    content: "Lato" !important;
}

.ql-picker.ql-font .ql-picker-label[data-value="Rubik"]::before, 
.ql-picker.ql-font .ql-picker-item[data-value="Rubik"]::before
{
    font-family: "Rubik", cursive;;
    content: "Rubik" !important;
}

/* Set content font-families */
.ql-font-Roboto {
  font-family: "Roboto";
}
.ql-font-Raleway {
  font-family: "Raleway";
}
.ql-font-Montserrat {
  font-family: "Montserrat";
}
.ql-font-Lato {
  font-family: "Lato";
}
.ql-font-Rubik {
  font-family: "Rubik";
}
```
### The Output
![3](https://user-images.githubusercontent.com/29145481/85171995-c3015a00-b28d-11ea-85ad-3b69c493e804.JPG)

**Comment by fMagVen** [comment]
how do I add downloaded fonts? Tried all of these and none worked.

**Comment by swustzl** [comment]
邮件已收到~我会尽快给您回复的~

**Comment by Gourishmesta** [comment]
> ### Finally, I found it.
> ### Feel free to skip steps if already done
> **Step 1 - Setup**
> 
> ```
> import ReactQuill from "react-quill";
> import "react-quill/dist/quill.snow.css";
> const Quill = ReactQuill.Quill;
> var Font = Quill.import("formats/font");
> Font.whitelist = ["Roboto", "Raleway", "Montserrat", "Lato", "Rubik"];
> Quill.register(Font, true);`
> ```
> 
> **Step 2 - Setup Modules and Formats**
> 
> ```
> modules = {
>     toolbar: [
>       [{ header: "1" }, { header: "2" }, { font: Font.whitelist }],
>       ["bold", "italic", "underline", "strike", "blockquote"],
>       [{ color: [] }, { background: [] }],
>       [{ align: [] }],
>       [
>         { list: "ordered" },
>         { list: "bullet" },
>         { indent: "-1" },
>         { indent: "+1" },
>       ],
>       ["link", "image", "video"],
>       [{ script: "sub" }, { script: "super" }],
>     ],
>   };
> 
>   formats = [
>     "header",
>     "font",
>     "bold",
>     "italic",
>     "underline",
>     "strike",
>     "blockquote",
>     "background",
>     "code",
>     "script",
>     "list",
>     "bullet",
>     "indent",
>     "link",
>     "image",
>     "video",
>   ];
> ```
> 
> **Step 3 - Render on the screen**
> 
> ```
> render() {
>     return (
>       <main>
>         <ReactQuill
>           theme="snow"
>           modules={this.modules}
>           formats={this.formats}
>         />
>       </main>
>     );
>   }
> ```
> 
> **Step 4 - Fix the CSS** **Take a look and change accordingly depending on the fonts you are using** **It's simple code written for every font**
> 
> ```
> .ql-picker.ql-font {
>   .ql-picker-item {
>     font-size: 0;
>     &:before {
>       content: attr(data-value) !important;
>       font-size: 14px;
>     }
>   }
> }
> 
> .ql-picker.ql-font{
>   .ql-active {
>     &:before {
>       content: attr(data-value) !important;
>       font-size: 14px;
>     }
>   }
> }
> 
> .ql-picker.ql-font .ql-picker-label[data-value="Roboto"]::before, 
> .ql-picker.ql-font .ql-picker-item[data-value="Roboto"]::before
> {
>     font-family: "Roboto", cursive;;
>     content: "Roboto" !important;
> }
> 
> .ql-picker.ql-font .ql-picker-label[data-value="Raleway"]::before, 
> .ql-picker.ql-font .ql-picker-item[data-value="Raleway"]::before
> {
>     font-family: "Raleway", cursive;;
>     content: "Raleway" !important;
> }
> 
> .ql-picker.ql-font .ql-picker-label[data-value="Montserrat"]::before, 
> .ql-picker.ql-font .ql-picker-item[data-value="Montserrat"]::before
> {
>     font-family: "Montserrat", cursive;;
>     content: "Montserrat" !important;
> }
> 
> .ql-picker.ql-font .ql-picker-label[data-value="Lato"]::before, 
> .ql-picker.ql-font .ql-picker-item[data-value="Lato"]::before
> {
>     font-family: "Lato", cursive;;
>     content: "Lato" !important;
> }
> 
> .ql-picker.ql-font .ql-picker-label[data-value="Rubik"]::before, 
> .ql-picker.ql-font .ql-picker-item[data-value="Rubik"]::before
> {
>     font-family: "Rubik", cursive;;
>     content: "Rubik" !important;
> }
> 
> /* Set content font-families */
> .ql-font-Roboto {
>   font-family: "Roboto";
> }
> .ql-font-Raleway {
>   font-family: "Raleway";
> }
> .ql-font-Montserrat {
>   font-family: "Montserrat";
> }
> .ql-font-Lato {
>   font-family: "Lato";
> }
> .ql-font-Rubik {
>   font-family: "Rubik";
> }
> ```
> 
> ### The Output
> ![3](https://user-images.githubusercontent.com/29145481/85171995-c3015a00-b28d-11ea-85ad-3b69c493e804.JPG)

@imsks Where did u add the fonts folder?
var Font = Quill.import("formats/font"); => what is the location of this?
it has ttf files correct?
I am getting below error

![image](https://user-images.githubusercontent.com/16563121/228525795-74dcfacf-6cf3-4f59-ad8c-4979d0431faf.png)


Thank you

**Comment by swustzl** [comment]
邮件已收到~我会尽快给您回复的~

**Comment by ejkkan** [comment]
Has anyone got this working with NextJs?

**Comment by swustzl** [comment]
邮件已收到~我会尽快给您回复的~

**Comment by ejkkan** [comment]
Solved by using the component with dynamic import to make the component CSR:

```
const TextEditCsr = dynamic(
  () => import('./TextEdit'),
  { ssr: false } // This will make the component only rendered on client-side
);
```

**Comment by ajaykumar1071999** [comment]
Can we show the font-size on dropdown

**Comment by KhizerWHussain** [comment]
I am struggling with this issue i wants to add some custom fonts in font dropdown how to do that i am using react.js

const ReactQuillWrapper = styled(ReactQuill)(() => {
  return {
    '& .ql-font .ql-picker-options span[data-value="TT Interphases Pro Trial Regular"]::before':
      {
        fontFamily: 'TT Interphases Pro Trial Regular',
      },
    '& .ql-font .ql-picker-options span[data-value="Ubuntu"]::before': {
      fontFamily: 'Ubuntu',
    },
    '& .ql-font .ql-picker-options span[data-value="Raleway"]::before': {
      fontFamily: 'Raleway',
    },
    '& .ql-font .ql-picker-options span[data-value="Roboto"]::before': {
      fontFamily: 'Roboto',
    },
    '& .ql-editor, & .ql-container': {
      maxHeight: '100% !important',
    },
    '& .ql-toolbar': {
      borderRadius: '8px 8px 0 0',
    },
    '& .ql-container': {
      borderRadius: '0 0 8px 8px',
      minHeight: 150,
      maxHeight: 200,
    },

    '& .ql-picker.ql-font': {
      '& .ql-active': {
        '&:before': {
          content: 'attr(data-value) !important',
          fontSize: '12px',
        },
      },
    },

    '.ql-picker.ql-font .ql-picker-label[data-value="lateef"]::before, .ql-picker.ql-font .ql-picker-item[data-value="lateef"]::before':
      {
        fontFamily: 'Lateef',
      },
    '.ql-picker.ql-font .ql-picker-label[data-value="lateef"]::before, .ql-picker.ql-font .ql-picker-item[data-value="Roboto"]::before':
      {
        fontFamily: 'Roboto',
      },
  };
});
const toolbar = [
    ['bold', 'italic', 'underline', 'strike'],
    [{font: []}],
    [{list: 'ordered'}, {list: 'bullet'}],
    [{indent: '-1'}, {indent: '+1'}],
    [{script: 'sub'}, {script: 'super'}],
    [{header: [1, 2, 3, 4, 5, 6, false]}],
    ['blockquote', 'code-block', 'link'],
    [{direction: 'rtl'}],
    [{color: []}, {background: []}],
    [{align: []}],
    [{direction: 'rtl'}],
    ['clean'],
  ];

 <ReactQuillWrapper
            modules={{
              toolbar,
            }}
            formats={formats}
            theme='snow'
            className='description'
            preserveWhitespace={true}
            placeholder='Description here'
            onChange={(value) => setFieldValue('description', value)}
            key={'description'}
            id='description'
            value={values.description || ''}
          />

**Comment by yashvichauhan** [comment]
Can anyone please help with the below configurations 
import React from 'react';
import ReactQuill, { Quill } from 'react-quill';
import 'react-quill/dist/quill.snow.css';
import './textEdit.module.css';

function TextEditor(props){
    const Font = Quill.import('formats/font');
    Font.whitelist = ['Ubuntu', 'Raleway', 'Roboto'];
    Quill.register(Font, true);

    const modules = {
        toolbar: [
            [{ 'header': '1'}, {'header': '2'}, { 'font': Font.whitelist }],
            ['bold', 'italic', 'underline', 'strike', 'blockquote'],
            [{'list': 'ordered'}, {'list': 'bullet'}, 
                {'indent': '-1'}, {'indent': '+1'}],
            ['link', 'image', 'video'],
            ['clean']
        ],
        clipboard: {
          // toggle to add extra line breaks when pasting HTML:
          matchVisual: false,
        }
    };
      
    const formats = [
        'header', 'font', 'size',
        'bold', 'italic', 'underline', 'strike', 'blockquote',
        'list', 'bullet', 'indent',
        'link', 'image', 'video'
    ];

    return(
        <ReactQuill 
            theme={"snow"}
            onChange={props.handleChange}
            value={props.value}
            modules={modules}
            formats={formats}
            // bounds={'.app'}
            placeholder={props.placeholder}
        />
    )
}

export default TextEditor;

The css file: 
/* Set default font-family */
.app .ql-editor {
  font-family: "Ubuntu";
}

/* Set dropdown font-families */

.ql-picker.ql-font .ql-picker-label[data-value="Ubuntu"]::before,
.ql-picker.ql-font .ql-picker-item[data-value="Ubuntu"]::before {
  font-family: "Ubuntu", cursive;
  content: "Ubuntu";
}

.ql-picker.ql-font .ql-picker-label[data-value="Raleway"]::before,
.ql-picker.ql-font .ql-picker-item[data-value="Raleway"]::before {
  font-family: "Raleway", cursive;
  content: "Raleway";
}

.ql-picker.ql-font .ql-picker-label[data-value="Roboto"]::before,
.ql-picker.ql-font .ql-picker-item[data-value="Roboto"]::before {
  font-family: "Roboto", cursive;
  content: "Roboto";
}

/* Set content font-families */
.ql-font-Raleway {
  font-family: "Raleway";
}

.ql-font-Roboto {
  font-family: "Roboto";
}
I am still seeing the attached dropdown; the configurations are same but it is not overriding the css it seems.
![image](https://github.com/user-attachments/assets/34f549e2-c938-4e65-90e9-569abf10d411)

**Comment by Vikmanatus** [comment]
For anyone struggling on this, that has tried this kind of snippets : 
```css
.ql-picker.ql-font .ql-picker-label[data-value="merriweather"]::before,
.ql-picker.ql-font .ql-picker-item[data-value="merriweather"]::before {
  content: "Merriweather";
  font-family: var(--font-merriweather);
}
```

In order for this to work,  a simple workaround is to add a `!important` at the end of the content property 

If your on Next.js, you'll have something like this : 


## `layout.tsx`

```tsx
import { Merriweather } from "next/font/google";

const merriweather = Merriweather({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
  variable: "--font-merriweather",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
        ${merriweather.variable}
      `}
      >
        {children}
      </body>
    </html>
  );
}
```


## `globals.css`

```css
:root {
  --font-merriweather: "Merriweather", serif;
}

.ql-font-merriweather {
  font-family: var(--font-merriweather);
}

.ql-picker.ql-font .ql-picker-label[data-value="merriweather"]::before,
.ql-picker.ql-font .ql-picker-item[data-value="merriweather"]::before {
  content: "Merriweather" !important;
  font-family: var(--font-merriweather);
}
```

Note : I'm sure there is a much more clean way to handles this, but for now it's the best I can suggest

I'll edit the response when I'll find a cleaner implementation

Best regards
