### ISSUE TITLE
image upload by base64??

### ISSUE THREAD

**Issue by jthink0228** [zenoamaro/react-quill#274]
this is a awesome plugin...
but i get some problem

i try to upload images with quill
well done, it`s work~

but i get 200,000 length code by base64.....

i try to upload 10 pictures..
2000,000 length...
it's too much long  for my database
Is it possible to switch to pictures other than base64 instead..

thx a lot

**Comment by alexkrolick** [comment]
Yep, there are some Quill plugins that can help with that: https://github.com/quilljs/awesome-quill#modules

**Comment by newyoung21** [comment]
Which plug-in should I use?
