### ISSUE TITLE
Question mark and comma key inputs don't work in the editor

### ISSUE THREAD

**Issue by amulgarg** [zenoamaro/react-quill#283]
I'm using React-quill v1.1.0. All works smooth but there's one peculiar but serious issue I'm facing.
The comma and question mark inputs don't work (all other key inputs work). I have to type them somewhere else and copy to the quill editor instance! 
What might I be doing wrong?

**Comment by alexkrolick** [comment]
Not sure, would need to see an example to debug. I don't think this is an issue with the editor as it works in the examples:

- Codepen https://codepen.io/pen?template=xgyOXQ
- Custom toolbar Codepen https://codepen.io/pen?template=gmroPj
