### ISSUE TITLE
 Unhandled Rejection (TypeError): Cannot read property 'imports' of undefined  IN REACT

### ISSUE THREAD

**Issue by dharmesh03** [zenoamaro/react-quill#285]
import ReactQuill,{Quill} from 'react-quill'; import ImageResize from 'quill-image-resize-module'; Quill.register('modules/ImageResize', ImageResize); 

 × Unhandled Rejection (TypeError): Cannot read property 'imports' of undefined ▼ 13 stack frames were expanded. (anonymous function) node_modules/quill-image-resize-module/image-resize.min.js:1 e node_modules/quill-image-resize-module/image-resize.min.js:1 (anonymous function) node_modules/quill-image-resize-module/image-resize.min.js:1 e node_modules/quill-image-resize-module/image-resize.min.js:1 t.exports node_modules/quill-image-resize-module/image-resize.min.js:1 (anonymous function) node_modules/quill-image-resize-module/image-resize.min.js:1 webpackJsonp../node_modules/quill-image-resize-module/image-resize.min.js.n node_modules/quill-image-resize-module/image-resize.min.js:1 Object../node_modules/quill-image-resize-module/image-resize.min.js node_modules/quill-image-resize-module/image-resize.min.js:1 webpack_require /home/dev1/ae-front-end/webpack/bootstrap 020bfc4c2b6760e16678:710 fn /home/dev1/ae-front-end/webpack/bootstrap 020bfc4c2b6760e16678:115 Object../src/routes/admin/design/Design.js http://localhost:3000/assets/4.chunk.js:18826:85 webpack_require /home/dev1/ae-front-end/webpack/bootstrap 020bfc4c2b6760e16678:710 fn /home/dev1/ae-front-end/webpack/bootstrap 020bfc4c2b6760e16678:115 ▲ 13 stack frames were expanded. This screen is visible only in development. It will not appear if the app crashes in production. Open your browser’s developer console to further inspect this error.

**Comment by alexkrolick** [comment]
See https://github.com/zenoamaro/react-quill/issues/224
