### ISSUE TITLE
Create a custome color picker with quill

### ISSUE THREAD

**Issue by Swati020494** [zenoamaro/react-quill#289]
How can a text field  be inserted in the colour-picker(text and background used as color:[] and background:[] formats) which takes hex values? The text field is needed to customise and widen the colour options.
![image](https://user-images.githubusercontent.com/14866260/32723237-c46c030a-c892-11e7-8ecc-1a2f4e8af2fd.png)

**Comment by alexkrolick** [comment]
You can supply a custom toolbar with JSX: http://sinonjs.org/releases/v4.1.2/stubs/

**Comment by volkandkaya** [comment]
@Swati020494 was you able to make a custom color picker?

**Comment by kwiser** [comment]
See this answer, https://stackoverflow.com/questions/42068335/quill-js-color-textbox/60526271#60526271

**Comment by Jomimoses** [comment]
> How can a text field be inserted in the colour-picker(text and background used as color:[] and background:[] formats) which takes hex values? The text field is needed to customise and widen the colour options.
> ![image](https://user-images.githubusercontent.com/14866260/32723237-c46c030a-c892-11e7-8ecc-1a2f4e8af2fd.png)

@swamu have you achieved this feature..?

**Comment by kumarajay0412** [comment]
I have a added a example please see this sandbox here 
https://codesandbox.io/p/devbox/react-quill-example-5j6w2y?file=%2Fsrc%2FApp.tsx%3A13%2C22
