### ISSUE TITLE
Surpotting for intarnalization?

### ISSUE THREAD

**Issue by countingSta** [zenoamaro/react-quill#290]
Thanks for filing an issue! 

If at all possible, please provide a Codepen to demonstrate the problem you're having with React Quill. Here's a [template] to get you started.

[template]: 
https://codepen.io/pen?template=xgyOXQ

### FAQ

**How do I access the wrapped Quill instance?**
See the [instance methods] and [API] documentation.

[instance methods]:
https://github.com/zenoamaro/react-quill#methods

[API]:
https://github.com/zenoamaro/react-quill#api-reference

**Is there a bug in Quill?**
Please refer to the [Quill issues page].

[Quill issues page]: 
https://github.com/quilljs/quill/issues

#### React-Quill version 
- [x] master
- [ ] 0.4.1
- [ ] 1.0.0-beta-1
- [ ] 1.0.0-beta-2
- [ ] 1.0.0-beta-3
- [ ] 1.0.0-beta-4
- [ ] 1.0.0-beta-5
- [ ] 1.0.0-rc-1
- [ ] 1.0.0-rc-2
- [ ] 1.0.0-rc-3
- [ ] 1.0.0
- [ ] 1.1.0
- [ ] Other (fork)

**Comment by countingSta** [comment]
Can it support for internalization?

**Comment by alexkrolick** [comment]
Most of the configuration for the themes lives in the theme files from Quill (https://quilljs.com). You can customize these files to change the language.
