### ISSUE TITLE
image size too large

### ISSUE THREAD

**Issue by LitileXueZha** [zenoamaro/react-quill#291]
When i upload a picture which likes 1M，it stops working....

**Comment by alexkrolick** [comment]
Quill's default behavior is to inline images as base64 strings. If you search in the Quill repository and on NPM there are a few modules that let you use external handlers as well as resize images.

- https ://quilljs.com/docs/modules/
- https://github.com/zenoamaro/react-quill#custom-formats
- https://github.com/quilljs/quill
- Codepen https://codepen.io/pen?template=xgyOXQ
- Custom toolbar Codepen https://codepen.io/pen?template=gmroPj
