### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by andylaci** [zenoamaro/react-quill#292]
![image](https://user-images.githubusercontent.com/7139923/33091010-2bc42424-cef6-11e7-82fb-7cbf597090f4.png)

**Comment by alexkrolick** [comment]
Are you server-side rendering? https://github.com/zenoamaro/react-quill/issues/185

**Comment by alexkrolick** [comment]
OK, #185 should contain everything you need 😄

**Comment by AryanJ-NYC** [comment]
If you're stumbling upon this, go straight to https://github.com/zenoamaro/react-quill/issues/122 instead of #185. #185 just forwards you to https://github.com/zenoamaro/react-quill/issues/122.

**Comment by sshekhar336** [comment]
Hi,
Add { ssr: false } to stop server side rendering in dynamic import.

**Comment by ashisdeveloper** [comment]
const ReactQuill = typeof window === 'object' ? require('react-quill') : () => false;

// Use ReactQuill as desired

<ReactQuill
  value={value}
  onChange={handleChange}
/>

**Comment by rhinehardtc** [comment]
Don't forget to import dynamic from 'next/dynamic' like I did for MuhammadMinhaj's answer to work!

**Comment by Coder-Devesh-Agarwal** [comment]
React Quill Rendering Twice ??

**Comment by cornnnnnnnnnnnnnnnn** [comment]
![1665988586250](https://user-images.githubusercontent.com/111114287/196184948-8ddb8228-54cb-48c9-91b4-c36d936b6f33.jpg)
how to fix it？

**Comment by Saravanakumarkandasamy** [comment]
const ReactQuill = dynamic(import('react-quill'), { ssr: false})  
Try This.

**Comment by ninsau** [comment]
> const ReactQuill = dynamic(import('react-quill'), { ssr: false})

doesn't work

**Comment by MiguelMarroquin** [comment]
I made a component for the quill editor and render it dynamic , and client side.

```
"use client";
import dynamic from "next/dynamic";
const ReactQuill = dynamic(() => import("react-quill"), { ssr: false });

import "react-quill/dist/quill.bubble.css";

function TextEditor({ value, name, handleQuillChange, label }) {
	return (
		<div className='flex flex-col mt-3'>
			<p className='mt-4 text-sm font-medium'>{label}</p>
			<ReactQuill
				className=' mt-1 px-2 rounded-xl border hover:scale-105 duration-300'
				value={value}
				onChange={handleQuillChange(name)}
				theme='bubble'
			/>
		</div>
	);
}

export default TextEditor;
```
Then I import it on a form that is rendered also  "use client"

but I have this error: 

```
ReferenceError: document is not defined
    at Object.eval (webpack-internal:///(sc_client)/./node_modules/quill/dist/quill.js:7656:12)
    at __nested_webpack_require_697__ (webpack-internal:///(sc_client)/./node_modules/quill/dist/quill.js:31:30)
    at Object.eval (webpack-internal:///(sc_client)/./node_modules/quill/dist/quill.js:1025:1)
    at __nested_webpack_require_697__ (webpack-internal:///(sc_client)/./node_modules/quill/dist/quill.js:31:30)
    at Object.eval (webpack-internal:///(sc_client)/./node_modules/quill/dist/quill.js:5650:14)
    at __nested_webpack_require_697__ (webpack-internal:///(sc_client)/./node_modules/quill/dist/quill.js:31:30)
    at Object.eval (webpack-internal:///(sc_client)/./node_modules/quill/dist/quill.js:10040:13)
    at __nested_webpack_require_697__ (webpack-internal:///(sc_client)/./node_modules/quill/dist/quill.js:319:20)
    at eval (webpack-internal:///(sc_client)/./node_modules/quill/dist/quill.js:11:3)
    at (sc_client)/./node_modules/quill/dist/quill.js (D:\Coding\NEXTJS\jjudit_nextjs13\.next\server\_sc_client_node_modules_react-quill_lib_index_js.js:909:1)
    at __webpack_require__ (D:\Coding\NEXTJS\jjudit_nextjs13\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(sc_client)/./node_modules/react-quill/lib/index.js:43:31)
    at (sc_client)/./node_modules/react-quill/lib/index.js (D:\Coding\NEXTJS\jjudit_nextjs13\.next\server\_sc_client_node_modules_react-quill_lib_index_js.js:920:1)
    at __webpack_require__ (D:\Coding\NEXTJS\jjudit_nextjs13\.next\server\webpack-runtime.js:33:43)
    at __webpack_require__.t (D:\Coding\NEXTJS\jjudit_nextjs13\.next\server\webpack-runtime.js:73:38)           at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by jjmss** [comment]
> const ReactQuill = dynamic(import('react-quill'), { ssr: false}) Try This.

Removing the arrow function solved the issue for me.

**Comment by jjmss** [comment]
> const ReactQuill = dynamic(import('react-quill'), { ssr: false}) Try This.

Wrapping the import within useMemo solved the issue for me (source: https://stackoverflow.com/a/74096771/12103912)

**Comment by LeeManh** [comment]
> const ReactQuill = typeof window === 'object' ? require('react-quill') : () => false;

Tks. I work for me

**Comment by 0xMazout** [comment]
> I made a component for the quill editor and render it dynamic , and client side.
> 
> ```
> "use client";
> import dynamic from "next/dynamic";
> const ReactQuill = dynamic(() => import("react-quill"), { ssr: false });
> 
> import "react-quill/dist/quill.bubble.css";
> 
> function TextEditor({ value, name, handleQuillChange, label }) {
> 	return (
> 		<div className='flex flex-col mt-3'>
> 			<p className='mt-4 text-sm font-medium'>{label}</p>
> 			<ReactQuill
> 				className=' mt-1 px-2 rounded-xl border hover:scale-105 duration-300'
> 				value={value}
> 				onChange={handleQuillChange(name)}
> 				theme='bubble'
> 			/>
> 		</div>
> 	);
> }
> 
> export default TextEditor;
> ```
> 
> Then I import it on a form that is rendered also "use client"
> 
> but I have this error:
> 
> ```
> ReferenceError: document is not defined
>     at Object.eval (webpack-internal:///(sc_client)/./node_modules/quill/dist/quill.js:7656:12)
>     at __nested_webpack_require_697__ (webpack-internal:///(sc_client)/./node_modules/quill/dist/quill.js:31:30)
>     at Object.eval (webpack-internal:///(sc_client)/./node_modules/quill/dist/quill.js:1025:1)
>     at __nested_webpack_require_697__ (webpack-internal:///(sc_client)/./node_modules/quill/dist/quill.js:31:30)
>     at Object.eval (webpack-internal:///(sc_client)/./node_modules/quill/dist/quill.js:5650:14)
>     at __nested_webpack_require_697__ (webpack-internal:///(sc_client)/./node_modules/quill/dist/quill.js:31:30)
>     at Object.eval (webpack-internal:///(sc_client)/./node_modules/quill/dist/quill.js:10040:13)
>     at __nested_webpack_require_697__ (webpack-internal:///(sc_client)/./node_modules/quill/dist/quill.js:319:20)
>     at eval (webpack-internal:///(sc_client)/./node_modules/quill/dist/quill.js:11:3)
>     at (sc_client)/./node_modules/quill/dist/quill.js (D:\Coding\NEXTJS\jjudit_nextjs13\.next\server\_sc_client_node_modules_react-quill_lib_index_js.js:909:1)
>     at __webpack_require__ (D:\Coding\NEXTJS\jjudit_nextjs13\.next\server\webpack-runtime.js:33:43)
>     at eval (webpack-internal:///(sc_client)/./node_modules/react-quill/lib/index.js:43:31)
>     at (sc_client)/./node_modules/react-quill/lib/index.js (D:\Coding\NEXTJS\jjudit_nextjs13\.next\server\_sc_client_node_modules_react-quill_lib_index_js.js:920:1)
>     at __webpack_require__ (D:\Coding\NEXTJS\jjudit_nextjs13\.next\server\webpack-runtime.js:33:43)
>     at __webpack_require__.t (D:\Coding\NEXTJS\jjudit_nextjs13\.next\server\webpack-runtime.js:73:38)           at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> ```

I Have the same problem if someone can help

**Comment by MammadProMax** [comment]
make sure include "use client" at the top of the file

**Comment by tajkir-alam** [comment]
`const ReactQuill = useMemo(() => dynamic(() => import('react-quill'), { ssr: false }),[]);`

this helped me. don't forget to use 'useMemo' it will store the data otherwise it will render. and obviously, write the code inside of your react function component.

**Comment by yogithesymbian** [comment]
> const ReactQuill = dynamic(() => import('react-quill'), { ssr: false });

greats work like a charm

**Comment by ABEL-Dion** [comment]
> const ReactQuill = typeof window === 'object' ? require('react-quill') : () => false;
> 
> // Use ReactQuill as desired

**Comment by ABEL-Dion** [comment]
It worked perfectly Thank you

**Comment by divyakerekar11** [comment]
> > const ReactQuill = typeof window === 'object' ? require('react-quill') : () => false;
> > // Use ReactQuill as desired

im using this but showing error?
