### ISSUE TITLE
How to upload image ?

### ISSUE THREAD

**Issue by countingSta** [zenoamaro/react-quill#293]
Thanks for filing an issue! 

If at all possible, please provide a Codepen to demonstrate the problem you're having with React Quill. Here's a [template] to get you started.

[template]: 
https://codepen.io/pen?template=xgyOXQ

### FAQ

**How do I access the wrapped Quill instance?**
See the [instance methods] and [API] documentation.

[instance methods]:
https://github.com/zenoamaro/react-quill#methods

[API]:
https://github.com/zenoamaro/react-quill#api-reference

**Is there a bug in Quill?**
Please refer to the [Quill issues page].

[Quill issues page]: 
https://github.com/quilljs/quill/issues

#### React-Quill version 
- [ ] master
- [ ] 0.4.1
- [ ] 1.0.0-beta-1
- [ ] 1.0.0-beta-2
- [ ] 1.0.0-beta-3
- [ ] 1.0.0-beta-4
- [ ] 1.0.0-beta-5
- [ ] 1.0.0-rc-1
- [ ] 1.0.0-rc-2
- [ ] 1.0.0-rc-3
- [ ] 1.0.0
- [ ] 1.1.0
- [ ] Other (fork)

**Comment by alexkrolick** [comment]
Add `image` to the `format` array you pass in as props, and images will be able to be uploaded and inlined as base64 string data.
