### ISSUE TITLE
Insert Text with no undo stacks

### ISSUE THREAD

**Issue by yangyu0311ugroop** [zenoamaro/react-quill#297]
Hi,

I copied the code from the document. Basically, I am trying to add a custom tool bar button and insert text. Below is my insertText function 

```
    const range = this.quillRef.getSelection();
    const position = range ? range.index : 0;
    this.quillRef.insertText(position, '1');
```

My Editor Module configuration is like this 
```
Editor.modules = (props) => ({
  toolbar: {
    synatax: true,
    container: `#toolbar`,
    handlers: {
      redo,
      undo,
    },
  },
  history: {
    delay: 1000,
    maxStack: 500,
    userOnly: true,
  },
});
```

My CustomTool Bar html is 
```
      <div id='toolbar'>
  history = () => <span
    className="ql-formats"
  >
    <button className="ql-undo">
      <Icon icon={'lnr-undo2'} />
    </button>
    <button className="ql-redo">
      <Icon icon={'lnr-redo2'} />
    </button>
  </span>;
</div>
```

The data insertion is all correct, however, I could't get the undo stacks in my history. Am I missing anything here?

Thank you

**Comment by alexkrolick** [comment]
The last argument to the Quill APIs is `source`. Pass `user` to make the event register as a user action, or change `userOnly: true` to false.

**Comment by yangyu0311ugroop** [comment]
hi Alex, thanks for the quick reply. I tried to pass user like this `this.quillRef.insertText(position, value, 'user');` but it still doesn't work, no undo stacks. However, as you said, if I change `userOnly: false`, it works, but that means `undo` button can change the original content.

**Comment by yangyu0311ugroop** [comment]
Just an update, I have to use like setTimeout to make it work correctly. 
```
    setTimeout(() => {
      this.quillRef.insertText(position, value, 'user');
    }, 100);
```
