### ISSUE TITLE
Access editor and getContent with dropdown select

### ISSUE THREAD

**Issue by Kielan** [zenoamaro/react-quill#299]
I have a quill editor and a select input in the form that I was to use to set templates to prefill quill content with the template. I seem to be unable to access by ref to the quill editor in the parent component the same 'editor' object that is used in the onChange method for which I use editor.getContents(); 

There are a lot of 'editor' names in the quill project but none of them seem to be of the same form as the onChange editor parameter that in passed in the onchange event.

I found the documentation quite circular regarding controlled and uncontrolled form, and no clear deviation between value and defaultValue.

**Comment by alexkrolick** [comment]
You can accomplish this by getting a ref to the ReactQuill node first, then accessing its `.getEditor` method: 
- https://github.com/zenoamaro/react-quill#methods
- https://codepen.io/alexkrolick/pen/YNmGar?editors=0011
