### ISSUE TITLE
Removing Toolbar

### ISSUE THREAD

**Issue by brucedlukens** [zenoamaro/react-quill#30]
Is there currently a way to remove the toolbar through props? I'd like to have the toolbar available in certain instances but not others.

**Comment by brucedlukens** [comment]
I found a way to do it, I just called the toolbar class (ql-toolbar and set it to none when it's inside of certain divs.

**Comment by zenoamaro** [comment]
I should provide you with a better, official way to disable the toolbar. Stay tuned.

**Comment by RayOconnor** [comment]
@brucedlukens I disabled the toolbar by using css to set display to none for react-quill edit boxes with a specific file name 
```
  div.blurred-term-row div.ql-toolbar
    display: none
```
I made a variable in the state called `focused`
when rendering ReactQuill I set the className dependent on the state
```
<ReactQuill
     className={this.state.focused ? "focused-editor" : "blurred-editor"}
     value={"yada yada yada"}
     theme="snow"/>
```
when the user focuses on the container component of react quill, I `this.setState({focused: true})`
when the user blurs on the container component of react quill, I `this.setState({focused: true})`

**Comment by zenoamaro** [comment]
You can now pass `false` to the `toolbar` prop to disable it completely.

**Comment by thienanle** [comment]
Bug: when `toolbar` prop changes, the editor loses focus.
For example, if I want to hide the toolbar until I click on the editor, I have to click on the editor, then click again to start editing.

**Comment by diepvv** [comment]
you can fix:
 render() {
    return (
      <div>
            <ReactQuill
                onChange={this.handleChange}
                value={this.props.editorHtml}
                modules={Editor.modules}
             />
       </div>
        }
    );
  }

Editor.modules = {
  toolbar: false,
};

**Comment by jellanarta** [comment]
import React, { useState } from 'react'
import ReactQuill from 'react-quill'; // ES6
import 'react-quill/dist/quill.snow.css';
export default function Editorhtml() {
    const [value, setValue] = useState('')
    const changevalue = e => {
        setValue(e)
    }
    const modules = {
        toolbar: false
    }
    console.log(value)
    return (
        <ReactQuill value={value} modules={modules} placeholder={'Deskripsi produk'}
            onChange={changevalue} />
    )
}

**Comment by chandra1899** [comment]
how can i enable and disable toolbar dynamically ?
