### ISSUE TITLE
How to handle images from react-quill(redux) to server ? (node express)

### ISSUE THREAD

**Issue by mirik999** [zenoamaro/react-quill#300]
Dear People , pls explain how can i handle images from React.Quill textarea with rest. I am a beginner so if someone can explain and write any example i will be very grateful

**Comment by alexkrolick** [comment]
In general, React-Quill is not responsible for that sort of functionality; we recommend using the underlying Quill plugin system instead.

There are a few plugins for Quill to handle images: https://www.npmjs.com/search?q=quill-image&page=1&ranking=optimal

Also check the Quill issues board: https://github.com/quilljs/quill

For help integrating Quill plugins with React-Quill, see the README:

- https://github.com/zenoamaro/react-quill#custom-formats
- https://github.com/zenoamaro/react-quill#api

**Comment by jayanthrbharadwaj** [comment]
handling images can be done with **quill-image-upload** plugin. 

Refer gist with imgur image upload
https://gist.github.com/jayanthrbharadwaj/0f90310b3a99499149a74cfe32355e27
