### ISSUE TITLE
Do you support hot keys from key board?

### ISSUE THREAD

**Issue by digish777** [zenoamaro/react-quill#301]
HI,

 I need the editor to save the content on ctrl+s from key board.  Does Quill support that?

**Comment by juanparadox** [comment]
Don't believe it does, but it would be interesting to have some sort of keystrokes prop where you could define this sort of action by mapping it to desired key. Seems like a whole bunch of new functionality would be added that may be out of the scope of the original intention of react-quill.

**Comment by alexkrolick** [comment]
See the Quill docs for the keyboard module - https://quilljs.com/docs/modules/keyboard/

For help integrating Quill configuration with React-Quill, see the README: https://github.com/zenoamaro/react-quill#custom-formats
