### ISSUE TITLE
Request: Have the onChange handler return a key attribute if one is set

### ISSUE THREAD

**Issue by aMadReason** [zenoamaro/react-quill#303]
Please can this addition be considered for while multiple instances of react-quill run concurrently in a child component and state change needs to be passed to the parent.

For instance an editor page where fields are appended dynamically.

The following assumes state is handled by the component itself rather than it's parent but you get the idea, also, if there is a better way to do this please advise i'm still relatively new to React.

```javascript
    this.state = { 
      editorHtml: '', 
      theme: 'snow',
      instances: [ // multiple instances
        {name: 'instance 1', content: ''},
        {name: 'instance 2', content: ''}
      ]
    }

  render () {
    return (
      <div>

        {this.state.instances.map((instance, i) => {
// render a react-quill for each instance in state
          return (
          <ReactQuill key={i}
            theme={this.state.theme}
            onChange={this.handleChange}
            value={this.state.editorHtml}
            modules={Editor.modules}
            formats={Editor.formats}
            bounds={'.app'}
            placeholder={this.props.placeholder}
           />
          );
        })}
       
       </div>
     )
  }

  // I'm unable to retrieve a key to update
  // the corresponding state instance
  handleChange (html, key) {
    const instances = this.state.instances;
    instances[key].content = html;
    
    this.setState({
      instances: instances
    });
    
  }
```

https://codepen.io/ouamandar/pen/OOGXzG

**Comment by alexkrolick** [comment]
The `key` prop is used for React's internal bookkeeping, but you can accomplish what you need by passing a bound function to each of your editors: https://reactjs.org/docs/faq-functions.html#how-do-i-pass-a-parameter-to-an-event-handler-or-callback

```diff
-  onChange={this.handleChange}
+  onChange={html => this.handleChange(i, html)}

- handleChange (html, key) {
+ handleChange (key, html) {
```

If your editors are reorderable, you may also have issues with using the array index as a key: https://reactjs.org/docs/lists-and-keys.html#keys
