### ISSUE TITLE
How to pass to parent component as normal change event?

### ISSUE THREAD

**Issue by Dashue** [zenoamaro/react-quill#305]
Following a pattern where the container components keeps all the state/logic etc of a form.

The parent uses the following method which it passed down to the form and that the form in turn binds its fields onChange to.
    setState(event) {
        const { name, value } = event.target;

        const entity= { ...this.state.entity};
        entity[name] = value;
        return this.setState({ entity: entity});
    }

Seeing as the onchange or the quill doesn't follow the pattern of a regular change event, i.e provide a target, I've yet to find a way to make it fit into onchange handler.

I've tried various combinations of binding change handlers, I've tried using refs and manually invoking change handlers on hidden inputs, and also to manually constructing and dispatching new events.

I can't see a way without forcing logic into the form which in our case is supposed to be a presentation component, and I'm scratching my head as I can't see this as an abnormal use-case with wanting to pass the event up to the parent container component.

I did see the older issue where someone had multiple editors and could resort to using a key={id} approach, but I don't think that would work in my case.

Any input is most appreciated!
Thanks!

#### React-Quill version 
- [ ] master
- [ ] 0.4.1
- [ ] 1.0.0-beta-1
- [ ] 1.0.0-beta-2
- [ ] 1.0.0-beta-3
- [ ] 1.0.0-beta-4
- [ ] 1.0.0-beta-5
- [ ] 1.0.0-rc-1
- [ ] 1.0.0-rc-2
- [ ] 1.0.0-rc-3
- [ ] 1.0.0
- [ X] 1.1.0
- [ ] Other (fork)

**Comment by alexkrolick** [comment]
```jsx
<Editor onChange={html => this.onChange({target: {value: html}}) />
```

This should serve to spoof the event

**Comment by Dashue** [comment]
Thanks for the help!

Do you know of a way to also spoof the name? If there's a
name="quillContent" attribute, is it possible to get at this in order to
make the object be {target:{name: "quillContent", value: html}}

**Comment by alexkrolick** [comment]
Can you synchronize the values for the name and the handler using a variable?

```jsx
const editorName = 'quillContent'
/* ...  */
<Editor onChange={html => this.onChange({target: {value: html, name: editorName}}) />
```

**Comment by Dashue** [comment]
Yeah I that's the best I can come up with. Thanks for your help and
for the library!
