### ISSUE TITLE
image handler issuse

### ISSUE THREAD

**Issue by layne0625** [zenoamaro/react-quill#307]
![1](https://user-images.githubusercontent.com/24985105/34148247-8ca3a4f4-e4db-11e7-9718-f19fe2111799.png)
![2](https://user-images.githubusercontent.com/24985105/34148260-95c9d328-e4db-11e7-8132-f96ec16e78f5.png)

When I use image handler , find this error

**Comment by alechstong** [comment]
you need to use this.quill.insertEmbed instead of format, like:
```js
const range = this.quill.getSelection();
this.quill.insert(range.index, 'image', '<your image src>');
```

**Comment by layne0625** [comment]
OK, thank you very much

**Comment by layne0625** [comment]
I want add some attributes to this img node that quill created or add another node element to this index . How I can do?

**Comment by alechstong** [comment]
In case of adding a custom node, I think you have to do it thru a custom blot, and then hook it up to a button in your toolbar.
If you want to change attributes of a node, you can either do it from the toolbar (custom blot) or using a custom module to get a reference to the node in the document, and manipulate it using the DOM api.
[more info on custom module.](https://quilljs.com/guides/building-a-custom-module/)
[more info on blot](https://quilljs.com/guides/cloning-medium-with-parchment/#cloning-medium-with-parchment)
always a good idea to check out [how the built-in formats are implemented](https://github.com/quilljs/quill/tree/develop/formats).

But remember to look for solutions in the community before building  your own from scratch. If it is img resizing feature you are looking for, [here](https://github.com/kensnyder/quill-image-resize-module) is a module that I'm currently using (quill-image-resize-module).

good luck.

**Comment by layne0625** [comment]
ok, thanks
