### ISSUE TITLE
Unless I use my own stylesheet, styles won't work

### ISSUE THREAD

**Issue by carlosepp** [zenoamaro/react-quill#31]
The problem: 
If I do not manually include the stylesheet in my application.scss, the editor shows as follows:
<img width="1201" alt="screen shot 2015-09-17 at 11 41 41 am" src="https://cloud.githubusercontent.com/assets/497142/9939680/27ceb08e-5d31-11e5-9d81-db34e90425fd.png">

What's strange is that after including it in my application.scss
<img width="472" alt="screen shot 2015-09-17 at 11 43 09 am" src="https://cloud.githubusercontent.com/assets/497142/9939702/49f8638a-5d31-11e5-9987-f5cb9f2d3307.png">
Styles do load, but collide:
<img width="1174" alt="screen shot 2015-09-17 at 11 47 56 am" src="https://cloud.githubusercontent.com/assets/497142/9939840/053cb326-5d32-11e5-9fd4-2080439ea403.png">

I had in mind a couple of ways of fixing this.

By including only the dist/quill.js like so:
```import Editor from "react-quill/node_modules/quill/dist/quill.js";```

but throws the following error:
<img width="569" alt="screen shot 2015-09-17 at 11 50 45 am" src="https://cloud.githubusercontent.com/assets/497142/9939937/6e0e3190-5d32-11e5-87d0-a658c5c0e0be.png">

The other is to get rid of the styles in dist so I can have more control over them, but that would require to fork and use that which does not seem like the best idea

Any suggestions or advice on this issue @zenoamaro , I really appreciate your help :pray:

**Comment by liato** [comment]
If you include your own stylesheet you can prevent quill from injecting styles into `<head>` by setting the `styles` prop to `false`:
```
<ReactQuill theme="snow"
            styles={ false } />
```

**Comment by carlosepp** [comment]
ohhhh thanks for this :)

**Comment by zenoamaro** [comment]
@carlosepp, yes, @liato is correct, Quill will add some styles for cursors, plugins and such if a `theme` has been specified.

Closing this as there is official support for `styles={false}` since #34.
