### ISSUE TITLE
Custom fonts

### ISSUE THREAD

**Issue by Astrak** [zenoamaro/react-quill#310]
Hello and many thanks for this react adaptation of Quill and your availability on github through the PRs and issues I've seen so far.

I would like to provide more font choices but in 3 days I haven't been able to understand what is the way for that. Some other issues are related (https://github.com/zenoamaro/react-quill/issues/36, https://github.com/zenoamaro/react-quill/issues/273) and you have created a special example for this : https://codepen.io/alexkrolick/pen/NapmrE?editors=0110

However the dropdown list doesn't have the correct fonts in this example.

I would like to import a list of fonts from google-fonts, how would I go for this ?

Thank you very much.

**Comment by alexkrolick** [comment]
The Quill Playground example uses Google Fonts. Essentially you just need to use the full name of the font without spaces, as you would reference it using CSS: https://quilljs.com/playground/#custom-fonts
