### ISSUE TITLE
Dependency on @types/react@* breaks if using React v15

### ISSUE THREAD

**Issue by skjorn** [zenoamaro/react-quill#316]
Hi, we're stuck with React v15 on our project at the moment and your TypeScript dependencies in package.json break it for us pretty badly. Particularly these lines:

```
   "dependencies": {
+    "@types/quill": "*",
+    "@types/react": "*",
```

You see ```"@types/react": "*"``` now imports typings for React v16 and globally we use typings for v15. As a result the project doesn't compile.

Please, consider using "devDependencies" for @types instead, or at least specifying a version for ```@types/react```.

**Comment by alexkrolick** [comment]
What version pattern would work for you?

**Comment by skjorn** [comment]
```"<16.0.0"``` since React v16 broke the backwards compatibility.

**Comment by alexkrolick** [comment]
Well, it does need to keep working with 16 😬...

Do you also have React types installed at a specific version in the parent package? The module system should be able to resolve `*` to any version.

**Comment by skjorn** [comment]
I do have a specific version set for React types we use, but it does not resolve properly with Yarn if I use ```yarn install``` without yarn.lock already in place. Types for v16 end up downloaded as dependencies of your package and they conflict with the earlier version set in the parent package. Thus it cannot be used "out of the box".

There's a workaround I've found -- specifying the "resolution" block in package.json, but without it (by default) your package will break it for anyone who uses TypeScript and an older version of React.

So I'm curious -- why do you even specify ```@types``` as a dependency for consumers anyway?

Are you sure all versions of your package work with all versions of React? That sounds very improbable. I'm fine with locking in to an earlier version of your package that uses an earlier version of React.

**Comment by alexkrolick** [comment]
It works with the version strings for the React peer dep in package.json. The types are a dep so that the typings file can reference ReactElement and thing like that. It is possible that the types could be moved to a peer dep, but I am not sure how Typescript resolves things like that as compared to Webpack.

**Comment by psaia** [comment]
>The types are a dep so that the typings file can reference ReactElement. It is possible that the types could be moved to a peer dep, but I am not sure how Typescript resolves peer deps.

I'm not seeing where the types are directly required? Ideally, this would be a dev-dep. At the very least a peer-dep.

**Comment by zenoamaro** [comment]
@alexkrolick technically we export React types, so we should at least peer depend on it. But most libraries I see put React types in dev dependencies, and this seems to work fine.

I'll hotfix v1 to alleviate the pain of anybody still using R15 (my prayers are with you my dudes)

**Comment by zenoamaro** [comment]
@skjorn hopefully you already enjoy react 16 today. Otherwise, v1.3.5 should finally fix this issue. Cheers
