### ISSUE TITLE
How can I get the Quill object?

### ISSUE THREAD

**Issue by RayOconnor** [zenoamaro/react-quill#32]
The Quill API is very rich and provides and provides a variety of useful functions.  How can I get my hands on the `Quill` object? http://quilljs.com/docs/api/#quillprototypegettext

I have the html value that Quill outputs ex: 
```
"<div><span style="color: rgb(230, 0, 0);">This is red; </span> This is not.</div>"
```
I need to extract the text value which can be done through `Quill.prototype.getText()` to get... 
`"This is red; this is not." `

**Comment by RayOconnor** [comment]
I created a pull request to get the Text that I need https://github.com/zenoamaro/react-quill/pull/33

**Comment by zenoamaro** [comment]
I know it's ugly, but as a temporary workaround (until there is an official way to expose the Quill instance) you should be able to access the `editor` instance from the component's `state` (digging a bit) if you have a `ref` to it.

Could you try and report?

**Comment by RayOconnor** [comment]
@zenoamaro continue conversation at https://github.com/zenoamaro/react-quill/pull/33

**Comment by zenoamaro** [comment]
While we undertake the porting effort to React 0.14 and so take the chance to break the event callbacks, I wanted to lessen this issue by exposing a public `getEditor` method on the component, to which you would have access by taking a `ref` to it.
