### ISSUE TITLE
get paragraphs to render with blank lines

### ISSUE THREAD

**Issue by ChuckIrvine** [zenoamaro/react-quill#320]
I'm used to seeing paragraphs render in a browser with blank lines before and after them as shown here:

![screen shot 2018-01-24 at 7 29 00 pm](https://user-images.githubusercontent.com/657002/35366047-f623a9ce-013c-11e8-923d-46be88f4bf5a.png)

However, if I type two paragraphs, the resulting html shows two paragraphs, but in the editor the paragraphs aren't separated by a blank line, as shown here:

![screen shot 2018-01-24 at 7 42 31 pm](https://user-images.githubusercontent.com/657002/35366474-6071383a-013f-11e8-8296-fc7382f41c16.png)

How can I get my paragraphs to render in the editor surrounded by blank lines?

**Comment by alexkrolick** [comment]
The browser stylesheet normally sets a margin or line-height on `p` tags; Quill sets the space between paragraphs to 0 in CSS to be more wysiwyg. You can target `.ql-editor p` in CSS to change it.

**Comment by ChuckIrvine** [comment]
Hey Alex,

Thanks for helping this neophyte. My web app (www.evrsity.com <http://www.evrsity.com/>) is all switched over from TinyMCE to react-quill. Quill and react-quill is really great.

Chuck
