### ISSUE TITLE
How to override default ReactQuill styling?

### ISSUE THREAD

**Issue by kbgar24** [zenoamaro/react-quill#322]
const styles = {
       fontWeight: 'bold',
       fontSize: '50px'
     }

    export default class NoteTitle extends React.Component {
     
     ....

      render = () => (
        <div style={{ fontSize: '50px !important' }}>
          <ReactQuill
            className='note'
            theme=""
            value={ this.state.value }
            onChange={ this.handleEditorChange }
            placeholder="Untitled"
            styles={styles}
            formats={[{"header":1}]}
          />
        </div>
      );
    }

----
## Issue 

**How to override default ReactQuill styling?**

How do you render a ReactQuill element with a custom style that overrides the default style? 

I would like this element to to have a default font-size of 50px && default to bold. But I've been unable to override the default font-size of 13px. Above is a snippet of all the methods I've tried to accomplish this (in-line styles, external styles, formats). 

Thanks in advance!

**Comment by alexkrolick** [comment]
It's actually Quill's CSS you need to override - check the documentation on themes. It's probably something like:

```css
.ql-editor p {
  font-size: 50px;
  font-weight: bold;
}
```

**Comment by kbgar24** [comment]
Thanks for the prompt @alexkrolick! Unfortunately I have multiple editors in the same page, and attacking the problem that way ends up impacting all the editors. Is there no way to do in-line styles?

**Comment by alexkrolick** [comment]
The inline styles would be on the wrapper; you need to target what Quill targets with its css. You can add an outer class to each editor to scope the rules.

**Comment by kbgar24** [comment]
I see. Thanks again for the help!
