### ISSUE TITLE
Mentions implementation

### ISSUE THREAD

**Issue by pablonm3** [zenoamaro/react-quill#324]
I'm trying to implement mentions within this editor, but I don't know where to start, is there any module to integrate with react-quill in order to get mentions to work?.
.
I've tried with React-mentions(https://github.com/signavio/react-mentions) module, but since this module uses textarea as the input, when wrapping it around react-quill it doesn't work(React-quill does not work with textarea)

**Comment by alexkrolick** [comment]
You'll probably need something Quill-specific. Check the project docs:

- https://quilljs.com/docs/modules/
- https://github.com/zenoamaro/react-quill#custom-formats
- https://github.com/quilljs/quill
- Codepen https://codepen.io/pen?template=xgyOXQ
- Custom toolbar Codepen https://codepen.io/pen?template=gmroPj

**Comment by hiteshagja** [comment]
@pablonm3 found any solution?

**Comment by DXTimer** [comment]
Using the [quill-mention](https://github.com/afconsult/quill-mention) module:

Example:

```js
import React, { Component } from 'react'
import ReactQuill from 'react-quill'
import QuillMention from 'quill-mention'

const atValues = [
  { id: 1, value: 'Fredrik Sundqvist' },
  { id: 2, value: 'Patrik Sjölin' }
];
const hashValues = [
  { id: 3, value: 'Fredrik Sundqvist 2' },
  { id: 4, value: 'Patrik Sjölin 2' }
]

export default class Editor extends Component {
  state = {
    text: ''
  }

  handleChange = (value) => {
    this.setState({text: value})
  }

  mentionModule = {
    allowedChars: /^[A-Za-z\s]*$/,
    mentionDenotationChars: ["@", "#"],
    source: function (searchTerm, renderList, mentionChar) {
      let values;

      if (mentionChar === "@") {
        values = atValues;
      } else {
        values = hashValues;
      }

      if (searchTerm.length === 0) {
        renderList(values, searchTerm);
      } else {
        const matches = [];
        for (i = 0; i < values.length; i++)
          if (~values[i].value.toLowerCase().indexOf(searchTerm.toLowerCase())) matches.push(values[i]);
        renderList(matches, searchTerm);
      }
    },
  }

  render () {
    return (
      <ReactQuill value={this.state.text}
                  onChange={this.handleChange}
                  modules={{mention: this.mentionModule}}/>
    )
  }
}
```

**Comment by hardiked** [comment]
Not able to get it working, in my component. I am just able to type one letter and then it gets out of the focus. Every time it behaves in the same manner. Can you help me.

**Comment by ssc-dev** [comment]
@hardiked (or whoever else will stumble upon this problem)
In my case the problem was that the reference for the source function changed. I fixed it by moving the source function outside of the component:
```js
const Editor = () => {
  return (
    <ReactQuill
      modules={{
        mention: {
          // this will create a new function `source` each render
          source: async (s, r) => r(await api.get(s))
        }
      }}
    />
  )
};
```
fix by:
```js
// This will create the source function only once
const mention = {source: async (s, r) => r(await api.get(s))}
const Editor = () => {
  return (
    <ReactQuill
      modules={{
        mention
      }}
    />
  )
};
```
You can also use `useCallback` if you want to define the function in the react component.

**Comment by Rafi993** [comment]
But can I render custom react component in the mention (both in the suggestion and when the mention is selected).

**Comment by ssc-dev** [comment]
@Rafi993 probably not, because quill-mention uses `innerHTML` to set the item, which is not compatible with the way react works.

    li.innerHTML = this.options.renderItem(data[i], searchTerm);

from https://github.com/afry/quill-mention/blob/c448f3c96f3e7521328249ab106838d544a5db71/src/quill.mention.js#L286

**Comment by Element7** [comment]
Has anyone make onSelect callback up and running correctly?? and could share some example ?

**Comment by sidharthancr** [comment]
I am not able to get the keyPress working. Anybody else had this issue?

**Comment by marinona** [comment]
> Using the [quill-mention](https://github.com/afconsult/quill-mention) module:
> 
> Example:
> 
> ```js
> import React, { Component } from 'react'
> import ReactQuill from 'react-quill'
> import QuillMention from 'quill-mention'
> 
> const atValues = [
>   { id: 1, value: 'Fredrik Sundqvist' },
>   { id: 2, value: 'Patrik Sjölin' }
> ];
> const hashValues = [
>   { id: 3, value: 'Fredrik Sundqvist 2' },
>   { id: 4, value: 'Patrik Sjölin 2' }
> ]
> 
> export default class Editor extends Component {
>   state = {
>     text: ''
>   }
> 
>   handleChange = (value) => {
>     this.setState({text: value})
>   }
> 
>   mentionModule = {
>     allowedChars: /^[A-Za-z\s]*$/,
>     mentionDenotationChars: ["@", "#"],
>     source: function (searchTerm, renderList, mentionChar) {
>       let values;
> 
>       if (mentionChar === "@") {
>         values = atValues;
>       } else {
>         values = hashValues;
>       }
> 
>       if (searchTerm.length === 0) {
>         renderList(values, searchTerm);
>       } else {
>         const matches = [];
>         for (i = 0; i < values.length; i++)
>           if (~values[i].value.toLowerCase().indexOf(searchTerm.toLowerCase())) matches.push(values[i]);
>         renderList(matches, searchTerm);
>       }
>     },
>   }
> 
>   render () {
>     return (
>       <ReactQuill value={this.state.text}
>                   onChange={this.handleChange}
>                   modules={{mention: this.mentionModule}}/>
>     )
>   }
> }
> ```

Working but missing module Quill register:

```
import ReactQuill, { Quill } from 'react-quill';
import QuillMention from 'quill-mention';
Quill.register('modules/mentions', QuillMention)
```

**Comment by gigiskarlett** [comment]
> Has anyone make onSelect callback up and running correctly? and could share some example ? Thank you in advance.

Probably late to this but were you able to create one?

**Comment by gigiskarlett** [comment]
> But can I render custom react component in the mention (both in the suggestion and when the mention is selected).

Were you able to find a solution for this?

**Comment by aclarembeau** [comment]
> Has anyone make onSelect callback up and running correctly? and could share some example ? Thank you in advance.

Adding this to save time for other users: if like me, you did the whole setup, but hitting key/selecting an entry does not add the mention, don't forget to add the mention in formats :)

**Comment by kritarth2121** [comment]
`/* eslint-disable object-shorthand */
import React, { useCallback, useEffect, useRef, useState } from 'react';
import ReactQuill, { Quill } from 'react-quill';
import 'react-quill/dist/quill.snow.css';
import 'quill-mention';
import 'quill-mention/dist/quill.mention.css';

interface Props {
  showToolbar?: boolean;
  atValues?: { id: number; value: string }[];
  hashValues?: { id: number; value: string }[];
  handleChange?: any;
}

const Font = Quill.import('formats/font');
Font.whitelist = ['Sans-Serif', 'serif', 'monospace'];
Quill.register(Font, true);

const QuillTextbox: React.FC<Props> = function (props: Props) {
  const { atValues, hashValues, showToolbar, handleChange } = props;
  const reference = useRef(null);
  const onChange = () => {
    const { ops } = reference.current.getEditor().getContents();
    handleChange(ops);
  };

  const modules = {
    mention: {
      allowedChars: /^[A-Za-z\sÅÄÖåäö]*$/,
      mentionDenotationChars: ['@', '#'],
      source: useCallback(
        (
          searchTerm: string,
          renderItem: (
            arg0: { id: number; value: string }[] | undefined,
            arg1: any
          ) => void,
          mentionChar: string
        ) => {
          let values;

          if (mentionChar === '@') {
            values = atValues;
          } else if (mentionChar === '#') {
            values = hashValues;
          }

          if (searchTerm.length === 0) {
            renderItem(values, searchTerm);
          } else if (values) {
            const matches = [];
            for (let i = 0; i < values.length; i += 1)
              if (
                values[i].value.toLowerCase().indexOf(searchTerm.toLowerCase())
              )
                matches.push(values[i]);
            renderItem(matches, searchTerm);
          }
        },
        []
      ),
    },

    toolbar: [
      ['bold', 'italic', 'underline', 'strike'],
      ['blockquote', 'link'],
      [{ color: [] }, { background: [] }],
      [
        {
          font: Font.whitelist,
        },
      ],
      [{ align: [] }],
      ['clean'],
      ['image'],
    ],
  };

  return (
    <>
      {' '}
      {showToolbar ? (
        <ReactQuill
          theme='snow'
          ref={reference}
          modules={modules}
          onChange={onChange}
        />
      ) : (
        <form>
          <ReactQuill
            ref={reference}
            theme='snow'
            modules={{ ...modules, toolbar: false }}
            onChange={onChange}
          />
        </form>
      )}
    </>
  );
};

QuillTextbox.defaultProps = {
  showToolbar: true,
  atValues: [
    { id: 1, value: 'Fredrik Sundqvist' },
    { id: 2, value: 'Patrik Sjölin' },
  ],
  hashValues: [
    { id: 1, value: 'Fredrik Sundqvist' },
    { id: 2, value: 'Patrik Sjölin' },
  ],
};
export default React.memo(QuillTextbox);
`
I have done it like this using useCallBack for mention ,and ref for getting values.Wasted half a day for doing so😐
😐

**Comment by andrezimpel** [comment]
I am using a functional component with useState since I am passing the values (users) to the editor.

```js
export default function Editor({ value, onChange, users=[], readOnly=false }) {
  const [tmpValue, setTmpValue] = useState("")
  const [mention, setMention] = useState({})

  const toolbar = [
    ["bold", "italic"],
    [{ list: "ordered" }, { list: "bullet" }],
    ["link"]
  ]

  const formats = [
    "bold",
    "italic",
    "mention",
    "ordered",
    "bullet",
    "link"
  ]

  const modules = readOnly ? { toolbar: false } : { mention: mention, toolbar }

  useEffect(() => {
    setTmpValue(value === "" ? "" : JSON.parse(value))
    setMention({
      mentionDenotationChars: ["@"],
      dataAttributes: ['id', 'value', 'denotationChar', 'link', 'target','disabled', 'type'],
      source: function(searchTerm, renderList, mentionChar) {
        let values;

        values = users.map(v => {
          return {
            id: v.id,
            value: v.displayName,
            type: v.__typename
          }
        })

        // if (mentionChar === "@") {
        // 
        // } else {
        //   values = [];
        // }

        if (searchTerm.length === 0) {
          renderList(values, searchTerm);
        } else {
          const matches = [];
          for (let i = 0; i < values.length; i++)
            if (
              ~values[i].value.toLowerCase().indexOf(searchTerm.toLowerCase())
            )
              matches.push(values[i]);
          renderList(matches, searchTerm);
        }
      }
    })
  }, [])

  return (
    <div className="z-30">
      <ReactQuill
        theme="snow"
        value={tmpValue}
        onChange={(val, delta, source, editor) => {
          setTmpValue(val)
          onChange(JSON.stringify(editor.getContents()))
        }}
        formats={formats}
        modules={modules}
        readOnly={readOnly}
      />
    </div>
  )
}
```

**Comment by darshak369** [comment]
> @hardiked (or whoever else will stumble upon this problem) In my case the problem was that the reference for the source function changed. I fixed it by moving the source function outside of the component:
> 
> ```js
> const Editor = () => {
>   return (
>     <ReactQuill
>       modules={{
>         mention: {
>           // this will create a new function `source` each render
>           source: async (s, r) => r(await api.get(s))
>         }
>       }}
>     />
>   )
> };
> ```
> 
> fix by:
> 
> ```js
> // This will create the source function only once
> const mention = {source: async (s, r) => r(await api.get(s))}
> const Editor = () => {
>   return (
>     <ReactQuill
>       modules={{
>         mention
>       }}
>     />
> 
  )
> };
> ```
> 
> You can also use `useCallback` if you want to define the function in the react component.

Hey @ssc-dev 

I am facing the same issue after separating the source to other constant the editor went away.
No Luck 

What is the actually reason behind this issue i am still figuring out by their source code. can you help here 

Which version you are using I am using the latest `react-quill` 2.0.0 and `quill-mention` 3.1.0.

**Comment by kostyanet** [comment]
> > Has anyone make onSelect callback up and running correctly? and could share some example ? Thank you in advance.
> 
> Adding this to save time for other users: if like me, you did the whole setup, but hitting key/selecting an entry does not add the mention, don't forget to add the mention in formats :)

Thanks mate, you've saved my day!

**Comment by epadarsh** [comment]
whats the defenition inside renderList function. Or how can we customise the users list to show

**Comment by epadarsh** [comment]
Can we customize the render list function by passing our JSX to the module? is this possible?
My purpose is to show the suggested user list as a dropdown instead of its default <li>

**Comment by kamaladenalhomsi** [comment]
> ```
> import` React, { useCallback, useEffect, useRef, useState } from 'react';
> import ReactQuill, { Quill } from 'react-quill';
> import 'react-quill/dist/quill.snow.css';
> import 'quill-mention';
> import 'quill-mention/dist/quill.mention.css';
> 
> interface Props {
>   showToolbar?: boolean;
>   atValues?: { id: number; value: string }[];
>   hashValues?: { id: number; value: string }[];
>   handleChange?: any;
> }
> const Font = Quill.import('formats/font');
> Font.whitelist = ['Sans-Serif', 'serif', 'monospace'];
> Quill.register(Font, true);
> 
> const QuillTextbox: React.FC<Props> = function (props: Props) {
>   const { atValues, hashValues, showToolbar, handleChange } = props;
>   const reference = useRef(null);
>   const onChange = () => {
>     const { ops } = reference.current.getEditor().getContents();
>     handleChange(ops);
>   };
> 
>   const modules = {
>     mention: {
>       allowedChars: /^[A-Za-z\sÅÄÖåäö]*$/,
>       mentionDenotationChars: ['@', '#'],
>       source: useCallback(
>         (
>           searchTerm: string,
>           renderItem: (
>             arg0: { id: number; value: string }[] | undefined,
>             arg1: any
>           ) => void,
>           mentionChar: string
>         ) => {
>           let values;
> 
>           if (mentionChar === '@') {
>             values = atValues;
>           } else if (mentionChar === '#') {
>             values = hashValues;
>           }
> 
>           if (searchTerm.length === 0) {
>             renderItem(values, searchTerm);
>           } else if (values) {
>             const matches = [];
>             for (let i = 0; i < values.length; i += 1)
>               if (
>                 values[i].value.toLowerCase().indexOf(searchTerm.toLowerCase())
>               )
>                 matches.push(values[i]);
>             renderItem(matches, searchTerm);
>           }
>         },
>         []
>       ),
>     },
> 
>     toolbar: [
>       ['bold', 'italic', 'underline', 'strike'],
>       ['blockquote', 'link'],
>       [{ color: [] }, { background: [] }],
>       [
>         {
>           font: Font.whitelist,
>         },
>       ],
>       [{ align: [] }],
>       ['clean'],
>       ['image'],
>     ],
>   };
> 
>   return (
>     <>
>       {' '}
>       {showToolbar ? (
>         <ReactQuill
>           theme='snow'
>           ref={reference}
>           modules={modules}
>           onChange={onChange}
>         />
>       ) : (
>         <form>
>           <ReactQuill
>             ref={reference}
>             theme='snow'
>             modules={{ ...modules, toolbar: false }}
>             onChange={onChange}
>           />
>         </form>
>       )}
>     </>
>   );
> };
> 
> QuillTextbox.defaultProps = {
>   showToolbar: true,
>   atValues: [
>     { id: 1, value: 'Fredrik Sundqvist' },
>     { id: 2, value: 'Patrik Sjölin' },
>   ],
>   hashValues: [
>     { id: 1, value: 'Fredrik Sundqvist' },
>     { id: 2, value: 'Patrik Sjölin' },
>   ],
> };
> export default React.memo(QuillTextbox);
> ```
> 
> I have done it like this using useCallBack for mention ,and ref for getting values.Wasted half a day for doing so😐 😐

Thank you for mentioning useCallback!! I was running out of ideas trying to figure out why adding `source` function breaks my editor, all I needed is to pass useCallback to source instead of passing a function directly to it.

**Comment by nikitadubyk** [comment]
If someone runs into the problem that the list of `mentions` can be updated and the `source` is already memoized - `useRef` for the list is used

Here is a code sample that helped me with the problem:
```
export const Component = (someProps) => {
  const mentionUsersRef = useRef(mentionUsers);
  const [isFocused, setFocused] = useState(false);

  useEffect(() => {
    mentionUsersRef.current = mentionUsers;
  }, [mentionUsers]);
  
  const source = useCallback(() => {
    // use mentionUsersRef.current here
  }, [])

  const modules = useMemo(() => ({
    // your models
   mention: {
      source
   }
  }), [])
  
  return <ReactQuill modules={modules} />
}
```
