### ISSUE TITLE
Adding formula to the editor

### ISSUE THREAD

**Issue by camliu89** [zenoamaro/react-quill#325]
Hi.

After trying to add a formula to the editor, Quill throws an error in the console:

`TypeError: Cannot read property 'render' of undefined`

After digging a little bit, I found that the problem is the `window.katex.render` where `katex` is undefined.

Are you able to provide a solution?

Thanks.

#### React-Quill version 
- [*] master

**Comment by Yutiy** [comment]
I also encountered this problem, how to solve it...

**Comment by alexkrolick** [comment]
You need to have katex available on the window - See the Quill docs: https://quilljs.com/docs/modules/formula/

**Comment by wingsiu** [comment]
Anyone solve this problem?

**Comment by flockooaube** [comment]
I found the solution for react-quill. Add following code the it work.
1. Install Katex
>npm install katex

2. Add following 3 line codes to your component
/-----
import katex from 'katex';
import 'katex/dist/katex.min.css';
window.katex = katex;
class xxxxForm extends React.Component {
.......................
}
----/

Then the alarm cleared and formula input successfully

**Comment by awanthairushan** [comment]
I have install and imported the katex as metioned in abov reply. 
import KaTeX from 'katex';
import 'katex/dist/katex.min.css';
(window as any).KaTeX = KaTeX;

Still I got this warning message in the console. Can anyone tell me the reason ? 


<img width="791" height="486" alt="Image" src="https://github.com/user-attachments/assets/a1830ed6-a314-47a2-b026-1000dea5f5fb" />
