### ISSUE TITLE
this.setState is not a function on clean component render

### ISSUE THREAD

**Issue by AlexKvazos** [zenoamaro/react-quill#327]
![screen shot 2018-02-13 at 1 51 06 pm](https://user-images.githubusercontent.com/4448627/36170573-575de0a0-10c5-11e8-851e-8f3abed33771.png)

![screen shot 2018-02-13 at 1 54 06 pm](https://user-images.githubusercontent.com/4448627/36170585-606fda7c-10c5-11e8-89db-bac5cfeb2e04.png)

#### React-Quill version 
- [x ] 1.2.3

**Comment by AlexKvazos** [comment]
I am importing quill through `import Quill from 'react-quill'`

**Comment by alexkrolick** [comment]
The `setState` method would be provided by the React component prototype; it wouldn't necessarily appear in the devtools as part of the object. Is your component perhaps unmounting before the editor setup is complete?

**Comment by AlexKvazos** [comment]
It's not unmounting, it's just a normal render with no props. What information can I provide for you to check further?

**Comment by alexkrolick** [comment]
A Codepen to demonstrate the issue would help.

By the way, it looks like you're trying to use the editor as a form element. The editor contents won't be captured on submit because it does not wrap a DOM element like a textarea or input. You need to provide a change handler and synchronize with form state yourself. (Another strategy is to sync with a hidden input).

**Comment by AlexKvazos** [comment]
I'm aware I need to handle change events from Quill. I just didn't add any props to make sure they weren't the issue and confirmed that those errors are still appearing, I will be checking on a clean repo and if I can reproduce it, I will let link you. Maybe it could be the way the parent component behaves.

**Comment by AlexKvazos** [comment]
Closing this issue since I can't reproduce on a clean project. Thank you!
