### ISSUE TITLE
Not compatible with Preact

### ISSUE THREAD

**Issue by AlexKvazos** [zenoamaro/react-quill#328]
Hello, this is to be considered a feature request more than a bug.

Current version of react-quill doesn't work on a Preact environment (https://preactjs.com/)

Would it be possible to test and see what Preact is missing or react-quill is missing to make this work together? Thanks.

**Comment by AlexKvazos** [comment]
Looks like Preact is having issues with Mixins https://github.com/developit/preact-compat/issues/442

**Comment by alexkrolick** [comment]
At some point the mixin and toolbar will be deprecated in favor of an ES6 rewrite. It'll be a breaking change but we can make sure it works with Preact at that point.

**Comment by alexkrolick** [comment]
If you don't need the full declarative wrapper provided by React-Quill, you can create a "lite version" that simply instantiates Quill in a (P)React-provided DOM element like this: https://github.com/alexkrolick/electron-quill/blob/master/app/editor.jsx

**Comment by AlexKvazos** [comment]
This is exactly what I need. Thank you very much. Feel free to close this issue if the ES6 migration is being tracked somewhere else.
