### ISSUE TITLE
CSS doesn't seem to be loaded (or loads really badly)

### ISSUE THREAD

**Issue by Drillan767** [zenoamaro/react-quill#329]
Hello, I just yarn added ReactQuill, everything went smoothly for the installation, but when I tried to make Quill work, nothing was correct. I did nothing else than copying [the code you display here](https://github.com/zenoamaro/react-quill#use-the-component), and imported both ReactQuill and the snow theme.

At first, I thought everything was corrupted by Material UI, that I use for the global layout, but trying Quill from a new file that renders nothing more than it returns exactly the same thing. Here is a screenshot of what I get : [[link]](https://imgur.com/a/sa0CR)

As you can see, on the top left hand corner, you can see some empty buttons, and on the bottom left hand corner, some more empty buttons with a text field.

Is this an obvious mistake from me? Should I upgrade/downgrade something?

#### React-Quill version 
- [x] master (well the one you get when you don't specify which version)

react@16.2.0
react-dom@16.2.0
react-quill@1.2.4

Thank you in advance

**Comment by alexkrolick** [comment]
The CSS definitely is not loaded in that image.

How you add CSS varies depending on your bundling config. Here are some common options: https://github.com/zenoamaro/react-quill#fetching-styles-from-the-cdn

**Comment by Drillan767** [comment]
You were right, everything went "normal" once I correctly added the css file as CDN, thank you for your answer!

**Comment by MWolman1990** [comment]
I had the exact same problem. I am following Ryan Dhungel's MERN stack SEOBLOG course on Udemy and the cause of my problem was improperly importing the css file. For some reason, he had `import '../../node_modules/react-quill/dist/quill.snow.css';` as the import. Changing it to `import 'react-quill/dist/quill.snow.css';` solved my problem. Thank you!
