### ISSUE TITLE
resize handle?

### ISSUE THREAD

**Issue by ChuckIrvine** [zenoamaro/react-quill#334]
I'm guessing it's not possible since I've done lots of searching..... Is it possible to get a textarea like resize handle so the user can resize the size of the editor window?

**Comment by alexkrolick** [comment]
It's possible using CSS 😄:

```
.ql-editor {
  overflow-y: scroll;
  resize: vertical;
}
```

https://css-tricks.com/almanac/properties/r/resize/

https://codepen.io/alexkrolick/pen/yvRgab?editors=0100

**Comment by scdev0** [comment]
I find that if I change overflow-y to auto. The resize handle does not appear in Chrome but still able to resize. Is that possible to fix?

**Comment by scdev0** [comment]
The resize handle on the second editor seems to be okay though https://codepen.io/anon/pen/bPZmVd

**Comment by benghanemsaad** [comment]
:host ::ng-deep .ql-editor {
    overflow: auto;
    resize: vertical;
}
This should fix the issue, thank me later :)
