### ISSUE TITLE
JSX element type 'ReactQuill' does not have any construct or call signatures.

### ISSUE THREAD

**Issue by Hereward** [zenoamaro/react-quill#336]
I'm working in Typescript. I have implemented code as per ReadMe instructions but I get an odd Typescript error: "JSX element type 'ReactQuill' does not have any construct or call signatures." on the JSX component (see image).

The editor does render ok, so I'm not sure what the error message is all about.

![quill](https://user-images.githubusercontent.com/1784096/36743543-1bb228e6-1c1d-11e8-800b-bbc322828f2c.JPG)

**Comment by Hereward** [comment]
**Update** 
this syntax works: `const ReactQuill = require('react-quill');`
this fails: `import ReactQuill from 'react-quill';`
this generates error but renders: ` import * as ReactQuill from "react-quill";`
**Note**: I am compiling to ES6.

**Comment by ycjcl868** [comment]
not work.
"react-quill": "^1.3.1",

![image](https://user-images.githubusercontent.com/13595509/46452924-f443a900-c7d0-11e8-9e82-10c8f9eb364b.png)

**Comment by wvyeun** [comment]
I'm having the same problem 'JSX element type 'ReactQuill' does not have any construct or call signatures' in Typescript with "react-quill": "^1.3.2"

**Comment by AhmadiRamin** [comment]
Any update? I'm still getting this error!

**Comment by paigeflourin** [comment]
i also get this error.

**Comment by alexkrolick** [comment]
I think the `import * as ` syntax is the problem, not sure what if it's a typescript version difference or something with the Quill or ReactQuill definitions themselves.

**Comment by zscaiosi** [comment]
@paigeflourin solution works!

**Comment by leoseccia** [comment]
same issue here :(

**Comment by aplaxas** [comment]
[#349](https://github.com/zenoamaro/react-quill/pull/349) is working for me.

// type.d.s 
export class ReactQuill extends React.Component<ReactQuill.ComponentProps> {
	focus(): void;
	blur(): void;
	getEditor(): Quill.Quill;
}
export { Quill } from "quill";
export = ReactQuill;

// code
import * as ReactQuill from 'react-quill';
import 'react-quill/dist/quill.snow.css'

**Comment by iamwill123** [comment]
All you need to do is add `declare module 'react-quill';` to your `./index.d.ts` file for example:
<img width="510" alt="Screen Shot 2020-11-20 at 5 22 49 PM" src="https://user-images.githubusercontent.com/15272175/99855828-ad060700-2b55-11eb-90c6-f89420f3ab4b.png">
