### ISSUE TITLE
Can't register a component 

### ISSUE THREAD

**Issue by kingmatusevich** [zenoamaro/react-quill#339]
I'm attempting to register a custom module to use with Quill, given my particular needs and the fact Quill is very extensible, as your own doc says. This is supposed to be possible,
quoting the ``react-quill`` docs:
> ``Quill`` : The ``Quill`` namespace on which you can call ``registerModule`` and such.

However, when doing
```js
import ReactQuill, {Quill} from 'react-quill';
```
...
```js
Quill.registerModule('moduleName', SomeModule);
```
I get the following Webpack Error:
```
TypeError: __WEBPACK_IMPORTED_MODULE_9_react_quill__.Quill.registerModule is not a function
```

**Comment by alexkrolick** [comment]
It's actually just `register` https://quilljs.com/docs/api/#register

**Comment by kingmatusevich** [comment]
Curious, thanks!
