### ISSUE TITLE
Placeholder is not updating

### ISSUE THREAD

**Issue by dbabaioff** [zenoamaro/react-quill#340]
If I try to re-render my component with a different placeholder - the placeholder is not changing.

Looking into: react-quill/lib/component.js
The placeholder is not on `dirtyProps` list

See example:
https://codepen.io/dbabaioff/pen/pLJyLq

React-Quill version
[*] 1.2.0

**Comment by alexkrolick** [comment]
Care to PR in a fix?

**Comment by RafikiTiki** [comment]
If you put `placeholder` in `dirtyProps` Quill will reinstantiate on every placeholder change which probably is not very optimal. There isn't any API in Quill itself to change placeholder and as stated in [this comment](https://github.com/quilljs/quill/issues/1150#issuecomment-264048390) from Quill contributor, we should use dataset to change placeholder. Way to do it:

1. You need to set up refs as described [here](https://github.com/zenoamaro/react-quill#methods) -> example
2. After you have refs set up use this code in any place you want to update placeholder (react lifecycle or whatever):`this.quillRef.root.dataset.placeholder = 'Placeholder text'`

**Comment by alexkrolick** [comment]
Ok, let's defer to the Quill recommendation for handling placeholder. I'll add a note to the README.

**Comment by alkismavridis** [comment]
I know this issue is closed since a long time, but I would expect that this should be an internal responsibility of react-quill instead of forwarding this responsibility to the users. You could make the `placeholder` prop **really** work by doing something like that on your side:

```
useEffect(() => {
    ref.current.getEditor().root.dataset.placeholder = props.placeholder || "";
  }, [ref, props.placeholder]);
```

**Comment by akbarob** [comment]
sdahddddimport Editor from './Editor';import Editor from './Editor';import Editor from './Editor';
import Editor from './Editor';import Editor from './Editor';
