### ISSUE TITLE
IME Japanese Support

### ISSUE THREAD

**Issue by jessierevil04** [zenoamaro/react-quill#342]
When typing with the IME enabled in Windows 7 Chrome(Ver 65.0.3325.162) & IE 11,
the first character is ignored.
In https://quilljs.com/ live demo, the issue does not exists.

**Steps to replicate:**
1. Enable Japanese Hiragana IME
2. Visit https://zenoamaro.github.io/react-quill/ (DEMO)
3. Clear all contents until the html content becomes `<p><br></p>`
4. Type "tesuto" + Enter

**Expected behavior:**
Result: てすと

**Actual behavior:**
Result (Chrome): ｔてすと
Result (IE): ｔえすと

**Related Issues:**
https://github.com/surmon-china/vue-quill-editor/issues/56
https://github.com/quilljs/quill/issues/1904
https://github.com/quilljs/quill/issues/1453

React Quill 1.2.6

**Comment by colorhook** [comment]
updating quill to v1.3.6 can resolve this issue

**Comment by alexkrolick** [comment]
`yarn upgrade react-quill`

or

`npm upgrade react-quill` should update the dependency
