### ISSUE TITLE
Center align is kind of pointless without custom styling...

### ISSUE THREAD

**Issue by alxvallejo** [zenoamaro/react-quill#343]
Just trying to gauge everyone's opinion on the align options. If I utilize a 'center' align for instance, and I am saving this to my DB... or sending to some third party API ... whatever, The output results in this:

`<p class="ql-align-center">What's happening</p>`

That's fairly useless if you have no control over the resulting formatting. It would be optimal to actually embed inline styles of `text-align: center`. 

Any thoughts?

**Comment by alexkrolick** [comment]
One common solution is to apply the Quill stylesheet to the rendered output by adding `#quill .ql-content` to the container.

You can also configure Quill to use inline styles: https://quilljs.com/playground/#class-vs-inline-style

In any case, this an upstream issue and not something React-Quill would handle.
