### ISSUE TITLE
doesnt work when rendering on the server

### ISSUE THREAD

**Issue by flyon** [zenoamaro/react-quill#348]
When trying to render the page on the server using ReactDOM.hydrate the following error occurs:
`ReferenceError: document is not defined
at Object.DIFF_DELETE (C:\web\dacore\modules\html\node_modules\quill\dist\quill.js:7588:12)`

**Comment by alexkrolick** [comment]
Duplicate of https://github.com/zenoamaro/react-quill/issues/185
