### ISSUE TITLE
React 0.14 support

### ISSUE THREAD

**Issue by jure** [zenoamaro/react-quill#35]
Any plans for this? I might attempt it in a week or so, if you don't have any plans. I'm actually already using react-quill in 0.14, and other than a few warnings for deprecations, there seems to be no breaking changes.

**Comment by J22Melody** [comment]
I have got warnings about .getDOMNode() method

**Comment by zenoamaro** [comment]
@jure yes, I'd be very interested. I was gonna do it some time ago, but real life went in the way.

If it's no problem for you to do 0.14, I'll gladly consider it for merging and a cutting a new release.

I don't know how many people are still on React 0.12 or 0.13 to say if it'd be worthwhile to preserve compatibility. What do you think? Thanks

**Comment by skrobek** [comment]
@zenoamaro Would be great to tag current version as the latest for to React 0.12 and 0.13. After there is a stable release for 0.14.x would be great to update the code (it's not a big deal ;-)).

**Comment by jacktrades** [comment]
I have [a branch here](https://github.com/jacktrades/react-quill/tree/fix-warnings-on-react-14) that fixes the warnings on 0.14.x, but it does break compatibility with <= 0.13.x.

**Comment by jure** [comment]
That's a very minimal diff, awesome!

I don't see how we can keep being compatible with < 0.14 though ... as @skrobek says, I think it would be fine to tag the current version as 0.13 compatible, and then break compatibility for those versions in the new release.

**Comment by zenoamaro** [comment]
Agree completely. It is long overdue (as well as an es6 rewrite), and compatibility with older versions has been kept for a long time. Additionally, I think this would be cool excuse to break the current api and solve #33.

I've merged most of the PR that were currently open, so please check if it still merges cleanly. I think we can also get rid of this stuff [here](https://github.com/zenoamaro/react-quill/blob/baafbe56acf41fe2576fa6afdc7fd0d0f72c35ec/src/component.js#L8-L22) and [here](https://github.com/zenoamaro/react-quill/blob/baafbe56acf41fe2576fa6afdc7fd0d0f72c35ec/demo/index.js#L117-L129). In the mean time I'll see if what else I can fix cleanly before cutting the release.

Thanks a lot, I've had little time recently and this contribution is really appreciated.

**Comment by skrobek** [comment]
Would be great to have a new version with this PR.

**Comment by laxplaer** [comment]
+1

**Comment by romanoff** [comment]
+1

**Comment by cathome** [comment]
+1

**Comment by JapMul** [comment]
+1

**Comment by farisj** [comment]
+1

**Comment by kylefdoherty** [comment]
+1

**Comment by carlosepp** [comment]
+1

**Comment by danwu** [comment]
+1

**Comment by gitupiikki** [comment]
+1

**Comment by josercruz01** [comment]
+1

**Comment by tylercollier** [comment]
+1

**Comment by stearagon** [comment]
+1

**Comment by laurentqro** [comment]
+1

**Comment by Enijar** [comment]
+1

**Comment by coniel** [comment]
+1

**Comment by Lesyek** [comment]
+1

**Comment by caynan** [comment]
+1

**Comment by jlegrone** [comment]
+1

**Comment by jure** [comment]
Awesome, thanks @zenoamaro! I'll check this soon.

**Comment by tylercollier** [comment]
This works for me. I no longer get any warnings/deprecations in my browser console. However, since the changes are not published to npm yet, for now you'll need a local copy of this repo and then you must point your `package.json` to your local copy:

```
{
  "dependencies": {
    "react-quill": "file:/path/to/your/local/copy/of/react-quill"
  }
}
```
