### ISSUE TITLE
Cannot install from master branch through NPM

### ISSUE THREAD

**Issue by jaepd** [zenoamaro/react-quill#351]
#### React-Quill version 
- [x] master

Installing via NPM normally (`npm install react-quill`) works fine. However trying to install it from the master branch (either by having `"react-quill": "zenoamaro/react-quill"` or by `npm install https://github.com/zenoamaro/react-quill.git`) fails with the same error:
```
> react-quill@1.2.7 prepack /home/jae/.npm/_cacache/tmp/git-clone-428e2c79
> make build

make: ./node_modules/.bin/webpack: Command not found
make: *** [Makefile:33: build] Error 127
npm ERR! code ENOPACKAGEJSON


npm ERR! package.json Non-registry package missing package.json: git+https://github.com/zenoamaro/react-quill.git.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jae/.npm/_logs/2018-04-09T16_12_02_578Z-debug.log
```
The debug log is [attached](https://github.com/zenoamaro/react-quill/files/1890750/2018-04-09T16_12_02_578Z-debug.log).

I'm not really sure what's going on as I've installed packages before using Github and I've never seen this message. Also `react-quill` definitely has a `package.json` so that error message is misleading. I'm hoping this isn't such edge-case NPM bug but who knows.

As a side note, could a new version be released?

**Comment by jaepd** [comment]
Oh and for system stuff:
- 64-bit Archlinux
- Node v9.11.1
- NPM v5.8.0

**Comment by alexkrolick** [comment]
We don't check built files into source control, so installing as a dependency will not work.

A new version was released a few days ago, what do you think is missing from master?

**Comment by jaepd** [comment]
Ohhh okay that's what that line in the README meant.

Yeah you're right, after looking at NPM there was a release. I was just looking at https://github.com/zenoamaro/react-quill/releases for release info.

Thanks for clarifying all that!
