### ISSUE TITLE
How would you go on adding a http protocol to links added by the user?

### ISSUE THREAD

**Issue by didair** [zenoamaro/react-quill#354]
This isnt an issue with the React Quill package per-se, but I'm having trouble making sure all links attached by the user gets a valid protocol https/http ? I've tried adding a custom link handler and that would work, but I'm not sure how to get the styled input back when replacing it with a `prompt`

Any suggestions are welcome.

Cheers,
Andreas

#### React-Quill version 
master

**Comment by didair** [comment]
Ok so since my original post might have been confusing, here is what im asking: How do i use the styled input that react quill uses?

**Comment by alexkrolick** [comment]
Something like this:

https://github.com/quilljs/quill/pull/1412

If you want you can resurrect the PR and add the requested tests.

**Comment by alexkrolick** [comment]
Closing since this is more of a Quill issue
