### ISSUE TITLE
syntax :true Don't work

### ISSUE THREAD

**Issue by An0nymous0** [zenoamaro/react-quill#357]
`
import hljs from 'highlight.js'
import 'highlight.js/styles/monokai-sublime.css'
import ReactQuill from 'react-quill'; 
import 'react-quill/dist/quill.snow.css'; 
modules= {
            toolbar: [
                [ 'code-block']
            ],
            syntax: true
        }
`

Error: Syntax module requires highlight.js. Please include the library on the page before Quill.

OR

`
import hljs from 'highlight.js'
import 'highlight.js/styles/monokai-sublime.css'
import ReactQuill from 'react-quill'; 
import 'react-quill/dist/quill.snow.css'; 
modules= {
            toolbar: [
                [ 'code-block']
            ],
            syntax: {
                highlight: text => hljs.highlightAuto(text).value
            }
        }
`

issue:Each input is lost focus

https://github.com/zenoamaro/react-quill/issues/284 Could not find a solution

**Comment by alexkrolick** [comment]
Try importing hljs into the global namespace:

`import highlightjs`

**Comment by An0nymous0** [comment]
@alexkrolick I tried it, the result was high。
`import 'highlight.js'`
Error: Syntax module requires highlight.js. Please include the library on the page before Quill.

**Comment by koffeinfrei** [comment]
@alexkrolick I think it would be useful to add support to this to `react-quill` or at least document in the README how to achieve this. After all `syntax: true` is a core feature of quill.

**Comment by alexkrolick** [comment]
It really depends on your bundle set up (Webpack/Typescript/Babel/script). If you want to document a few common patterns, a PR is welcome.

**Comment by jgarboza813** [comment]
Here is the solution, it took me a long time to find : https://codesandbox.io/s/nww9q0v67p?from-embed

It is a real shame that Quill's documentation is so deficient. They spent all this time creating a sleek framework and website but their docs are so bad.

**Comment by alphonso06** [comment]
> 
> 
> Here is the solution, it took me a long time to find : https://codesandbox.io/s/nww9q0v67p?from-embed

This does work on a small and light sandbox and localhost project, but for some reason once I implement this on my actual project Quill just loses focus with every keystroke. I haven't been able to identify the source of this problem.

**Comment by A7U** [comment]
> 
> 
> > Here is the solution, it took me a long time to find : https://codesandbox.io/s/nww9q0v67p?from-embed
> 
> This does work on a small and light sandbox and localhost project, but for some reason once I implement this on my actual project Quill just loses focus with every keystroke. I haven't been able to identify the source of this problem.

I have this issue too :(

**Comment by shery10** [comment]
> > Here is the solution, it took me a long time to find : https://codesandbox.io/s/nww9q0v67p?from-embed
> 
> This does work on a small and light sandbox and localhost project, but for some reason once I implement this on my actual project Quill just loses focus with every keystroke. I haven't been able to identify the source of this problem.

Same issue for me

**Comment by austinbailie** [comment]
> 

Anyone find a solution to this? I am having this issue too

**Comment by austinbailie** [comment]
> > > Here is the solution, it took me a long time to find : https://codesandbox.io/s/nww9q0v67p?from-embed
> > 
> > 
> > This does work on a small and light sandbox and localhost project, but for some reason once I implement this on my actual project Quill just loses focus with every keystroke. I haven't been able to identify the source of this problem.
> 
> Same issue for me

Anyone find a solution to this? I am having the same issue too
