### ISSUE TITLE
Paste events on selection

### ISSUE THREAD

**Issue by rodrigo-brito** [zenoamaro/react-quill#358]
I'm using the react quill without controlled mode, without default style, only with some customizations on toolbar. When I paste some content over a text selection, the content is  deleted.

#### React-Quill version: 1.2.7

![quill bug](https://user-images.githubusercontent.com/7620947/39055779-73d0ac82-448b-11e8-92c0-edf274f3bb15.gif)

```jsx
<ReactQuill
        ref={ref => {
            this.reactQuillRef = ref;
        }}
        onChange={this.onChange}
        defaultValue={this.state.content}
        modules={{
            toolbar: false
        }}
        readOnly={this.state.saving}
        formats={["bold", "italic", "underline", "video", "image", "link"]}
        className="release-editor"
        placeholder="Escreva seu release aqui com no mínimo 250 caracteres..."
/>
```

**Comment by natterstefan** [comment]
Hi @rodrigo-brito, check out my examples in another issue (https://github.com/zenoamaro/react-quill/issues/276#issuecomment-384618178) related to pasting content into the editor. Maybe they help you out.

**Comment by rodrigo-brito** [comment]
I think that is not the same problem, I tested in your code pen, but it hasn't the expected behavior. I tried to create a example with my problem, but doesn't works on codepen.

**Comment by rodrigo-brito** [comment]
Problem solved! We are using a custom theme for the editor and the class `.clipboard` should not use `display: none;`. I copied the style from `snow` theme, and the problem was solved.
