### ISSUE TITLE
How tdo I set the maxLength for the editor?

### ISSUE THREAD

**Issue by rjdecilos** [zenoamaro/react-quill#366]
How do I set the maxLength that I can put in the editor? I tried making the editor read only but after making it read only I won't be able to delete the characters to make the editor available again.

**Comment by rjdecilos** [comment]
nevermind, I've done it by setting the value to same value everytime the length is larger than the limit.

**Comment by michalpokojski** [comment]
When i do this i get an error message: 

![image](https://user-images.githubusercontent.com/29205657/41602946-342c9b4c-73dc-11e8-9d95-feb4c627c8ee.png)

**Comment by alexkrolick** [comment]
You need to reset the Quill selection (cursor location/highlight) if you trim the editor contents

**Comment by michalpokojski** [comment]
@alexkrolick when i try to do this 

```JavaScript
{
      this.quillRef.setEditorSelection({ index: 0, length: 0 })
      this.setState({ quillState: oldState })
      onChange(he.decode(oldState.replace(/\n/g, '')))
    }
```

this happens : 
![image](https://user-images.githubusercontent.com/29205657/41649350-aacbaa6e-747b-11e8-9eb1-4830bf75ec58.png)
