### ISSUE TITLE
onKeyUp, onKeyDown, onKeyPress not working

### ISSUE THREAD

**Issue by brucedlukens** [zenoamaro/react-quill#37]
I've tried passing a callback into these 3 props, as stated in the react-quill API, and haven't seen anything get returned. I checked in component.js and I see that at line 225 it calls onChange (which I do receive updates for). I need onKeyUp to register that a user has hit the enter key but I don't see onKeyUp, onKeyDown, or onKeyPress being used anywhere. Is there anyway to get the key code for enter other than these 3 functions?

**Comment by zenoamaro** [comment]
This change has not yet been published to npm.

Can you verify if this still happens when using master?

**Comment by dshorowitz** [comment]
When are you planning on publishing this to npm? Thanks!

**Comment by zenoamaro** [comment]
Published to NPM just now! This has been a long release, so thanks for the patience.
