### ISSUE TITLE
Retain empty spaces between tags

### ISSUE THREAD

**Issue by ShirlyChan** [zenoamaro/react-quill#370]
empty spaces before and after the text has been thought as bug and has been fixed.
Here's the link: https://github.com/zenoamaro/react-quill/issues/251
But now I need to retain thouse spaces, can i fixed it through configuration?

**Comment by alexkrolick** [comment]
I think in the Quill issues: https://github.com/quilljs/quill there are some discussions about using `pre` or `code` tags to show whitespace.
