### ISSUE TITLE
set id attribute for heading to render TOC(table of content)

### ISSUE THREAD

**Issue by diepvv** [zenoamaro/react-quill#373]
hi everyone!
I have a issure. Create a TOC(table of content) for html document of react-quill.
i have find a librari is: tocbot(https://www.npmjs.com/package/tocbot)
But it need id attribute to render TOC. Now in react-quill not have id attribute when i change text in editor of quill. How to i can set id for heading?

**Comment by alexkrolick** [comment]
You'll probably want to make a custom Blot format for Parchment - here are some links:

- https://quilljs.com/docs/modules/
- https://github.com/zenoamaro/react-quill#custom-formats
- https://github.com/quilljs/quill
- https://www.npmjs.com/search?q=quill%20mentions&page=1&ranking=optimal

**Comment by RUPAAK** [comment]
@diepvv  how did you tackle your problem. Can you tell me
