### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property 'exports' of object (1.4.0-beta.1)

### ISSUE THREAD

**Issue by finom** [zenoamaro/react-quill#376]
Getting a problem using react-quill with Webpack 4.12.2. 

![image](https://user-images.githubusercontent.com/1082083/41971275-7e6d73b2-7a16-11e8-89ce-220e611407bf.png)

The exception is thrown at /lib/index.js

![image](https://user-images.githubusercontent.com/1082083/41971289-88782c94-7a16-11e8-97e2-2cd4edf87c65.png)

#### React-Quill version 
- 1.4.0-beta.1

**Comment by juandjara** [comment]
Same thing happened to me.
Try importing from `react-quill/dist/index` instead of just `react-quill`

**Comment by finom** [comment]
It works, thank you!
