### ISSUE TITLE
Quill modules usage

### ISSUE THREAD

**Issue by vishim** [zenoamaro/react-quill#379]
HI
Do you have an example of how to use quill modules with react-quill.

I could not get quill-markdown-shortcuts to work. Here is the code: 

```
import ReactQuill,  { Quill } from 'react-quill';
import { MarkdownShortcuts} from 'quill-markdown-shortcuts';
Quill.register('MarkdownShortcuts', MarkdownShortcuts);

...
render() {
...
        <ReactQuill value={'abcd'}
          modules={{
            MarkdownShortcuts: {}
          }}
        />
...
}
...
```

This is the Error that I get:
```
quill Cannot import modules/MarkdownShortcuts. Are you sure it was registered?
quill Cannot load MarkdownShortcuts module. Are you sure you registered it?
quill Cannot import modules/MarkdownShortcuts. Are you sure it was registered?
Uncaught TypeError: moduleClass is not a constructor
    at SnowTheme.addModule (quill.js:6052)
    at SnowTheme.addModule (quill.js:6696)
```
#### React-Quill version 
1.3.0

**Comment by xxx** [comment]
I don't know about the particular module you're using, but I've had to [`Quill.import`](https://quilljs.com/docs/api/#import) modules before I could use them.

**Comment by alrik** [comment]
@vishim The error message states, quill cannot import **modules**/MarkdownShortcuts.
try to register your module this way:
`Quill.register('modules/MarkdownShortcuts', MarkdownShortcuts);`

**Comment by pirsquare** [comment]
I've encountered similar issue while using original quilljs (not react-quill) and managed to solve it. In my case, it is due to invalid modules added quill config.

Original Config
```
const quillOptions = {
  modules: {
    toolbar: `quill-toolbar`,
    variable: {}
  }
};
```

After removing `variable` from modules, it worked for me. 
```
const quillOptions = {
  modules: {
    toolbar: `quill-toolbar`
  }
};
```

For anyone encountering this issue, you may want to check if you've added unregistered modules to your config.

**Comment by thinkdj** [comment]
I got the same error on quill on Angular (using ngx-quill). Like @pirsquare mentioned, mine was also a **missing module issue**, whose reference I had forgot to take out b/w projects.

**Comment by TatyanaMolchanova** [comment]
::ng-deep .ngx-quill-editor
  p > br
    display: none
  p:not(:last-of-type)
    margin-bottom: 1rem

**Comment by ishan123456789** [comment]
Any solution for it yet?

**Comment by raju-tagline** [comment]
![Screenshot 2022-07-28 at 4 00 54 PM](https://user-images.githubusercontent.com/98521729/181484724-076ed8b2-42c4-44ec-b493-d84949b21f09.png)

I'm getting this error after all the set-up done.

**Comment by osbeug001** [comment]
I had a similar issue when importing and registering a module, my solution was to: 
1. Import the module from the dist folder : `import BlotFormatter from 'quill-blot-formatter/dist/BlotFormatter'`
2. When registering, register the module's default.: `Quill.register('modules/blotFormatter', BlotFormatter.default);`

Hope this helps.

**Comment by devthub** [comment]
> I had a similar issue when importing and registering a module, my solution was to:
> 
> 1. Import the module from the dist folder : `import BlotFormatter from 'quill-blot-formatter/dist/BlotFormatter'`
> 2. When registering, register the module's default.: `Quill.register('modules/blotFormatter', BlotFormatter.default);`
> 
> Hope this helps.

did you find any workaround?

**Comment by codingwithashu** [comment]
error ReferenceError: document is not defined
