### ISSUE TITLE
Mobile Safari focus on mount issue

### ISSUE THREAD

**Issue by MaxTwentythree** [zenoamaro/react-quill#383]
Hi,

I want to focus the React-Quill editor automatically after the component mounted:
https://codepen.io/maxtwentythree/pen/gKJBaO

This works on Chrome, FF, Safari, but not on Mobile Safari:
After setting reactQuillRef.focus(), Quill even says it's focused (via quillRef.hasFocus()), but it really is not.
Is this a bug or do I do sth wrong?

I'm on the current master.

Thanks,
Max

**Comment by alexkrolick** [comment]
This sounds like an issue in Quill if it is saying it is focused
