### ISSUE TITLE
Localisation - How can I give different language support for label ?

### ISSUE THREAD

**Issue by harshalpanday** [zenoamaro/react-quill#386]
**How can I give different language support for label?**

In our system we provide support for different languages, We are using Quil as Editor and wanted to 
change all its label to language base. For **Ex.** when we click on the **Video** option, one popup opens in which there are label like **Save**, **Enter Video** etc. I wanted to override this and provide my own value according to the selected language in my system.
 
I have tried searching that how can we achieve this in quil but did not get any answer. Can some one please help me out ?

**Comment by alexkrolick** [comment]
- Custom toolbar Codepen https://codepen.io/pen?template=gmroPj
- You could also try adding a CSS class like `lang-en` around the component and target specific CSS rules from the Quill theme files to override.
