### ISSUE TITLE
react-quill crashes in production

### ISSUE THREAD

**Issue by shezankazi** [zenoamaro/react-quill#388]
I am afraid I am getting this past issue again:
https://github.com/zenoamaro/react-quill/issues/346

The submitted fix for webpack does not seem to work anymore.

**Comment by alexkrolick** [comment]
What versions are you resolving for Quill, React, ReactQuill, Webpack?

**Comment by RobertBuice** [comment]
Hi, I'm also having the exact same problem. 

Versions:
Quill: 1.3.6
React: 16.3.2
ReactQuill: 1.3.1
Webpack: 3.11.0

Thanks for any help you could provide!

**Comment by alexkrolick** [comment]
Does it work with @next ?

`yarn add react-quill@next` // 1.4.0-beta.5

**Comment by RobertBuice** [comment]
For me that didn't fix it.

**Comment by shezankazi** [comment]
Sorry for the missing versions:
React: 16.1.0
React-Quill: 1.3.6
Webpack: 3.8.1
Uglify: 3.1.9

**Comment by reggieofarrell** [comment]
Same story here. 

react: 16.2.0
react-quill: 1.3.1
webpack: 3.8.1
uglifyjs-webpack-plugin: 1.2.7

**Comment by labibismaiel** [comment]
I had the same problem, I solved it by changing something in webpack.config.js

```
modules: {
    noParse: /node_modules\/quill\/dist/
}
```

**Comment by alexkrolick** [comment]
https://github.com/zenoamaro/react-quill#bundling-with-webpack
