### ISSUE TITLE
after build，show this bug,  e.isBuffer is not a function，Causes the editor to fail to display properly.

### ISSUE THREAD

**Issue by DarlingJing** [zenoamaro/react-quill#390]
![image](https://user-images.githubusercontent.com/23731001/42986893-e08d2e1e-8c29-11e8-824a-559078639908.png)

**Comment by labibismaiel** [comment]
I had the same problem, I solved it by changing something in webpack.config.js

```
modules: {
    noParse: /node_modules\/quill\/dist/
}
```

**Comment by alexkrolick** [comment]
https://github.com/zenoamaro/react-quill#bundling-with-webpack
