### ISSUE TITLE
How to turn off spellcheck?

### ISSUE THREAD

**Issue by ycjcl868** [zenoamaro/react-quill#391]
![image](https://user-images.githubusercontent.com/13595509/43183669-866ecf76-9018-11e8-84bf-c3bf4437a55e.png)

**Comment by alexkrolick** [comment]
This does not appear to be a feature of Quill: https://quilljs.com/docs/configuration/

**Comment by nombrekeff** [comment]
Any workaround? There seems to be some workarounds for vanilla Quill, see https://github.com/quilljs/quill/issues/2225

**Comment by nzwsch** [comment]
FYI:
```jsx
function MyEditor() {
  const quillRef = useRef(null);

  const handleRef = useCallback((ref) => {
    const quill = ref.getEditor();

    // disable spellcheck
    quill.root.setAttribute('spellcheck', false);

    quillRef.current = ref;
  }, []);

  return <ReactQuill ref={handleRef} />;
}
```

**Comment by patricklongo1** [comment]
> FYI:
> 
> ```js-jsx
> function MyEditor() {
>   const quillRef = useRef(null);
> 
>   const handleRef = useCallback((ref) => {
>     const quill = ref.getEditor();
> 
>     // disable spellcheck
>     quill.root.setAttribute('spellcheck', false);
> 
>     quillRef.current = ref;
>   }, []);
> 
>   return <ReactQuill ref={handleRef} />;
> }
> ```

Its work for me!

**Comment by cancan101** [comment]
@nzwsch what is the use `useRef` doing in your solution? It appears that hooks is unneeded ?
