### ISSUE TITLE
Style issues

### ISSUE THREAD

**Issue by indapublic** [zenoamaro/react-quill#392]
React 16.4

My code is:

```
import React, { Component } from "react";
import "react-quill/dist/quill.core.css";
import "react-quill/dist/quill.snow.css";

export default class WysiwygEditor extends Component {
  constructor(props) {
    super(props);
    this.state = { text: "" }; // You can also pass a Quill Delta here
    this.handleChange = this.handleChange.bind(this);
  }

  componentDidMount() {
    this.quill = require("quill").default;
    this.ReactQuill = require("react-quill").default;
    this.Quill = require("react-quill").Quill;
  }

  handleChange(value) {
    this.setState({ text: value });
  }

  render() {
    return (
      !!this.ReactQuill && (
        <this.ReactQuill
          theme="snow"
          value={this.state.text}
          onChange={this.handleChange}
        />
      )
    );
  }
}
```

What I get after:

![screen shot 2018-08-02 at 19 31 29](https://user-images.githubusercontent.com/856260/43575640-af682436-968a-11e8-9525-e8d55fbb78e4.png)

Seems it's related to styles, but I tried with `core` and `snow` themes. No difference

**Comment by kwayebopp** [comment]
You don't need to import the styles into the component. Rather,  insert the latest stylesheet into the `<head>` of your index.html:
```
<!doctype html>
<html lang="en">

<head>
  /*other head stuff*/
  <link rel="stylesheet" href="//cdn.quilljs.com/1.3.6/quill.snow.css">
</head>
<body>
   /* body stuff */
</body>
</html>
```

**Comment by alexkrolick** [comment]
You can
- use a link like @kwayebopp showed
- set up Webpack (or any bundler) to import CSS as you are doing in the code snippet
- import the stylesheet from within another CSS/SCSS/LESS/PostCSS file

**Comment by indapublic** [comment]
> set up Webpack (or any bundler) to import CSS as you are doing in the code snippet

It's not worked for me. Will try link file sometime later
