### ISSUE TITLE
html data-content becomes undefined

### ISSUE THREAD

**Issue by Strafos** [zenoamaro/react-quill#393]
Hi, I have a custom Inline comment component (using Semantic UI) which creates this html: 
```<p>
    <span class="ui" data-content="abc" data-position="right center">Official statistics say we are winning the War on Cancer. Cancer incidence rates, mortality rates, and five-year-survival
      rates have generally been moving in the right direction over the past few decades.</span>
  </p>
```
I save the html as a string. On load, I pass the string as `value` into React-Quill and `data-content` becomes "undefined":
```<p>
    <span class="ui" data-content="undefined" data-position="right center">Official statistics say we are winning the War on Cancer. Cancer incidence rates, mortality rates, and five-year-survival
      rates have generally been moving in the right direction over the past few decades.</span>
  </p>
```
Any ideas as to why this happens/what I could change to prevent this from happening?

#### React-Quill version 
- [x ] master

**Comment by alexkrolick** [comment]
You probably need a custom formatter registered with Quill:

- https://quilljs.com/docs/modules/
- https://github.com/zenoamaro/react-quill#custom-formats
- https://github.com/quilljs/quill
