### ISSUE TITLE
Move type definitions to DefinitelyTyped

### ISSUE THREAD

**Issue by alexkrolick** [zenoamaro/react-quill#395]
No maintainers update the typescript definitions directly and they are a frequent source of bugs, so I'd like to move them out of the repo to a 3rd party source. 

https://twitter.com/drosenwasser/status/1024474677798887424

We should end up with something like this: https://github.com/testing-library/react-testing-library/pull/437

- [ ] Create react-quill on DefinitelyTyped
- [ ] Remove local TS definitions
- [ ] Install DT package as a dependency to enable automatic type acquisition in TS/VSCode

**Comment by alexkrolick** [comment]
Related: #269 #277 #349 #510 #433 #490 #423 #510 #294 #350 #361 #347 #316 #420 #500 

https://github.com/zenoamaro/react-quill/issues?q=sort%3Aupdated-desc+label%3Atypescript

**Comment by vdh** [comment]
Could you either finish this export or pull #490? Because as is the types are just broken.

**Comment by alexkrolick** [comment]
The TS rewrite supercedes this ticket, closing. @vdh can you check out the beta release?

**Comment by vdh** [comment]
@alexkrolick Thanks, the v2 version solves the import issues I was having with the types inside the namespace
