### ISSUE TITLE
specify href target

### ISSUE THREAD

**Issue by bradrobertson** [zenoamaro/react-quill#40]
Not sure if this is a Quill question or react-quill. This isn't an issue but a question.

I just can't figure out how I'd apply `target="_blank"` by default to all links generated with `react-quill`. I can see the formats section, which I'd think I could do something like:

```javascript
formats = [
  "bold",
  {name: "link", tag: "a", type: "link", target: "_blank"}
];
```

But I obviously don't understand the quill api properly. Any help ?

**Comment by zenoamaro** [comment]
I think this is not supported by Quill yet.

It is being discussed in quilljs/quill#189, though it seems stalled by a "custom formats" milestone.

In the mean time you should be able to do it by post-processing the resulting html.

**Comment by bradrobertson** [comment]
ya that's what I've ended up doing. thx!
