### ISSUE TITLE
React 16.4 warnings Unsafe lifecycle methods 

### ISSUE THREAD

**Issue by dbenchi** [zenoamaro/react-quill#401]
When updating to React 16.4 It throws warnings because of the use of lifecycle methods that are unsafe for async rendering.

![screenshot from 2018-09-11 11-13-13](https://user-images.githubusercontent.com/6479928/45350297-baa5c680-b5b3-11e8-9f09-228179aaa6dd.png)

**Comment by zenoamaro** [comment]
ReactQuill v2 is now fully TypeScript and React16+, and uses no deprecated lifecycle methods anymore.

Please try the latest v2 beta. The upgrade should be drop-in.
