### ISSUE TITLE
React quill production build fails on uglifier

### ISSUE THREAD

**Issue by wsielskx** [zenoamaro/react-quill#405]
I'm having an issue with the production build of application and react-quill. The problem was mentioned a few times as an issue but none of the solutions worked in my case. 

Production build with uglifier applied ends with the message:

![image](https://user-images.githubusercontent.com/32566644/45741380-b69f2780-bbf7-11e8-9174-b49fa9b65db6.png)

Suggested solutions applied:
```
    module: {
            noParse: [
                /node_modules\/react-quill\/node_modules\/quill\/dist\/quill\.js/,
                /node_modules\/quill\/dist\/quill\.js/,
                /node_modules\/quill\/dist/
            ],
```

```
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');

...

new UglifyJsPlugin({
                sourceMap: true,
                compress: {
                    warnings: false
                }
            }),
```

Installed versions:
```
react@16.3.2
react-quill@1.3.1
uglifyjs-webpack-plugin@0.4.6
webpack@3.12.0
```

I've also tried to downgrade to the react-quill@1.2.6 but it was still causing the problems.

Any ideas for fixing this?

**Comment by alexkrolick** [comment]
Try using lib instead of dist in noParse

**Comment by wsielskx** [comment]
If you were thinking about something like this:

```
noParse: [
                /node_modules\/react-quill\/node_modules\/quill\/dist\/quill\.js/,
                /node_modules\/quill\/dist\/quill\.js/,
                /node_modules\/quill\/dist/,
                /node_modules\/quill\/lib/,
                /node_modules\/react-quill\/lib/,
            ],
```

nothing changed, still fails with the same issue.

**Comment by xujiahaoXiXi** [comment]
you finally resolve it？

**Comment by drelyn86** [comment]
I had the same issue and was able to resolve it by using the exact noParse value from the [README](https://www.npmjs.com/package/react-quill#bundling-with-webpack).

`noParse: /node_modules\/quill\/dist/`

This seems somehow related to #7

**Comment by wsielskx** [comment]
@xujiahaoXiXi no I didn't. I'll remove Quill from my project due to this error. Have no idea why #7 didn't work for me.
