### ISSUE TITLE
html to view and view to html doesn't work for tables

### ISSUE THREAD

**Issue by saurabh147sharma** [zenoamaro/react-quill#408]
Hi
Awesome rich text editor.
I'm facing an issue while I'm using source to view and view to source for tables.
I paste a table in editor but when I see the source view it was converted to a paragraph text.
I request you to please help me into this.
Here is the codepen which I'm following.

https://codepen.io/alexkrolick/pen/XgaVVX

**Comment by alexkrolick** [comment]
In general table support in Quill is limited. You can track progress upstream at https://github.com/quilljs/quill
