### ISSUE TITLE
Mobile browser is not showing the toolbar icons

### ISSUE THREAD

**Issue by zehawki** [zenoamaro/react-quill#419]
Hello, I just integrated react-quill with our website. Thank you for this amazing component that worked so seamlessly - better than I had expected. It's showing up and working just fine on a desktop browser:

![quill 1](https://user-images.githubusercontent.com/8095144/47624376-03084c00-db42-11e8-9599-f81b4f4e60de.PNG)

but totally weird on Android mobile browsers. Any help or clue to debug would be highly appreciated. I'm on Android 8.

1. This is webview inside our app:

![quill 2](https://user-images.githubusercontent.com/8095144/47624432-bcffb800-db42-11e8-8e59-b2f0d21eb7fc.jpg)

2. And this is in Firefox:

![quill 3](https://user-images.githubusercontent.com/8095144/47624485-38616980-db43-11e8-9122-2d6f5ff4628a.jpg)

Thank you.

**Comment by alexkrolick** [comment]
Sounds like a missing CSS stylesheet

**Comment by zehawki** [comment]
>
> Sounds like a missing CSS stylesheet

Thank you Alex. Yup, thats exactly what it was. I had put http://cdn.quilljs by mistake and it doesnt do a redirect to https.
