### ISSUE TITLE
Text-align options are not triggering

### ISSUE THREAD

**Issue by prosenjitchy** [zenoamaro/react-quill#422]
I just have added this package into my react project. I also added 'text-align' options into **modules** prop of React-quill. But the problem is that, I can see the buttons but these are not triggering (or working) after I click on them.

**Here is the [Codepen link](https://codepen.io/bonnopc/pen/ZmEZZE).**

I have defined the variable, **modules** like,
`modules = {toolbar: [
         [{ 'header': [1, 2, 3, false] }],
         ['bold', 'italic', 'underline'],
         [{ align: '' }, { align: 'center' }, { align: 'right' }, { align: 'justify' }],
         [{'list': 'ordered'}, {'list': 'bullet'}, {'indent': '-1'}, {'indent': '+1'}],
         ['link']
]};`

and declared the prop as,
`<ReactQuill value={this.state.text}
                            theme="snow"
                            modules={this.modules}
                            formats={this.formats}
                            onChange={this.handleChange}/>`

Please help..

**Comment by mdmasumbillah** [comment]
Solved it. Set `align` in format.

`
  formats = [
    'header',
    'bold', 'italic', 'underline', 'strike', 'blockquote',
    'list', 'bullet', 'indent',
    'link', 'image', 'align'
  ]
`

**Comment by KumarAbhirup** [comment]
Hey, that isnt working. I am having the exact problem. :-(

**Comment by sohebmu** [comment]
I tried and it is working.

**Comment by artem-solovev** [comment]
In order to get it work i placed settings into
- toolbar: `[{ align: '' }, { align: 'center' }, { align: 'right' }, { align: 'justify' }],`
- formats: `'align'`

Full component setting looks like

```
                       <ReactQuill
				value={value}
				theme={'snow'}
				defaultValue={defaultValue}
				/* style={{
					all: 'unset',
				}} */
				onChange={this.onChangeContent}
				modules={{
					toolbar: [
						[{ 'header': [] }, { 'font': [] }],
						[{ size: [] }],
						['bold', 'italic', 'underline', 'strike', 'blockquote'],
						[
							{ 'list': 'ordered' },
							{ 'list': 'bullet' },
							{ 'indent': '-1' },
							{ 'indent': '+1' },
						],
						['link', 'image', 'video'],
						['clean'],
						[{ 'color': [] }, { 'background': [] }],
						[{ align: '' }, { align: 'center' }, { align: 'right' }, { align: 'justify' }],
						// [],
					],
					clipboard: {
						// toggle to add extra line breaks when pasting HTML:
						matchVisual: false,
					},
					// htmlEditButton,
					htmlEditButton: {
						// logging, default:false
						debug: true,

						/**
						 * Custom message to display in the editor, default:
						 * Edit HTML here, when you click "OK" the quill editor's
						 * contents will be replaced
						*/
						msg: 'Edit the content in HTML format',

						// Text to display in the OK button, default: Ok,
						okText: 'Ok',

						// Text to display in the cancel button, default: Cancel
						cancelText: 'Cancel',

						// Text to display in the toolbar button, default: <>
						buttonHTML: '&lt;&gt;',

						// Text to display as the tooltip for the toolbar button, default: Show HTML source
						buttonTitle: 'Show HTML source',

						/**
						 * Show the HTML with syntax highlighting.
						 * Requires highlightjs on window.hljs (similar to Quill itself), default:
						 * false
						*/
						syntax: false,

						// a string used to select where you want to insert the overlayContainer, default: null (appends to body),
						prependSelector: 'div#myelement',
						editorModules: {}, // The default mod
					},
				}}
				formats={[
					'header', 'font', 'size', 'color',
					'bold', 'italic', 'underline', 'strike', 'blockquote',
					'list', 'bullet', 'indent',
					'link', 'image', 'video',
					'align',
				]}
				style={{
					backgroundColor: '#fff',
					color: '#000',
					minHeight: '300px',
				}}
			/>


```
