### ISSUE TITLE
Entering a number with a dot (eg. "30.") creates an empty sorted list instead of "30. "

### ISSUE THREAD

**Issue by natterstefan** [zenoamaro/react-quill#427]
### Issue description

![screen capture on 2018-11-23 at 10-14-51](https://user-images.githubusercontent.com/1043668/48935678-c2b1a900-ef08-11e8-859b-08b288d652ee.gif)

That title explains the main issue (not sure if it's just an issue on our side or a bug of the component), as [described here as well](https://github.com/quilljs/quill/issues/2408):

1. Visit our [lovely-editor storybook](https://lovely-editor.netlify.com/?selectedKind=Editors%2FEditorQuill&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)
2. enter "30."
3. now press space again

Now I would expect to get "30. ". But instead I get an unsorted list with no initial value.

Here's the [source code of the editor](https://github.com/lovelysystems/lovely-editor/blob/develop/src/components/editor-quill/index.js) and here the [storybook story](https://github.com/lovelysystems/lovely-editor/blob/develop/src/components/editor-quill/index.stories.js).

### FAQ

**How do I access the wrapped Quill instance?**

I do not access it as described in your Readme. I simply use the `onChange` method to receive and react to changes.

**Is there a bug in Quill?**

I do not know (yet). That is the reason why I'll open another issue there as well.

#### React-Quill version 
- 1.2.7

_Thank you for your help!_

**Comment by alexkrolick** [comment]
Related: https://github.com/quilljs/quill/issues/2408

This looks default Quill behavior

**Comment by natterstefan** [comment]
Oh yes, sorry. Forgot to close it here. Thank you @alexkrolick
