### ISSUE TITLE
Blank editor when loading from api

### ISSUE THREAD

**Issue by pblUSA** [zenoamaro/react-quill#429]
Using redux to make an in the component did mount I  api call, I retrieve an entity that I will use to pre-populate the editor with html stored on my database that was initially edited by the user and retrived using `this.myRef.current.state.value` but the editor is blank unless i hardcode the html in the defaultValue field like this `defaultValue={"<p>sad oajsldn </p>"}`.

Doesn't make sense to me why I can't bind to the mediaentity.description. Is this a bug maybe?

```

  private modules = {
    toolbar: {
      container: [
        [{ header: [1, 2, false] }],
        ['bold', 'italic', 'underline', 'strike', 'blockquote'],
        [{ list: 'ordered' }, { list: 'bullet' }, { indent: '-1' }, { indent: '+1' }],
        ['link', 'image'],
        ['clean']
      ],
      handlers: {
        // image: this.uploadImage
      }
    }
  };
<ReactQuill
                    modules={this.modules}
                    formats={this.formats} placeholder={'Enter Text...'}
                    ref={this.myRef} defaultValue={mediaEntity.description} />
```

[Update]:
This is how I am now updating the content of the editor but it is still blank. Not sure why this is the case
```
  updateEditorContent = response => {
    console.log(this.myRef.current);
    this.myRef.current.setState({
      value: this.props.mediaEntity.description
    });
    this.myRef.current.renderEditingArea()
    //this.myRef.current.setEditorContents(this.myRef.current.getEditor(), this.props.mediaEntity.description);
  }
```
[Quill issues page]: 
https://github.com/quilljs/quill/issues

#### React-Quill version 
- [ +] 1.3.2

**Comment by alexkrolick** [comment]
I'm not sure why you would need to call .setState from a ref - this seems like a data flow issue in your application and not the library
