### ISSUE TITLE
Overide BaseTheme

### ISSUE THREAD

**Issue by paolavness** [zenoamaro/react-quill#439]
Hi there,
I'm using react-quill in my react app and trying to extend Quill's base, snow or bubble themes to create a custom theme but running into errors and not sure if there is something I've missed in my implementation or what.

Below is the code for the `extend`. 
```
import {Quill} from "react-quill";
const BubbleTheme = Quill.import('themes/bubble')
const BubbleTooltip = Quill.import('themes/bubble')

class DreamTheme extends SnowTheme {
  constructor (quill, options) {
    super(quill, options)
  }

  extendToolbar (toolbar) {
    super.extendToolbar(toolbar)
    this.tooltip = new DreamTooltip(this.quill, this.options.bounds); //error line
    this.tooltip.root.appendChild(toolbar.container);
  }
}

class DreamTooltip extends SnowTooltip {}

DreamTooltip.TEMPLATE = [
  '<span class="ql-tooltip-arrow"></span>',
  '<div class="ql-tooltip-editor">',
    '<input type="text" data-formula="e=mc^2" data-link="https://myurl.com" data-video="Embed URL">',
    '<a class="ql-close"></a>',
  '</div>'
].join('');

export { DreamTooltip, DreamTheme as default }
```

I've tried extending `snow`, `bubble` and `base`.  `snow` and `bubble` give the error `TypeError: Cannot read property 'toolbar' of undefined`, referring to the line noted in the code above.

When extending `base`, the error is `quill Cannot import themes/base. Are you sure it was registered?`

I've also tried creating the custom theme using Quill.js, in the same way as described [here](https://stackoverflow.com/questions/44625868/es6-babel-class-constructor-cannot-be-invoked-without-new). However this creates webpack issues which when resolved, (in the same way described in the stackoverflow) break react-quill, understandably.

Have I missed something in my code or is this possibly a bug in `react-quill`? 

Thanks.

**Comment by paolavness** [comment]
D'oh, fixed this - was sending through `this.options.bounds` on the error line. Should have been `this.options`

**Comment by paolavness** [comment]
D'oh, fixed this - was sending through `this.options.bounds` on the error line. Should have been `this.options`

**Comment by nesh325** [comment]
> D'oh, fixed this - was sending through `this.options.bounds` on the error line. Should have been `this.options`

I know it's been a while. But do you mind sharing how you were to then use this extended theme in react-quill?

**Comment by KennethWise** [comment]
I have same issue "When extending base, the error is quill Cannot import themes/base". Is there any way to solve it?
