### ISSUE TITLE
TabIndex is set to both container and editor

### ISSUE THREAD

**Issue by frysztak** [zenoamaro/react-quill#442]
I encountered an issue when using two instances of Quill in my app. TabIndex is set to both outer `.ql-container` and inner `.ql-editor` divs, which means that pressing tab doesn't focus the actual editor, but its container. See codepen [here](https://codepen.io/frysztak/pen/EGXoaY).

I'll provide a pull request to fix this soon.

#### React-Quill version 
- 1.3.6

**Comment by rwarford** [comment]
I'm surprised this hasn't been resolved yet.  I too have hit the same issue.  I would love to see the fix merged.

**Comment by zenoamaro** [comment]
Merged in master. Expect a beta release soon
