### ISSUE TITLE
Running npm install for the dev dependencies fails on Node v4.2.1

### ISSUE THREAD

**Issue by jacktrades** [zenoamaro/react-quill#45]
Older versions of jsdom have [issues building on Node 4.x](https://github.com/tmpvar/jsdom/issues/1243).  Upgrading the [jsdom dependency](https://github.com/zenoamaro/react-quill/blob/d68d530ab6df06a4073b30d3393785fd5dacd673/package.json#L46) to `"jsdom": "^7.0.1",` fixes the problem.

However, it seems that as of 7.0.0, [jsdom only supports Node 4.x or newer](https://www.npmjs.com/package/jsdom), and apparently the 3.x series of jsdom (which does support < Node 4.x) [is now unmaintained](https://github.com/tmpvar/jsdom/tree/3.x).

Since I'm new to this project, and don't know what build environments you need to support, I'll leave the fix for this one up to the maintainers.

**Comment by zenoamaro** [comment]
This should not be a problem anymore.

Feel free to reopen this if you still encounter this issue.
