### ISSUE TITLE
Text Overlaping Quill toolbar

### ISSUE THREAD

**Issue by kpmakwana** [zenoamaro/react-quill#453]
Quill toolbar is geeting overlaped by other text .

I used Quill Editor for Two elements of same Page when I tried Editting first Text toolbar appiered but most of the part of toolbar was overlaped by text beside that.

![screenshot 2019-02-13 at 4 52 32 pm](https://user-images.githubusercontent.com/37105330/52708391-fce29200-2faf-11e9-9ea7-dde0d0dbc215.png)

What I can do to make quill float on every elements??

**Comment by pReya** [comment]
Have you tried to solve this with CSS using the [z-index property](https://developer.mozilla.org/en-US/docs/Web/CSS/z-index)?
