### ISSUE TITLE
how to remove the <p> and wrap it in <div> instead. new line creating extra line break

### ISSUE THREAD

**Issue by paigeflourin** [zenoamaro/react-quill#461]
my text just gets wrapped in <p> every time i hit enter which isnt what i wanted the result i wanted is

test1
test2
test3

but when i save it backend i am getting:

test1

test2

test3

i have read [here](https://github.com/quilljs/quill/issues/861) to use this: 

```
var Block = Quill.import('blots/block');
Block.tagName = 'DIV';
Quill.register(Block, true);
```

but i am not sure how to implement this in my current solution:

```
 <ReactQuill
            value={this.props.value}
            onChange={this.handleChange}
            onBlur={this.setProps}
            modules={this.modules}
            formats={this.formats}
          />
```

**Comment by IssaafKattan** [comment]
How did you end up solving this?

**Comment by cidylle** [comment]
Same here. How was this resolved?

**Comment by IssaafKattan** [comment]
I worked around it with css
```
p {
    margin-top: 0;
    margin-bottom: 0;
}
```
