### ISSUE TITLE
[QUESTION] How to paste image from clipboard (screenshot)

### ISSUE THREAD

**Issue by buddythumbs** [zenoamaro/react-quill#468]
Thanks for filing an issue! 
Just spun up a vanilla version of this and would like to know if it is possible to paste an image from the clipboard which has been created from screenshot?

https://codesandbox.io/s/43nxwx8nn4

I have checked the issues and nothing popped up so I'm sorry if this is a duplicate!

#### React-Quill version 
- [ ] master
- [ ] 0.4.1
- [ ] 1.0.0-beta-1
- [ ] 1.0.0-beta-2
- [ ] 1.0.0-beta-3
- [ ] 1.0.0-beta-4
- [ ] 1.0.0-beta-5
- [ ] 1.0.0-rc-1
- [ ] 1.0.0-rc-2
- [ ] 1.0.0-rc-3
- [ ] 1.0.0
- [x] 1.1.0
- [x ] Other (fork)
 version 1.3.3

**Comment by alexkrolick** [comment]
You should be able to do that with the clipboard module enabled

**Comment by buddythumbs** [comment]
I can paste text but not images, is there something else I need to enable to paste image?

**Comment by karpkarp** [comment]
same issue here. Pasting images from other websites is fine. But I can't paste images from screenshots and local files.

**Comment by syzygy56** [comment]
> I can paste text but not images, is there something else I need to enable to paste image?

has anybody been able to get this to work

**Comment by shark-Ron** [comment]
ikkdieijhfaw

**Comment by luluhoc** [comment]
any updates on it?

**Comment by alexkrolick** [comment]
Can you try a plugin. Here's one:

https://www.npmjs.com/package/quill-right-image-upload

**Comment by alexkrolick** [comment]
Closing as this is handled by Quill or a plugin
