### ISSUE TITLE
Multiple editors and one toolbar

### ISSUE THREAD

**Issue by LitvinAndrey** [zenoamaro/react-quill#469]
I need to create multiple editors on page with one toolbar. When text selected in one of editors I need that buttons should be active. All handlers work with only active editor.

**Comment by houshuang** [comment]
We had this issue, and we used cuid to generate a uuid in the constructor, and then pass that to the toolbar handler container. You can see in github.com/houshuang/react-demo.

**Comment by nurbek-ab** [comment]
I managed to do this mostly with CSS. Hide all toolbars with css but show the first one by default. Then when an editor gets focus add active class to it and display its toolbar or increase its z-index.

**Comment by maxfahl** [comment]
Hey guys!

I've created a sample React app to show how I resolved this issue. Note that I'm not using the react-quill wrapper, but I thought someone might be interested in my solution for this anyway. This is basically how it works:

> I'm creating one instance of Quill, using a custom toolbar positioned at the top. The editor element is placed in a temporary, hidden, container. When the user double clicks any of the three text containers (Editables), the editor element will be transplanted form the temporary container to a new location inside the Editable. If a user hits the escape key, the Editable will be deactivated, moving the editor element back to the temporary container.

You can test it here: https://codesandbox.io/s/hungry-pine-o8oh9?file=/src/App.js
GitHub repo: https://github.com/maxfahl/Quill-Edit-Multiple

Feel free to use the code however you'd like.

**Comment by sahajkedia** [comment]
> Hey guys!
> 
> I've created a sample React app to show how I resolved this issue. Note that I'm not using the react-quill wrapper, but I thought someone might be interested in my solution for this anyway. This is basically how it works:
> 
> > I'm creating one instance of Quill, using a custom toolbar positioned at the top. The editor element is placed in a temporary, hidden, container. When the user double clicks any of the three text containers (Editables), the editor element will be transplanted form the temporary container to a new location inside the Editable. If a user hits the escape key, the Editable will be deactivated, moving the editor element back to the temporary container.
> 
> You can test it here: https://codesandbox.io/s/hungry-pine-o8oh9?file=/src/App.js GitHub repo: https://github.com/maxfahl/Quill-Edit-Multiple
> 
> Feel free to use the code however you'd like.

You're using quill, i want to use React-quill

**Comment by charusharma0** [comment]
-  #``[](u
 @/
![image](https://github.com/user-attachments/assets/2c84216d-a8c3-460f-858a-403ce52b9754)
![pinkflower](https://github.com/user-attachments/assets/b63c58d3-a753-4d06-a7f5-93ad3b34975a)
![pinkflower](https://github.com/user-attachments/assets/cfe20e60-7403-4792-b7dd-b09765f19c9b)
![image](https://github.com/user-attachments/assets/0539fb27-037d-48e2-b937-6eade9a1bfb4)
rl)
