### ISSUE TITLE
Passing a boolean to the styles prop warns about incorrect type

### ISSUE THREAD

**Issue by jacktrades** [zenoamaro/react-quill#47]
As recommended in #31 as well as the [Quill docs](http://quilljs.com/docs/configuration/#styles), passing `false` to the `styles` prop produces the following warning:

    Warning: Failed propType: Invalid prop `styles` of type `boolean` supplied to `Quill`, expected `object`. Check the render method of `Quill`.

**Comment by jacktrades** [comment]
Whoops, it looks like there's already a pull request open for this (#34).  Since it's still not merged, I'll leave this open.

**Comment by zenoamaro** [comment]
Merged, now `object` or `false` can be passed to `style`.
