### ISSUE TITLE
How to set it up with Formik?

### ISSUE THREAD

**Issue by nithinkashyapn** [zenoamaro/react-quill#473]
Thanks for the wonderful editor.

I am trying to set it up with `Formik` but it's not working. Can anyone help me with this.

I tried using Formik's `setFieldValue()` also via React-Quill's `onChange()` but that also is not working.

My basic setup looks like this

```
<Field
	name="designation"
	value={this.props.values.designation}
	render={({ field /* _form */ }) => (
		// <input {...field} placeholder="designation" />
		<ReactQuill
			{...field}
		/>
	)}
/>
```

`<input>` works but `<ReactQuill />` fails.

Thank you.

**Comment by bologer** [comment]
Also would be useful to know.

**Comment by alexkrolick** [comment]
May be able to debug if you provide a Codepen or Codesandbox link

**Comment by bologer** [comment]
@alexkrolick  here it is - https://codesandbox.io/s/zlxn4mr07m

**Comment by bologer** [comment]
@nithinkashyapn, @alexkrolick so far I have the following solution: 

```js 
...
{({isSubmitting, setFieldValue}) => (
    <Form>
        ...
        <Field render={({ field}) => {
            return <QuillEditor value={field.value.editor} onChange={(value) => {
                setFieldValue('editor', value)
            }}/>
        }}/>
    </Form>
)}
...
```

**Comment by alexdunne** [comment]
https://github.com/jaredpalmer/formik/issues/1383#issuecomment-493934980

```
<Formik initialValues={{ content: '' }}>
    <Field name="content">
        {({ field }) => <ReactQuill value={field.value} onChange={field.onChange(field.name)} />}
    </Field>
</Formik>
```

**Comment by christiantigre** [comment]
I use 
<ReactQuill
                          theme={"snow"}
                          name={"contrato"}
                          id={"contrato"}
                          value={values.contrato}
                          modules={this.props.modules}
                          onChange={event => setFieldValue("contrato", event)}
                          onBlur={() => setFieldTouched("contrato", true)}
                          valid={!errors.estado}
                          invalid={touched.estado && !!errors.estado}
                          autoFocus={true}
                        />

**Comment by nithinkashyapn** [comment]
Thanks everyone. Closing the issue.

**Comment by abdoul-guy** [comment]
thanks everyone
