### ISSUE TITLE
If the HTML string contains ID, Class and Style, it does not render ID and Class rather just inline style.

### ISSUE THREAD

**Issue by reeversedev** [zenoamaro/react-quill#474]
Unable to render id and classes for my html.

**Comment by abarrafo** [comment]
Do you mean that your HTML tag attributes are being dropped by quill js? That is, if you pass in `<p id="myId">Some editor line</p>` when you view your attributes within the editor they are not there `<p>Some editor line</p>`?

**Comment by dpistoleKUBRA** [comment]
This seems to be the case for us `<p style="margin-left: 20px">` goes in but `<p>` comes out.

**Comment by abarrafo** [comment]
This has nothing to do with React-quill really, this is the typical behavior for QuillJs. They basically normalize html and will strip everything out. If you want to be able to keep html attributes, you need to extend a block, then handle the attributes manually.
