### ISSUE TITLE
Can I save the quilljs document to some sort of JSON format to save in Mongodb?

### ISSUE THREAD

**Issue by LucasRios95** [zenoamaro/react-quill#479]
Thanks for filing an issue! 

If at all possible, please provide a Codepen to demonstrate the problem you're having with React Quill. Here's a [template] to get you started.

[template]: 
https://codepen.io/pen?template=xgyOXQ

### FAQ

**How do I access the wrapped Quill instance?**
See the [instance methods] and [API] documentation.

[instance methods]:
https://github.com/zenoamaro/react-quill#methods

[API]:
https://github.com/zenoamaro/react-quill#api-reference

**Is there a bug in Quill?**
Please refer to the [Quill issues page].

[Quill issues page]: 
https://github.com/quilljs/quill/issues

#### React-Quill version 
- [ ] master
- [ ] 0.4.1
- [ ] 1.0.0-beta-1
- [ ] 1.0.0-beta-2
- [ ] 1.0.0-beta-3
- [ ] 1.0.0-beta-4
- [ ] 1.0.0-beta-5
- [ ] 1.0.0-rc-1
- [ ] 1.0.0-rc-2
- [ ] 1.0.0-rc-3
- [ ] 1.0.0
- [ ] 1.1.0
- [ ] Other (fork)

**Comment by alexkrolick** [comment]
The `onChange` prop is called with a number of arguments, including the Quill delta format which is a JS object.

**Comment by zenoamaro** [comment]
You can get a delta representing a full document by calling `getContents()` on the fourth argument of the `onChange` handler. See [ReactQuill onChange prop](https://github.com/zenoamaro/react-quill#props).
