### ISSUE TITLE
Change editor template

### ISSUE THREAD

**Issue by bologer** [zenoamaro/react-quill#481]
Hi, 

Could anybody suggest where to find way to change template of the editor to such form: 

![image](https://user-images.githubusercontent.com/9879933/56315050-0c6c8b80-6157-11e9-9857-974fd70e99ed.png)

by default it is as follows: 

![image](https://user-images.githubusercontent.com/9879933/56315068-14c4c680-6157-11e9-9cd8-4c688b187b21.png)

Thanks in advance.

**Comment by bologer** [comment]
Anyone?

**Comment by bologer** [comment]
@alexkrolick any idea? I would really appreciate it.

**Comment by alexkrolick** [comment]
The custom toolbar is deprecated, and Quill itself attaches the DOM node, so off the top of my head it seems like the next things to look into a) check the Quill docs for config options related to the toolbar DOM node b) consider using CSS to reorder the .ql-toolbar and .ql-editor classes

**Comment by bologer** [comment]
@alexkrolick thank you for suggestions!
