### ISSUE TITLE
why not support emoji?

### ISSUE THREAD

**Issue by leeseean** [zenoamaro/react-quill#484]
why not support emoji?

**Comment by vgeyvandov** [comment]
@leeseean here is a third party plugin in the meantime: https://github.com/contentco/quill-emoji

**Comment by vgeyvandov** [comment]
@leeseean here is a third party extension in the meantime: https://github.com/contentco/quill-emoji

**Comment by zenoamaro** [comment]
The editor itself supports emoji content without issues, as far as I can see. 

Whether an emoji button should be included, is a question for upstream [Quill](https://quilljs.com), and you should be able to use the extension @vgeyvandov posted in ReactQuill without issues. 

Please reopen if that's not the case. Cheers
