### ISSUE TITLE
Does react-quill support adding padding or margin styles?

### ISSUE THREAD

**Issue by lizhongkun** [zenoamaro/react-quill#488]
The project needs to add a variety of custom styles in the rich text editor. I want to ask the gods, react-quill support does not support adding margin and padding. Please let me know. Thank you very much!

**Comment by alexkrolick** [comment]
You can create custom Quill blots (Parchment modules) and create a custom toolbar:

- https://quilljs.com/docs/modules/
- https://github.com/zenoamaro/react-quill#custom-formats
- https://github.com/quilljs/quill
- Codepen https://codepen.io/pen?template=xgyOXQ
- Custom toolbar Codepen https://codepen.io/pen?template=gmroPj
- https://www.npmjs.com/search?q=quill%20mentions&page=1&ranking=optimal
