### ISSUE TITLE
Google Translate On Not Able to write in the text area.

### ISSUE THREAD

**Issue by Jaskaran121** [zenoamaro/react-quill#494]
Whenever google translation is turned on, I am not able to write in the text box area.
This issue can be reproduced by clicking on the following code sandbox repo link and then follow the steps as given below: -
1. Click on the repo link https://codesandbox.io/s/w2zn900qx7
2. Open the browser window in new tab i.e https://w2zn900qx7.codesandbox.io/
3. Right click on the browser and select translate to English(i.e change to any other language for say if your browser current language is English change it to a language other than English for e.g Spanish).

Then the following problem occurs I cannot write in the text area, a supporting gif is attached.
Please open the below URL:-
https://user-images.githubusercontent.com/35613378/60298997-b441ca80-98f9-11e9-9901-56e3fc1e004f.gif

**Comment by alexkrolick** [comment]
Does this occur on a plain Quill app as well?

Please try it on https://quilljs.com/

**Comment by Jaskaran121** [comment]
yes the same problem comes with the Quill app too... i tried using this codepen https://codepen.io/quill/pen/KzZqZx from https://quilljs.com/

**Comment by Jaskaran121** [comment]
yeah and this issue is already reported on Quill [#2286](https://github.com/quilljs/quill/issues/2286) and its workaround is <span class="notranslate"> </span> which will turn off the translation for the editor.But this is only a partial solution,which will not cause any errors but still this problem needs to be addressed.
