### ISSUE TITLE
dangerouslySetInnerHTML error

### ISSUE THREAD

**Issue by asok** [zenoamaro/react-quill#5]
So I've tried to use the component. But I get the error about the wrong usage of the property `dangerouslySetInnerHTML`.
I've setup an app showing [this](https://github.com/asok/react-quill-bug).
You can just follow the README to fire it up and see the error in the browser's console.

Any idea what might be wrong?

**Comment by zenoamaro** [comment]
Here, apparently feeding a null value to the editor was triggering the assertion.

I've defaulted that to an empty string. This should fix your issue, but let me know if otherwise.
