### ISSUE TITLE
When loading an image the original image's Orientation is not respected (used)

### ISSUE THREAD

**Issue by FoxyWolfy** [zenoamaro/react-quill#502]
When loading an image the original image's EXIF Orientation is not respected (used).

EXIF image metadata

References: 
https://github.com/exif-js/exif-js

https://stackoverflow.com/questions/43676070/quilljs-editor-rotate-upload-image-inside-editor-or-before-upload

**Comment by alexkrolick** [comment]
This sounds like an upstream issue in Quill

- https://quilljs.com/docs/modules/

Does it reproduce in plain Quill?

**Comment by FoxyWolfy** [comment]
Yes, it reproduces in the Quill playground.  But only with "portrait" images.  Landscape images are fine.  
Could it be Quill is rotating the portrait images to fit?

**Comment by alexkrolick** [comment]
I am not sure what code we would change here to fix this. Seems like it's fully in upstream.
