### ISSUE TITLE
Cmd+Z completely removes all text?

### ISSUE THREAD

**Issue by MitchEff** [zenoamaro/react-quill#511]
I've just gotten a very angry message from one of my users saying pressing Cmd+Z (undo) on a prepopulated Quill instance just, deletes all the text.

He's right. My app has a 'notes' section - I can open any note, press Cmd+Z and Quill just like, deletes everything.

Why on earth does it do that, and is there a way to prevent it?

**Comment by MitchEff** [comment]
Turns out you need to clear your editor's history after mounting, for whatever reason.

**Comment by k-lusine** [comment]
@MitchEff Could you provide some code, please?

**Comment by alexneo2003** [comment]
having same issue
after write this config all fixing
https://quilljs.com/docs/modules/history/#useronly
