### ISSUE TITLE
Question: is it possible to implement new line in editor.

### ISSUE THREAD

**Issue by mindaugasnakrosis** [zenoamaro/react-quill#513]
Is it possible to implement a new line `<br />` on shift+enter like in general editing?

At the moment all new lines are wrapped in paragraphs which add top and bottom margin which is fine. 

How do I achieve adittional functionality of new line with `br` tag?

**Comment by mindaugasnakrosis** [comment]
@alexkrolick any ideas?

**Comment by mindaugasnakrosis** [comment]
Solved it like this:

```
const Delta = Quill.import("delta");
const Break = Quill.import("blots/break");
const Embed = Quill.import("blots/embed");

const lineBreakMatcher = () => {
  let newDelta = new Delta();
  newDelta.insert({ break: "" });
  return newDelta;
};

class SmartBreak extends Break {
  length() {
    return 1;
  }
  value() {
    return "\n";
  }

  insertInto(parent, ref) {
    Embed.prototype.insertInto.call(this, parent, ref);
  }
}

SmartBreak.blotName = "break";
SmartBreak.tagName = "BR";
Quill.register(SmartBreak);

<ReactQuill
  modules={{
    clipboard: {
      matchers: [["BR", lineBreakMatcher]],
      matchVisual: false
    },
    keyboard: {
      bindings: {
        linebreak: {
          key: 13,
          shiftKey: true,
          handler: function(range) {
            const currentLeaf = this.quill.getLeaf(range.index)[0];
            const nextLeaf = this.quill.getLeaf(range.index + 1)[0];
            this.quill.insertEmbed(range.index, "break", true, "user");
            // Insert a second break if:
            // At the end of the editor, OR next leaf has a different parent (<p>)
            if (nextLeaf === null || currentLeaf.parent !== nextLeaf.parent) {
              this.quill.insertEmbed(range.index, "break", true, "user");
            }
            // Now that we've inserted a line break, move the cursor forward
            this.quill.setSelection(range.index + 1, Quill.sources.SILENT);
          }
        }
      }
    }
  }}
/>
```

**Comment by oleksii-lyhun** [comment]
@mindaugasnakrosis your code just changing caret position. this.quill.insertEmbed(range.index, "break", true, "user"); not working for me! Can you help me🙏 ?

**Comment by mylesdawson** [comment]
For some reason @mindaugasnakrosis's solution did not work for me. Here is an alternate solution for anyone else stuck in the same scenario:

[React-Quill Shift+Enter](https://codesandbox.io/s/optimistic-sea-dsb71?file=/src/App.js)

The only problem is that after pressing enter, backspace has to be pressed twice to return to the previous line. If anyone has a solution for that please let me know!

**Comment by boris-petrov** [comment]
@mindaugasnakrosis - we're using your solution and it works pretty well, thank you!

However, there is a specific case where we get an exception from Quill. To reproduce - check [this](https://codepen.io/kamenf/pen/wvJgGbG) CodePen - copy the text from above in the Quill editor below. That leads to a `Cannot read property 'mutations' of undefined` somewhere deep in Quill's code (check the console). Any ideas why that is and how to fix it?

**Comment by robozb** [comment]
@mindaugasnakrosis Thank you so much! Your solution is worked for me!

**Comment by maxfahl** [comment]
> However, there is a specific case where we get an exception from Quill.

I'm getting this as well on occasions. This breaks the entire editor. I've tried finding a working solution for this shift+enter issue for a long time now, and have tried about 6 different solutions. None of them works entirely correct.

So sad the Quill devs doesn't want to help with this.

**Comment by jonny-xhl** [comment]
Worked for me. Thanks.

**Comment by herrbasan** [comment]
This is such a hacky solution, if one could call it a solution at all. I guess the problem is that the author didn't anticipate this while constructing the inner logic of the project, so it probably isn't trivial to add this in a robust manner. Unfortunately the project i'm working on requires this functionality so i'm giving up on Quill for now.

**Comment by lkalinowski** [comment]
This workaround stopped working from 2.0.
Do you have a workaround for 2.0?
