### ISSUE TITLE
class / classname & other react formats

### ISSUE THREAD

**Issue by Cobwebster** [zenoamaro/react-quill#527]
Why does a react module spit out html markup that doesn't fit the JSX scheme?

Aka it spits out "class" and not "className", images don't have else closing tags on base64.

Is there a way to enable this and why isn't it  on be default if its built for react?

**Comment by alexkrolick** [comment]
The DOM nodes created by quill are not controlled by React

**Comment by Cobwebster** [comment]
> The DOM nodes created by quill are not controlled by React

So is there a way to convert it? Why is reeact quill a thing for react if it spits out invalid html for it? Like it just spams my console with errors. really confused as to why its made for react if what it produces is just gonna error on react pages.
