### ISSUE TITLE
following hyperlink brings to improper URL

### ISSUE THREAD

**Issue by jaagaard01** [zenoamaro/react-quill#529]
I'm not sure if this just an issue I'm having or not but when I'm using the hyperlink button say google.com it attaches that to the end of my local env. Brings me to localhost:3000/www.google.com. I replicated it on the sandbox for quill. 

Basically following the hyperlink isnt bringing me to the proper url. Hope I didnt make that more confusing than it needed to be.

**Comment by DanielNgozika** [comment]
Hi @jaagaard01, add the protocol, for example, https://google.com. This should now correctly open the link in a new tab.

**Comment by jaagaard01** [comment]
@DanielNgozika Sorry about that, yeah the protocol should be exactly like you stated above.

hyperlinking [https://google.com](url) inside the editor should open a new tab and bring you to the proper URL

**Comment by jaagaard01** [comment]
@DanielNgozika thanks for the clarification! Is there anyway to populate that beforehand to make it more user friendly? or anyway to add it on after the fact?

**Comment by FrederickEngelhardt** [comment]
Most users don't know about adding https:// before their urls. We should assume that many will freehand a url and omit the https:// thoughts on opening a ticket to resolve this issue?

**Comment by jaagaard01** [comment]
@FrederickEngelhardt That is exactly what I originally thought, I'm figuring for my use case most people using the app I'm working on will more than likely just copy and paste urls which works perfectly.

**Comment by zenoamaro** [comment]
This is a behavior of the Quill editor. While I agree with your suggestions, I can't implement them in ReactQuill. Please open a ticket here: https://github.com/quilljs/quill/issues

**Comment by heyalexchoi** [comment]
You can prepend `http` to urls for your users:


```
import Quill from 'quill'
const Link = Quill.import('formats/link');
Link.sanitize = function(url) {
  // quill by default creates relative links if scheme is missing.
  if (!url.startsWith('http://') && !url.startsWith('https://')) {
    return `http://${url}`
  }
  return url;
}
```

**Comment by Puspendert** [comment]
@jaagaard01 Did you find a proper solution to this?

**Comment by samarendramajhi** [comment]
For appending http with the selected text and react quill editor we can use a custom handler of the tool bar for link button as below.
import ReactQuill, { Quill } from "react-quill"; // import Quill to use in the custom handler
Get the selected text from the quill editor and prefix http with the selected text.
use below module toolbar object as module props.

 toolbar: {
      handlers: {
        link: function(value) {
          const selection = this.quill.getSelection();

          if (selection.length > 0) {
            //append selected text with http prefix for link
            const selectedContent = this.quill.getContents(selection.index, selection.length);
            const tempContainer = document.createElement("div");
            const tempQuill = new Quill(tempContainer);
            tempQuill.setContents(selectedContent);
            const selectedText = tempContainer.querySelector(".ql-editor").innerText;
            let tooltip = this.quill.theme.tooltip;
            tooltip.edit("link", "http://" + selectedText);
          }
        },
      },
      container: [
        [{ size: [] }],
        ["bold", "italic", "underline", "strike", "blockquote"],
        [{ align: [] }],
        [{ list: "ordered" }, { list: "bullet" }, { indent: "-1" }, { indent: "+1" }],
        ["link"],
        ["clean"],
      ],
    },
  };

**Comment by panosjapan7** [comment]
I'm doing this before I send the message to backend
`const prependHttpToLinks = message.replace(
    /href="(?!http:\/\/|https:\/\/)(.*?)"/g,
    'href="https://$1"'
  )`
  and then I send to backend `prependHttpToLinks` instead of `message`.
