### ISSUE TITLE
A ton of warning in browser console

### ISSUE THREAD

**Issue by Ben07** [zenoamaro/react-quill#55]
I use react-quill,it works nice but as title said.I get lots of warnings when I use react-quill with material-ui. material-ui has fixed it so I hope react-quill will fixed it too.
Thanks!

react version:0.14.2
material-ui version:0.13.3
react-quill 0.3.0

as below

Warning: onDismiss will be removed in favor of explicitly setting open and can be replaced by onRequestClose

Warning: ReactDOMComponent: Do not access .getDOMNode() of a DOM node; instead, use the node directly. This DOM node was rendered by `Quill`.

**Comment by zenoamaro** [comment]
Yes! Compliance with React 0.14 is planned for the very next release! 

Though this will only cover the `getDOMNode()` warning, there is no `onDismiss` in Quill, so that must be coming from material.

**Comment by Ben07** [comment]
@zenoamaro got it.Thanks!

**Comment by zenoamaro** [comment]
Latest release published on NPM (v0.4.0) has official support for React 0.14.
