### ISSUE TITLE
Align working in editor, produced html not compatible with flexbox

### ISSUE THREAD

**Issue by ZoeElizabeth** [zenoamaro/react-quill#553]
I have the align feature included in my toolbar and it works as expected in the editor. The compiled html with the classes ql-align-center/ql-align-right does not align the content in the generated html. 

When I add display: flex and justify-content: center/right inline on the html its look as expected on the webpage. This not feasible for me to do though, I can't edit every submission to add inline style to the generated html. 

Would really like this feature to work and be compatible with flexbox. I would have submitted altered css but am unfamiliar with stylus and couldn't figure out how to update the classes to include display: flex and justify-content: center/right on the the classes ql-align-center/ql-align-right.

**In Editor**
![Screen Shot 2019-12-06 at 10 47 02 AM](https://user-images.githubusercontent.com/43502013/70347986-8ea8dd80-1816-11ea-99e4-3dc746d0ba4a.png)

**Inserted to page with Html Parser or dangerouslySetHtml**
![Screen Shot 2019-12-06 at 10 46 44 AM](https://user-images.githubusercontent.com/43502013/70348003-98cadc00-1816-11ea-8786-db2b5bbbe749.png)

Please let me know if there is a way for me to fix these styles so the generated classes appear as expected on the webpage.

**Comment by ZoeElizabeth** [comment]
Ahh. I resolved, just overwrote the classes in my own styles...

**Comment by alexkrolick** [comment]
If you have conflicts with the CSS, you can also use one of the minimal CSS themes instead of the default, or omit the stylesheet altogether for rendered content.

**Comment by duongsieu** [comment]
I am having the same problem, but I think overwriting the classes is not a good solution. Do you have any other workarounds?

**Comment by KYogananda** [comment]
> Ahh. I resolved, just overwrote the classes in my own styles...

how to over write class with our own classes

**Comment by JamalSBS** [comment]
> 
> 
> > If you have conflicts with the CSS, you can also use one of the minimal CSS themes instead of the default, or omit the stylesheet altogether for rendered content.
> 
> @alexkrolick how did you resolve this?

@ZoeElizabeth Bump, how did you end up fixing this?

**Comment by ZoeElizabeth** [comment]
@JamalSBS 

It been a long time and I don’t have access to the codebase I was creating this for anymore.

If there are classes creates the generated HTML I would have just taken that class and done my changes with the !important flag.

or

I would have wrapped the the HTML in a class and created my own styles for each element under that class and flagging any not working styles with !important. 

I remember when I got it solved I just rewrote stuff in my css file and flagged what I needed to work with !important. I think it was the first route though, and finding the classes through my dev tools.

Sorry, that’s all in recall

**Comment by JamalSBS** [comment]
> 
> 
> @JamalSBS
> 
> It been a long time and I don’t have access to the codebase I was creating this for anymore.
> 
> If there are classes are created in the generated HTML I would have just taken that class and done my changes with the !important flag.
> 
> or
> 
> I would have wrapped the the HTML in a class and created my own styles for each element under that class and flagging any not working styles with !important.
> 
> I remember when I got it solved I just rewrote stuff in my css file and flagged what I needed to work with !important. I think it was the first route though, and finding the classes through my dev tools.
> 
> Sorry, that’s all I recall

I see. I would need the produced HTML to be compatible email clients, so I don't have the luxury of overriding the CSS. 

Hmm, this seems to be a recurring theme with Quill, this shortcoming is just like the how Quill adds <p> tags and wraps <br> with p tags.

**Comment by kentvdc029** [comment]
I fixed it by containerizing the html value by div with "ql-editor" class.
Here's my sample code for using dangerouslySetInnerHTML

```
<div className="ql-editor">
       <div dangerouslySetInnerHTML={{ __html: your_quill_html_value }} /> 
</div>
```

Hope it helps to future readers.

**Comment by trinhminhhieu** [comment]
My solution is to override it by adding the highest priority !important

```
.ql-align-center {
  text-align: center !important;
}

.ql-align-left {
  text-align: left !important;
}

.ql-align-right {
  text-align: right !important;
}

.ql-align-justify {
  text-align: justify !important;
}
```

**Comment by arkadx13** [comment]
> I fixed it by containerizing the html value by div with "ql-editor" class. Here's my sample code for using dangerouslySetInnerHTML
> 
> ```
> <div class="ql-editor">
>        <div dangerouslySetInnerHTML={{ __html: your_quill_html_value }} /> 
> </div>
> ```
> 
> Hope it helps to future readers.

Thank you sooo muuuchhh. I've been searching for the solution for 2 days and yours works for me.

**Comment by maznevskia** [comment]
> I fixed it by containerizing the html value by div with "ql-editor" class. Here's my sample code for using dangerouslySetInnerHTML
> 
> ```
> <div class="ql-editor">
>        <div dangerouslySetInnerHTML={{ __html: your_quill_html_value }} /> 
> </div>
> ```
> 
> Hope it helps to future readers.

Love the solution and for anyone wondering if it is not working on your end, make sure to import the CSS file.

**Comment by damiandominella** [comment]
The current solutions in this thread rely on CSS overrides targeting Quill's default classes, which creates unnecessary coupling. A more robust approach would be to customize the class generation itself, allowing easy integration with existing design systems like Tailwind.

I've implemented a custom attributor that directly generates semantic Tailwind classes (`text-center`, `text-right`, `text-left`, `text-justify`) instead of relying on the default `ql-align-*` classes:


```typescript
import Quill from 'quill';

const Parchment = Quill.import('parchment');

export class CustomAlignAttributor extends Parchment.Attributor {
	constructor(attrName: string, keyName: string, whitelist: string[] = []) {
		super(attrName, keyName, { whitelist });
	}

	add(node: HTMLElement, value: string): boolean {
		if (!(node instanceof HTMLElement)) {
			return false;
		}

		// Clear any existing alignment classes
		this.remove(node);

		if (value === 'center') {
			node.classList.add('text-center');
		} else if (value === 'right') {
			node.classList.add('text-right');
		} else if (value === 'justify') {
			node.classList.add('text-justify');
		} else {
			this.remove(node);
		}

		return true;
	}

	remove(node: HTMLElement): void {
		if (!(node instanceof HTMLElement)) {
			return;
		}
		node.classList.remove('text-center', 'text-right', 'text-justify');
	}

	value(node: HTMLElement): string | boolean {
		if (!(node instanceof HTMLElement)) {
			return false;
		}
		if (node.classList.contains('text-center')) {
			return 'center';
		} else if (node.classList.contains('text-right')) {
			return 'right';
		} else if (node.classList.contains('text-justify')) {
			return 'justify';
		}

		// Return false if no specific alignment class is found (Quill expects false or a value)
		return false;
	}
}

Quill.register(
	'formats/align',
	new CustomAlignAttributor('align', 'ql-align', ['center', 'right', 'justify']),
	true
);
```
