### ISSUE TITLE
componentWillReceiveProps and componentWillUpdate are becoming deprecated in React 17.x

### ISSUE THREAD

**Issue by TraceWright** [zenoamaro/react-quill#554]
Please update these lifecycle methods in Quill component as they are becoming deprecated in React 17.x

Console warnings:

Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

**Please update the following components: Quill**

Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

**Please update the following components: Quill**

**Comment by alexkrolick** [comment]
See open PRs

**Comment by richgong** [comment]
See https://github.com/zenoamaro/react-quill/issues/518

**Comment by macknull** [comment]
@alexkrolick  can you elaborate? open PRs for which version? I'm still getting the warning in 1.3.5
