### ISSUE TITLE
Unable to get react-quill 0.3.0 working with react 0.12.1

### ISSUE THREAD

**Issue by stileswatson** [zenoamaro/react-quill#56]
I'm running React.js 0.12.1 and upgrading to 0.13 or 0.14 is not possible at this time.

I tried installing react-quill via "npm install react-quill". Version 0.3.0 was installed and, looking at react-quill\package.json, the devDependency for react is "^0.12.0". 

When I use react-quill as follows in my React component, I get the warning, _"Warning: Something is calling a React component directly. Use a factory or JSX instead"_ from react-with-addons.js, followed by the error _"Uncaught TypeError: Cannot read property '__reactAutoBindMap' of null"_ from ReactClass.sj.

``` javascript
var ReactQuill = require('react-quill');
var MyComponent = React.createClass({
    render: function() {
        return <ReactQuill value="hi" />;
    }
);
```

As you can see, I am using JSX.

I saw some discussion on removing React 0.12 support at some point. Does react-quill 0.3.0 still support React 0.12?

**Comment by zenoamaro** [comment]
Yes, React 0.12 will still be supported up until next version, when support for React 0.14 will be merged in, and support for React 0.13 and less will be dropped.

ReactQuill already uses `React.createFactory` throughout to support React 0.12, though, so I believe there's something else at play here. I'll try and see if I can reproduce.
