### ISSUE TITLE
Directly entering HTML markup in react-quill editor

### ISSUE THREAD

**Issue by asah27** [zenoamaro/react-quill#561]
This is more like a doubt. I was trying to add HTML markup text directly into the editor, then It was getting converted to a text with escaped sequences. Could someone please help me if there is any way to keep it as it is. 

Example:

Input: <b>REACT-QUILL</b>
Output: <p>&lt;b&gt;REACT-QUILL&lt;/b&gt;</p>
Required Output: <p><b>REACT-QUILL</b></p>

**Comment by mdathersajjad** [comment]
For this you can get the editor reference and do editor.clipboard.dangerouslyPasteHTML
