### ISSUE TITLE
Releases seem to be messed up

### ISSUE THREAD

**Issue by jbojcic1** [zenoamaro/react-quill#562]
Something seems to be wrong with releases. If you check changelog https://github.com/zenoamaro/react-quill/blob/master/CHANGELOG.md it says that `preserveWhitespace` is added in v1.3.2 and if I install v1.3.3 I don't see it.

Also if you check `types.d.ts` in `master` on github you will see the prop but if you switch from master to `v1.3.3` tag it's not there.

Could you pls make a new release and make sure this is included?

**Comment by zenoamaro** [comment]
The feature was supported, but the type definition wasn't in the release.

This should be fixed with 1.3.4. Cheers
