### ISSUE TITLE
Editing CSS file doesn't make difference

### ISSUE THREAD

**Issue by hegdeMadan** [zenoamaro/react-quill#568]
Hi Thank you so much for this beautiful text-editor first of all!

Is there a specific way to make it responsive and move toolbar to bottom and do some styling?

**What I have tried** : Editing css file (dist/quill.snow.css) which didn't make any difference. But when I tried editing tool bar on browser it all works fine.
Let me know how I can solve this if anyone knows.

Thanks in advance.

**Comment by BitPhinix** [comment]
Are you sure that you are editing the correct CSS file / you import the correct one? Also, try clearing the application storage if you are using a service worker.

**Comment by adwnm** [comment]
I am able to overwrite styling.  I've provided an example:
https://codesandbox.io/s/tender-lamport-e9r1f?fontsize=14&hidenavigation=1&theme=dark
