### ISSUE TITLE
Why is React Quill matchVisuals not working?

### ISSUE THREAD

**Issue by douglasrcjames** [zenoamaro/react-quill#570]
I am trying to remove the extra `<p><br></p>` tags that are present as line breaks while using React Quill. I tried implementing the `matchVisual` parameter outlined [here][1], but it still seems to be giving me that paragraph and br tags in the output. [Here is a code pen][2] showing simple changes to the Quill demo setup, and it still doesn't work. 

I declare the modules for Quill in the constructor like:

     constructor (props) {
        super(props)
        this.state = { editorHtml: '', theme: 'snow' }
        this.handleChange = this.handleChange.bind(this)
        this.modules = {
                toolbar: [
                    [{ 'header': '1'}, {'header': '2'}],
                    [{size: []}],
                    ['bold', 'italic', 'underline', 'strike', 'blockquote'],
                    [{'list': 'ordered'}, {'list': 'bullet'}, 
                    {'indent': '-1'}, {'indent': '+1'}],
                    [{ align: '' }, { align: 'center' }, { align: 'right' }, { align: 'justify' }],
                    ['link', 'image'],
                    ['clean']
                ],
                clipboard: {
                  matchVisual: false,
                }
              }
            
        this.formats = [
          'header', 'size',
          'bold', 'italic', 'underline', 'strike', 'blockquote',
          'list', 'bullet', 'indent',
          'link', 'image', 'align'
        ]
      }

I am probably doing something just a tad bit wrong, any ideas?

  [1]: https://github.com/zenoamaro/react-quill/issues/250
  [2]: https://codepen.io/douglasrcjames/pen/zYGvMPd

#### React-Quill version 
- [x] master (^1.3.3)
- [ ] 0.4.1
- [ ] 1.0.0-beta-1
- [ ] 1.0.0-beta-2
- [ ] 1.0.0-beta-3
- [ ] 1.0.0-beta-4
- [ ] 1.0.0-beta-5
- [ ] 1.0.0-rc-1
- [ ] 1.0.0-rc-2
- [ ] 1.0.0-rc-3
- [ ] 1.0.0
- [ ] 1.1.0
- [ ] Other (fork)

**Comment by austere-rm** [comment]
Exact same problem here with  ```"react-quill": "^1.3.3"```

```
export function RenderRichText({ input, label, placeholder }) {
    const classes = useStyles()
    const toolbarOptions = [
        { 'header': [1, 2, 3, false] },
        'bold',
        'italic',
        'underline',
        'blockquote',
        { 'list': 'ordered' },
        { 'list': 'bullet' },
        { 'indent': '-1' },
        { 'indent': '+1' },
        { 'color': [] },
        { 'background': [] },
        'link',
        'image',
        'video'
    ]

    return (
        <Grid item xs={12} >
            <FormControl style={{ width: '100%' }}>
                <FormLabel className={classes.label}>{label}</FormLabel>
                <ReactQuill
                    theme="snow"
                    {...input}
                    onChange={(newValue, delta, source) => {
                        if (source === 'user') {
                            input.onChange(newValue)
                        }
                    }}
                    onBlur={(range, source, quill) => {
                        input.onBlur(quill.getHTML())
                    }}
                    placeholder={placeholder ? placeholder : 'Enter text here...'}
                    modules={{
                        toolbar: toolbarOptions,
                        clipboard: {
                            matchVisual: false
                        }
                    }}
                />
            </FormControl>
        </Grid >
    )
}
```

**Comment by filipgrkinic** [comment]
Are there any updates on this? I'm having this issue as well, setting matchVisual to false doesn't seem to be doing anything.

**Comment by douglasrcjames** [comment]
I never got an answer to fixing matchVisuals, but I solved it by using this snippet on the output as a work around to just remove the visuals of the `br` tag that was being inserted:

**HTML/JSX:**
`<div className="bye-br" dangerouslySetInnerHTML={{__html: this.props.article.body}}></div>`

**CSS:**
```
 /* Don't display line breaks */
 .bye-br br {
  display: block;
  margin: 10px 0;
  line-height: 30px;
  content: " ";
}

.bye-br {
  all: unset;
}
```

**Comment by filipgrkinic** [comment]
Thanks for sharing! I ended up just doing the following, before storing it in the database.
`text.replace(/<p><br><\/p>/g, "")`

**Comment by douglasrcjames** [comment]
I like your solution more, I might implement yours in the future haha!
