### ISSUE TITLE
Upgrade quill to 1.3.7 to close vulnerability

### ISSUE THREAD

**Issue by JuliaMi12** [zenoamaro/react-quill#575]
Hi,

There is known vulnerability in quill@<1.3.7 https://github.com/quilljs/quill/issues/2438 which is related to reverse tabnabbing.
I'm using react-quill@1.3.3 which installed quill@1.3.6 for me and I get reports about vulnerability in my code. Can you publish a new version with quill@^1.3.7 please?

**Comment by alexkrolick** [comment]
`yarn upgrade react-quill` should bump the dependency version

**Comment by vpsk** [comment]
@JuliaMi12  @alexkrolick Will it updates react-quill internal dependency also? when we do next ```npm i``` will it not have the same packages as earlier one?
