### ISSUE TITLE
Dev Dependencies

### ISSUE THREAD

**Issue by castroCrea** [zenoamaro/react-quill#586]
in the V2 the packages.json has wrong dev dep

```
  "dependencies": {
    "@types/quill": "^1.3.10",
    "lodash": "^4.17.4",
    "quill": "^1.3.7"
  },
```

When I install it and I do `yarn list` I got this
<img width="241" alt="Capture d’écran 2020-04-08 à 14 10 09" src="https://user-images.githubusercontent.com/20707343/78782716-ba91c680-79a2-11ea-9fc6-543f51f47965.png">

**Comment by zenoamaro** [comment]
As far as I can see, `@types/quill@1.3.10` is the correct types version for `quill@1.3.7`. The two projects update independently, and it's not mandatory for them to keep the same version number.

Have you been experiencing any sort of issue related to this?
