### ISSUE TITLE
value prop changes are not reflected

### ISSUE THREAD

**Issue by jeiea** [zenoamaro/react-quill#588]
React-Quill version: **2.0.0-beta.1**

It seems value prop changes can't change internal quill editor contents. I expect [this codesandbox](https://codesandbox.io/s/react-quill-bug-5ue4u) quill contents to be changed every 1 second, but it doesn't.

I suspect [`shouldComponentUpdate`](https://github.com/zenoamaro/react-quill/blob/47f8a4edfeaf294741798ca55d49c20b54097e63/src/index.tsx#L212) blocks `componentDidUpdate` call taking charge of reflecting value changes.

How about adding `value` to `cleanProps`?

**Comment by zenoamaro** [comment]
Hello. The management of `value` has been changed to fix this issue. It is experimentally located in this branch: https://github.com/zenoamaro/react-quill/tree/fix/direct-value-change

Any chance you could try it (eg. using `npm link`)? It is a big enough change that I'd prefer to test it out before releasing it. Thanks!

**Comment by jeiea** [comment]
I tried `npm i github:zenoamaro/react-quill#fix/direct-value-change` and `git clone; npm link; cd project; npm link react-quill`, but when I run webpack `node_modules/react-quill` directory is cleared except package.json. I couldn't figure out it...

**Comment by jeiea** [comment]
It seems good. I can test it by making tarball.

**Comment by gleidsonh** [comment]
is this fixed? I've updated to 2.0.0-beta.2 but doesn't works yet. =/

**Comment by jeiea** [comment]
@gleidsonh I think that's another issue. At least my sandbox has no problem with 2.0.0-beta.2.
I could fix your example by inserting `setText(Math.random());` above `setText(textTyped)`.

I agree this behavior is less intuitive and we have a chance to change this because it is still beta. How about creating separate issue for more attention?

**Comment by zenoamaro** [comment]
This is indeed a separate issue, but it's due to how the `setState` hook behaves, when used in that specific way. I could however provide a work around.

**Comment by pmaddaloni-shujinko** [comment]
This bug still appears to occur in `2.0.0-beta.2`; e.g. if I update the value and pass that change to the Quill component via `value`, that change is not reflected.

The basic rundown for me is that I save the current content of an active (e.g. not `readOnly`) Quill editor when the user leaves the page. When they come back to that page, if they activate the quill editor (it gets set to `readOnly={false}`, the content is loaded and that change is passed to the Quill editor via the `value` prop - it never gets reflected in the editor.

**Comment by avinashk2946** [comment]
This issue still exists; not able to bind data into text editor by passing data using value or default value props.

Note: The assigned value is HTML string

**Comment by jeiea** [comment]
@pmaddaloni-shujinko @avinashk2946 My codesandbox's bug behaviour is not reproducible on 2.0.0-beta.2. Your phenomenon may be a separate issue, may have different conditions to reproduce.
How about opening a new issue with a reproducible codesandbox?

**Comment by KumarAscharyaPrasad** [comment]
The bug still appearing  in **2.0.0-beta.4** if I update the value and pass that change to the Quill component via value, that change is not reflected.
