### ISSUE TITLE
Hope React-quill can support customized className for Toolbar items

### ISSUE THREAD

**Issue by southerncross** [zenoamaro/react-quill#59]
Hi, :smiley:

Currently, react-quill use `'ql-'+item.type` as the class name of item, which in some cases is inconvenient for customizing.

For example, I use [icomoon](https://icomoon.io/) to create icons. However, it gives me icons with class name such as `icon-blablabla`. So I have to modify these class name from `icon-blablabla` to `ql-blablabla` manually. 
Therefore I hope that react-quill can support customized class name for items. Like:

```
    renderChoices: function(item, key) {
        return React.DOM.select({
            key: item.label || key,
            title: item.label,
            className: 'ql-'+item.type + ' ' + item.className },     <---- customized class name
            item.items.map(this.renderChoiceItem)
        );
    },
```

Thanks :blush:

**Comment by zenoamaro** [comment]
Sure, would you be able to make a PR? I'd merge that immediately.

It would be cool to extend this feature to all toolbar components where it makes sense.

**Comment by zenoamaro** [comment]
The ReactQuill Toolbar has been deprecated in the latest version, so no further work on it will be done unless needed. That said, I would still consider a PR on this for inclusion.

You can, however, create a custom toolbar very easily. Please refer to [the Quill toolbar configuration](http://quilljs.com/docs/modules/toolbar) to see how this can be done.
