### ISSUE TITLE
[V2] Changing modules leads to a blank editor

### ISSUE THREAD

**Issue by rockwotj** [zenoamaro/react-quill#593]
Here is a code sandbox example of the behavior:
https://codesandbox.io/s/react-quill-bug-ddsnb?file=/src/App.js

If you try typing in the editor at all (at least in Stable Chrome) the full editor is unrendered. I'm assuming this is a bug in how dirty props are handled and the editor is never recreated?

**Comment by zenoamaro** [comment]
The latest fix merged on master fixes this reproduction case! Check it out!

**Comment by rockwotj** [comment]
@zenoamaro awesome thanks for fixing! Are you able to create a `beta2` release with this fix?
