### ISSUE TITLE
online demo please :)?

### ISSUE THREAD

**Issue by winkler1** [zenoamaro/react-quill#6]
For react.rocks -- thanks

**Comment by zenoamaro** [comment]
Here it is https://zenoamaro.github.io/react-quill

Have a look!

**Comment by winkler1** [comment]
Looks great! One comment, when I first come into the page there's a lot of whitespace in the markup-
![image](https://cloud.githubusercontent.com/assets/883896/7621793/8f23e090-f997-11e4-8911-c9c898486b5e.png)

Making a little change (bolding "free") updates the markup and it jumps visually a lot-
![image](https://cloud.githubusercontent.com/assets/883896/7621797/a1e2b47c-f997-11e4-96af-1a05f4c5d18d.png)

Not a show stopper, but jarring for a first-timer..

**Comment by zenoamaro** [comment]
You're right! What about now?

**Comment by winkler1** [comment]
good, but now there are wierd spacing problems on the left--
![image](https://cloud.githubusercontent.com/assets/883896/7622787/debd6b68-f9a0-11e4-8d23-d84fcdcebe98.png)

**Comment by zenoamaro** [comment]
Ok, I think I managed to have the thing become tighter. How does it look?

**Comment by winkler1** [comment]
great!

**Comment by zenoamaro** [comment]
Do you have a link btw?
