### ISSUE TITLE
Uncaught TypeError: Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by mtando** [zenoamaro/react-quill#61]
in mixin.js:
    destroyEditor: function(editor) {
     editor.destroy();
    },

if the DOM's changed (the editor had been removed) , I get the following error in Chrome: Uncaught TypeError: Cannot read property 'destroy' of undefined. Probably need to add a null check

**Comment by MichalZalecki** [comment]
+1

**Comment by MichalZalecki** [comment]
`componentWillUnmount` which tries to destory the editor is called also by `componentWillUpdate`. In my case it happen when I'm trying to use `toolbar` prop. Editor state is not updated yet after mount from what I see.

**Comment by difelice** [comment]
I'm having same issue when use custom `toolbar`

**Comment by gor181** [comment]
Is this going to be merged and released any time soon? It has been 4 months..

**Comment by mouhsinelonly** [comment]
is there any update concerning this issue or how to go arround it ?

**Comment by zenoamaro** [comment]
Should be fixed in the latest `master`. Can you verify?
