### ISSUE TITLE
quill recently enabled grammarly on quill

### ISSUE THREAD

**Issue by jaddoescad** [zenoamaro/react-quill#619]
is it possible to integrate the recent changes?

**Comment by zenoamaro** [comment]
As far as I know, the Grammarly fix only applies to Quill 2, which is not out yet.

Please follow #601 for updates on Quill 2 support for ReactQuill.

**Comment by cancan101** [comment]
From this thread: https://github.com/quilljs/quill/issues/574#issuecomment-670418301 it seems like the new version of Grammarly (out since late 2019) should work with quill.

**Comment by cancan101** [comment]
What would be the suggested way to re-enable Grammarly support when using `react-quill` ?
