### ISSUE TITLE
How to resize image, I'm using NextJS

### ISSUE THREAD

**Issue by Kamez** [zenoamaro/react-quill#629]
Now I'm facing with the issue about resize image with NextJS. I tried to use **quill-image-drop-module** but it's not working.

Could anyone advise or show the example to me ?
Thanks.

**Comment by zenoamaro** [comment]
Your question pertains a plugin for Quill, rather than ReactQuill. I suggest [asking the question on StackOverflow](https://stackoverflow.com/questions/tagged/quill)

**Comment by Abuitime** [comment]
Did you end up finding a solution?

**Comment by raja-poudel** [comment]
@Kamez did you find the solution?
