### ISSUE TITLE
Default font sizes for "Normal" and "Smaller" swapped

### ISSUE THREAD

**Issue by or** [zenoamaro/react-quill#63]
The current (caaf6ef679fab3984e75e0e356a804250d2ff53c) default values for the font sizes are:
```js
		{ label:'Size', type:'size', items: [
			{ label:'Normal',  value:'10px' },
			{ label:'Smaller', value:'13px' },
			{ label:'Larger',  value:'18px' },
			{ label:'Huge',    value:'32px' }
		]}
```
I suspect "Normal" should be `13px` and "Smaller" then `10px`.

Ideally the order would still be "Smaller", "Normal", "Larger", "Huge", but it looks like the first element is assumed to be "Normal"? I haven't investigated this, but it'd be nice if above were the default option order and "Normal" were the default selection.

**Comment by brucedlukens** [comment]
+1

**Comment by craigklem** [comment]
+1

**Comment by zenoamaro** [comment]
Thanks a lot for noticing that. I've corrected the default items, and sorted out the selection state.
