### ISSUE TITLE
Most users don't know about adding https:// before their urls. We should assume that many will freehand a url and omit the https://

### ISSUE THREAD

**Issue by jurisjansons** [zenoamaro/react-quill#632]
Most users don't know about adding https:// before their urls. We should assume that many will freehand a url and omit the https:// thoughts on opening a ticket to resolve this issue?

_Originally posted by @FrederickEngelhardt in https://github.com/zenoamaro/react-quill/issues/529#issuecomment-568080144_

**Comment by zenoamaro** [comment]
This is a behavior of the Quill editor. While I agree with your suggestions, I can't implement them in ReactQuill. Please open a ticket here: https://github.com/quilljs/quill/issues

**Comment by heyalexchoi** [comment]
@jurisjansons 
you can prepend `http` scheme to urls for your users:

```
import Quill from 'quill'
const Link = Quill.import('formats/link');
Link.sanitize = function(url) {
  // quill by default creates relative links if scheme is missing.
  if (!url.startsWith('http://') && !url.startsWith('https://')) {
    return `http://${url}`
  }
  return url;
}
```

**Comment by Puspendert** [comment]
@heyalexchoi that means I need to add an extra dependency(`quill`) to the project and make the bundle size more heavy?

**Comment by alexkrolick** [comment]
@Puspendert Quill is a dependency of React-Quill already
