### ISSUE TITLE
Color option not working

### ISSUE THREAD

**Issue by edsilv** [zenoamaro/react-quill#637]
https://codesandbox.io/s/react-quill-template-fvioi?file=/src/App.js

https://codepen.io/edsilv/pen/dyGrKwd?editors=0010

I can't get the color option to work using the latest react-quill (clicking on the color button does nothing). 

It _seems_ to be a problem with react-quill, not quill itself, as the standalone quill demo works?

https://quilljs.com/standalone/full/

### Ticket due diligence

- [x] I have verified that the issue persists under ReactQuill `v2.0.0-beta.2`
- [ ] I can't use the beta version for other reasons

### ReactQuill version

- [ ] master
- [x] v2.0.0-beta.2
- [ ] v2.0.0-beta.1
- [ ] 1.3.5
- [ ] 1.3.4 or older
- [ ] Other (fork)

**Comment by MonteKrysto** [comment]
@edsilv I got this working by just adding `[{ color: [] }, { background: [] }]` to the modules. https://codesandbox.io/s/react-quill-template-3eb50

Do you have any idea how to incorporate a custom toolbar item?

**Comment by edsilv** [comment]
Ah, I was using `["color"]` not `[{ "color": [] }]` which makes the button appear but not function. Thanks!
