### ISSUE TITLE
Quill component isn't exposed yet

### ISSUE THREAD

**Issue by sandzone** [zenoamaro/react-quill#64]
I don't think the Quill namespace is exposed yet. I noticed that the change that exposes the Quill namespace happened a month ago while the latest dist is 2 months old.

I struggled a bit with the browser throwing up 'undefined' when accessing the component. It'll be great if you can check this out.

Awesome work with the editor. I am a convert from TinyMCE to Quill.

**Comment by zenoamaro** [comment]
Updates to the distributables are now being shipped with version v0.4.0, and published to NPM.

This should solve your issue. Apologize for the time it took.
