### ISSUE TITLE
Unable to access Editor instance with dynamically imported react-quill in NextJS 

### ISSUE THREAD

**Issue by sanderfish** [zenoamaro/react-quill#642]
I'm using react-quill in a NextJS app. I'm looking to extend a part of the app where I want to force users to use the Quill instance with a specific formatting option enabled by default (list). To achieve this, I believe I need access to the Quill Editor instance.

However, when attempting to use a ref, I'm unable to call the getEditor method on the ref. The only method available is `retry`.

I've made a CodeSandbox: https://codesandbox.io/s/nextjs-dynamic-react-quill-ref-example-sxm64
Check the browser console to see what the ref object is.

**Expected behavior**:
I would expect the ref to contain a `getEditor` method 

**Actual behavior**:
The ref only contains a `retry` method

**Version**:
2.0.0-beta.2

**Comment by jularbs** [comment]
have you found a solution for this. I am also experiencing this issue as well.

**Comment by sanderfish** [comment]
@jularbs I have not.

**Comment by alexkrolick** [comment]
Are you trying to do this in server-side render (SSR) mode? If so, does NextJS provide a window.document object? You can't SSR React-Quill without it.

**Comment by alexkrolick** [comment]
I am not an expert on Next, but it looks like this creates a dynamic component wrapper around ReactQuill.

```jsx
const ReactQuill = dynamic(() => import("react-quill"), {
  ssr: false
});
```

When you render it, it's not giving you a ref to RQ, it's a ref to the wrapper that Next creates:

```jsx
    <ReactQuill ref={quillRef} theme="snow" value={value} onChange={setValue} />
```

Here is an issue on the Next side that describes some potential solutions. Can you try one of them and see if it works for you?

https://github.com/vercel/next.js/issues/4957

**Comment by mrgoonie** [comment]
Perhaps we could switch into this: https://www.npmjs.com/package/react-quilljs

Code example: https://codesandbox.io/s/laughing-surf-ox7q5

**Comment by EugeneTeu** [comment]
if your use case allows you to, can disable SSR for the specific module. 

I ran into the same issue with using this for `@toast-ui/react-editor`

My workaround is this: 
- Create a dummy component in `components` folder 
` export it as another component and the ref should be able to be accessed

![Screenshot 2020-10-05 at 9 32 21 PM](https://user-images.githubusercontent.com/43085751/95085996-867d3f80-0752-11eb-88c2-29cb3ad08ec7.png)

```js
 const editor = useRef()


  <Editor
            //@ts-ignore
            previewStyle="vertical"
            height="40vh"
            initialEditType="markdown"
            initialValue="hello"
            ref={editor}
  />
```

**Comment by kt3k** [comment]
When `next/dynamic` wraps the component, it doesn't seem forwarding `ref` to the internal component. If I wrapped ReactQuill component with `ref` renamed to `forwardedRef`, it seemed working.

https://codesandbox.io/s/nextjs-dynamic-react-quill-ref-example-forked-gyhz3

**Comment by CooperHash** [comment]
> When `next/dynamic` wraps the component, it doesn't seem forwarding `ref` to the internal component. If I wrapped ReactQuill component with `ref` renamed to `forwardedRef`, it seemed working.
> 
> https://codesandbox.io/s/nextjs-dynamic-react-quill-ref-example-forked-gyhz3

but what about tsx file in next.js? your codesandbox is js

**Comment by hadarhubara10** [comment]
> > When `next/dynamic` wraps the component, it doesn't seem forwarding `ref` to the internal component. If I wrapped ReactQuill component with `ref` renamed to `forwardedRef`, it seemed working.
> > https://codesandbox.io/s/nextjs-dynamic-react-quill-ref-example-forked-gyhz3
> 
> but what about tsx file in next.js? your codesandbox is js

With TS

```ts
const ReactQuillComponent = dynamic(
  async () => {
    const { default: RQ } = await import('react-quill');

    const Component = ({ forwardedRef, ...props }: { forwardedRef: RefObject<ReactQuill> } & ReactQuillProps) => (
      <RQ ref={forwardedRef} {...props} />
    );

    Component.displayName = 'ReactQuillComponent';
    return Component;
  },
  {
    ssr: false,
  }
);

ReactQuillComponent.displayName = 'ReactQuillComponent';
);
```

**Comment by syed-shoaib-ali** [comment]
> When `next/dynamic` wraps the component, it doesn't seem forwarding `ref` to the internal component. If I wrapped ReactQuill component with `ref` renamed to `forwardedRef`, it seemed working.
> 
> https://codesandbox.io/s/nextjs-dynamic-react-quill-ref-example-forked-gyhz3

brooooo 🙌🏻
