### ISSUE TITLE
when using on nextjs

### ISSUE THREAD

**Issue by jonsoku2** [zenoamaro/react-quill#648]
### ReactQuill version

- [ ] master
- [ ] v2.0.0-beta.2
- [ ] v2.0.0-beta.1
- [x] 1.3.5
- [ ] 1.3.4 or older
- [ ] Other (fork)

### FAQ

Hello. I want to use react-quill with nextjs .

This is a problem with ssr, so I wrote this code with reference to issue #122.

However, only 'loading ...' continues, and react-quill does not appear.

There are no errors in the console, so tracking is not possible.

Can you help me ... ?

```javascript
import React from 'react';
import dynamic from 'next/dynamic';

const QuillNoSSRWrapper = dynamic(import('react-quill'), {
  ssr: false,
  loading: () => <p>Loading ...</p>,
});

const modules = {
  toolbar: [
    [{ header: '1' }, { header: '2' }, { font: [] }],
    [{ size: [] }],
    ['bold', 'italic', 'underline', 'strike', 'blockquote'],
    [
      { list: 'ordered' },
      { list: 'bullet' },
      { indent: '-1' },
      { indent: '+1' },
    ],
    ['link', 'image', 'video'],
    ['clean'],
  ],
  clipboard: {
    // toggle to add extra line breaks when pasting HTML:
    matchVisual: false,
  },
};
/*
 * Quill editor formats
 * See https://quilljs.com/docs/formats/
 */
const formats = [
  'header',
  'font',
  'size',
  'bold',
  'italic',
  'underline',
  'strike',
  'blockquote',
  'list',
  'bullet',
  'indent',
  'link',
  'image',
  'video',
];

const Createtest = () => (
  <div>
    124
    <QuillNoSSRWrapper modules={modules} formats={formats} theme="snow" />
  </div>
);

export default Createtest;
```
### Brower
![image](https://user-images.githubusercontent.com/51524954/90347887-06016300-e06e-11ea-9402-121b31b25df7.png)

### Chrome console
![image](https://user-images.githubusercontent.com/51524954/90347895-131e5200-e06e-11ea-84bc-c552156e03b5.png)

**Comment by karthik-js** [comment]
@jonsoku2 
Have you loaded the css in _app and added css configuration to next config using @zeit/next-css. If so it should work.

**Comment by tbremer** [comment]
I am seeing this same issue, interestingly react-quill works fine in dev, but does not work in production.

**Comment by jasminnancy** [comment]
I found this to work much easier. As someone said above, don't forget to import the CSS file. It's required.
Change `snow` to `bubble` or `core` depending on what theme you plan to use.

```
const ReactQuill = typeof window === 'object' ? require('react-quill') : () => false
import 'node_modules/react-quill/dist/quill.snow.css'
```

**Comment by SkyYap** [comment]
> @jonsoku2 Have you loaded the css in _app and added css configuration to next config using @zeit/next-css. If so it should work. import 'react-quill/dist/quill.snow.css';

For those who are visiting, here's the update. Nextjs now has Built-In CSS Support. Can skip using @zeit/next-css

**Comment by SkyYap** [comment]
> @jonsoku2 Have you loaded the css in _app and added css configuration to next config using @zeit/next-css. If so it should work. import 'react-quill/dist/quill.snow.css';

I think they have fixed the issue. I just add `import 'react-quill/dist/quill.snow.css';` below next/dynamic and it works.

**Comment by trinhminhhieu** [comment]
> import 'node_modules/react-quill/dist/quill.snow.css'

Thanks!

After many days of struggling, I found this code that solves the problem!
```
import "quill/dist/quill.snow.css";
import "react-quill/dist/quill.snow.css"; 
const ReactQuill =
  typeof window === "object" ? require("react-quill") : () => false;
```

 This code makes **imageHandler** work in Nextjs 13.4!
