### ISSUE TITLE
Issue with getEditor() in componentDidMount()

### ISSUE THREAD

**Issue by sandzone** [zenoamaro/react-quill#65]
I am trying to load earlier saved HTML content into react-quill. 

Example 3 (setting content using dangerouslySetInnerHTML) isn't working for me.

As an alternative, I tried to access editor instance in componentDidMount() and set the HTML content using this.refs.quill.getEditor().setHTML({this.props.content});

However, getEditor() returns 'undefined' in componentDidMount()

If I use the same getEditor() later, say in an onChange event, i am able to access the underlying editor.

For now, i am accessing the DOM via getDOMNode() to set the initial HTML content.

It will be great if you can look into it.

**Comment by tylercollier** [comment]
What worked for me was just using `defaultValue`, like this (assume `this.savedHtml` is some value you've created):

```
<ReactQuill defaultValue={this.savedHtml} />
```

**Comment by sandzone** [comment]
Thanks Tyler. That works.

But, there were other issues with the react-quill component that were taking too much of my time. So, for the time being, I decided to not use the react-quill component.

Instead, I am using the quilljs directly by initializing a 'quill' on a 'div' in 'componentDidMount'.

**Comment by zenoamaro** [comment]
Hello, the technique proposed by @tylercollier is the correct one.

If you have issues with ReactQuill you can always list them here, and we'll try our best to solve them, so to help other users too.
