### ISSUE TITLE
Update React app state from React Quill content element node on click

### ISSUE THREAD

**Issue by raw-brt** [zenoamaro/react-quill#654]
I want to allow a specific element in the body of a React Quill editor to update the app context on click.

How can I do it?

Here is the custom blot I've made:

```
/* Mention blot config
  ====================== */
class MentionBlot extends BlockEmbed {
  static create(data) {
    const node = super.create();
    const denotationChar = document.createElement("span");
    denotationChar.className = "ql-mention-denotation-char";
    denotationChar.innerHTML = data.denotationChar;
    node.appendChild(denotationChar);
    node.innerHTML += data.value;
    return MentionBlot.setDataValues(node, data);
  }

  static setDataValues(element, data) {
    const domNode = element;
    Object.keys(data).forEach((key) => {
      domNode.dataset[key] = data[key];
    });
    return domNode;
  }

  static value(domNode) {
    return domNode.dataset;
  }
}

MentionBlot.blotName = "mentionCustom";
MentionBlot.tagName = "span";
MentionBlot.className = "mention";

Quill.register("formats/mentionCustom", MentionBlot);
```

And here is a screenshot of the elements in question:

![image](https://user-images.githubusercontent.com/12975849/91697717-decc8a80-eb71-11ea-863b-ba5b93554f3f.png)

Thank you :)

### Ticket due diligence

- [ ] I have verified that the issue persists under ReactQuill `v2.0.0-beta.2`
- [x] I can't use the beta version for other reasons

### ReactQuill version

- [ ] master
- [ ] v2.0.0-beta.2
- [ ] v2.0.0-beta.1
- [x] 1.3.5
- [ ] 1.3.4 or older
- [ ] Other (fork)

**Comment by alexkrolick** [comment]
Maybe you could create a Blot factory that proxies a reference to a function that updates the state? Or make your plugin create JS custom events and listen to them in the React component?

**Comment by raw-brt** [comment]
> Maybe you could create a Blot factory that proxies a reference to a function that updates the state? Or make your plugin create JS custom events and listen to them in the React component? You could also use Redux and maintain a reference to the store object outside React.

Hi, Alex. Thank you for commenting! Sadly, what you are proposing exceeds my level as a developer.

What is a blot factory?
How could I create custom JS events and make them available outside?

Regarding the redux part, I'm using useContext and useReducer to manage global states.

I think I'll redesign the functionality. Mentions are "cool" but I've seen that is not easy either to update mention inner html (and data-value) if the object that feeds it change. Or delete them in DB when you delete them there...

**Comment by alexkrolick** [comment]
> Regarding the redux part, I'm using useContext and useReducer to manage global states.

OK, working with that:

```diff
+ // store.js
+ // ...import redux stuff
+ // ...create store
+ // in a reducer, handle 'mention/create' event
+ /// export { store }
```

```diff
+ import {store} from './store' // where you create the redux store

/* Mention blot config
  ====================== */
class MentionBlot extends BlockEmbed {
  static create(data) {
    const node = super.create();
    const denotationChar = document.createElement("span");
    denotationChar.className = "ql-mention-denotation-char";
    denotationChar.innerHTML = data.denotationChar;
    node.appendChild(denotationChar);
    node.innerHTML += data.value;
+	store.dispatch({ type: 'mention/create', payload: data })
    return MentionBlot.setDataValues(node, data);
  }

  static setDataValues(element, data) {
    const domNode = element;
    Object.keys(data).forEach((key) => {
      domNode.dataset[key] = data[key];
    });
    return domNode;
  }

  static value(domNode) {
    return domNode.dataset;
  }
}

MentionBlot.blotName = "mentionCustom";
MentionBlot.tagName = "span";
MentionBlot.className = "mention";

Quill.register("formats/mentionCustom", MentionBlot);
```

> I think I'll redesign the functionality. Mentions are "cool" but I've seen that is not easy either to update mention inner html (and data-value) if the object that feeds it change. Or delete them in DB when you delete them there...

It is pretty complex. You have a few options:
- If you are doing username-only @-mentions, you can choose to either break all references (like twitter) if the username changes or remap the references 
- If you support short names/emails/aliases, you'd probably map the mentions to a unique ID somewhere on the backend rather than the only the substring

**Comment by alexkrolick** [comment]
Closing as this isn't an issue with the library itself

**Comment by raw-brt** [comment]
Thank you very much, Alex.

I'll give it a try.

Thank you.

Best,
Roberto.
