### ISSUE TITLE
React Quill componentWillUpdate & componentDidUpdate Warnings

### ISSUE THREAD

**Issue by Hassaan016** [zenoamaro/react-quill#655]
When i run my nextjs blog with react-quill the following warning appears:

Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate
![React Quill warning for NextJs](https://user-images.githubusercontent.com/66521099/91772972-4da3f500-ebff-11ea-8cf4-c1a556a1cdcc.jpg)
.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Quill

* Move data fetching code or side effects to componentDidUpdate.
* Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Quill

**Comment by alexkrolick** [comment]
These warnings are fixed in the latest release

**Comment by qramilq** [comment]
@alexkrolick here is [sandbox](https://codesandbox.io/s/competent-silence-3l4wl?file=/src/App.js)
