### ISSUE TITLE
How to use quill plugins with react-quill

### ISSUE THREAD

**Issue by anmol5varma** [zenoamaro/react-quill#656]
How do I use such a plugin?
https://github.com/kensnyder/quill-image-resize-module

Currently, I get -> TypeError: Cannot read property 'imports' of undefined

[Codesadbox link](https://codesandbox.io/s/funny-waterfall-pvxge?file=/src/App.js:116-142)

Thanks for filing an issue!

If at all possible, please provide a Codesandbox or Codepen to demonstrate the problem you're having with React Quill. Here's a [template] to get you started.

⚠️ Make sure that your bug hasn't already been fixed by ReactQuill `v2.0.0-beta.2`. See the homepage for instructions on how to upgrade.

[template]:
https://codesandbox.io/s/react-quill-template-u9c9c

### Ticket due diligence

- [ ] I have verified that the issue persists under ReactQuill `v2.0.0-beta.2`
- [x] I can't use the beta version for other reasons

### ReactQuill version

- [ ] master
- [ ] v2.0.0-beta.2
- [ ] v2.0.0-beta.1
- [x] 1.3.5
- [ ] 1.3.4 or older
- [ ] Other (fork)

### FAQ

**Is this a bug in Quill or ReactQuill?**

ReactQuill is just a ~thin~ wrapper on top of the Quill editor. Often, what looks like a bug in ReactQuill, is actually a bug in the Quill editor itself. Before opening a ticket, please check the [Quill documentation], and the [issues page], and see if that answers your question first.

[Quill documentation]:
https://quilljs.com/docs

[issues page]:
https://github.com/quilljs/quill/issues

**How do I access the wrapped Quill instance?**

See the [instance methods] and [API] documentation.

[instance methods]:
https://github.com/zenoamaro/react-quill#methods

[API]:
https://github.com/zenoamaro/react-quill#api-reference

**Comment by anmol5varma** [comment]
@zenoamaro ?

**Comment by ArjunAtlast** [comment]
+1

**Comment by anmol5varma** [comment]
@ArjunAtlast 
Use this instead

import ReactQuill, { Quill } from 'react-quill';
import ImageResize from 'quill-image-resize-module-react';
Quill.register('modules/imageResize', ImageResize);

module = {
		imageResize: {
			// parchment: Quill.import('parchment'),
			modules: ['Resize', 'DisplaySize']
		}
	};

**Comment by taltultc** [comment]
I found that doing this `window.Quill = Quill;` solve some problems with `'quill-image-resize-module-react'` library, like deleting the image

**Comment by dextel2** [comment]
Is there any library that works like this for iframes?
