### ISSUE TITLE
Unable to get selected text (getSelection, getText)

### ISSUE THREAD

**Issue by raw-brt** [zenoamaro/react-quill#658]
I'm trying to get the selected text on the editor when clicking a button on the toolbar.

I'm using getSelection first and the getText, but it doesn't work.

What am I missing? This should be pretty straightforward. I'm following Quill official docs for getSelection. I've checked in React Quill docs that getSelection() and getText() are available methods.

```
  const handleMark = () => {
    const range = getSelection();
    if (range) {
      if (range.length === 0) {
        console.log('User cursor is at index', range.index);
      } else {
        const text = getText(range.index, range.length);
        console.log('User has highlighted: ', text);
      }
    } else {
      console.log('User cursor is not in editor');
    }
  }
```
This is the function I'm passing to the onClick attribute to the button in the toolbar, but getText is not recognized.

Thank you.

### Ticket due diligence

- [ ] I have verified that the issue persists under ReactQuill `v2.0.0-beta.2`
- [X] I can't use the beta version for other reasons

### ReactQuill version

- [ ] master
- [ ] v2.0.0-beta.2
- [ ] v2.0.0-beta.1
- [X] 1.3.5
- [ ] 1.3.4 or older
- [ ] Other (fork)

**Comment by raw-brt** [comment]
If anyone faces the same issue, the getText() method is undefined.

You can extract the selected text (that's what I wished) with toString().

**Comment by spostad7** [comment]
Creates an [unprivileged editor](https://github.com/zenoamaro/react-quill#unprivileged-editor). Pass this method a reference to the Quill instance from getEditor
```javascript
const editor = this.reactQuillRef.getEditor();
const unprivilegedEditor = this.reactQuillRef.makeUnprivilegedEditor(editor);
// You may now use the unprivilegedEditor proxy methods
unprivilegedEditor.getText();
```
It provides the following methods, which are mostly proxies of existing [Quill methods](https://quilljs.com/docs/api/):

```getLength()``` : Returns the length of the editor contents, in characters, not including any HTML tag.

```getText()``` : Returns the string contents of the editor, not including any HTML tag.

```getHTML()``` : Returns the full HTML contents of the editor.

```getContents()``` : Returns a [Quill Delta](https://quilljs.com/docs/delta/) of the complete document.

```getSelection()``` : Returns the current selection range, or null if the editor is unfocused.

```getBounds()``` : Returns the pixel position, relative to the editor container, and dimensions, of a selection, at a given location.
