### ISSUE TITLE
Inline Style ordering is inconsistent

### ISSUE THREAD

**Issue by jbean96** [zenoamaro/react-quill#660]
My application is porting over to using `ReactQuill` as our new rich-text-editor. We need to be backwards compatible with our old rich text format which was to apply all styles inline (hence the registering of custom bold/italic style attributors to Quill). 

`ReactQuill` (or perhaps the `Quill` editor it uses under the hood) seems to be inconsistent with it's ordering of these inline style attributes. This is a problem because these re-ordering changes are surfaced as a "change" to the data model currently being displayed to the user. So they need to save changes to the rich text even though no changes were actually made.

Ideally we would change our data storage format to not be the raw HTML and instead be the Quill Delta, however, we are unable to do that as we need to be backwards compatible with existing rich text data.

In the application you can see that our initial HTML displayed by the editor should be: `<p><span style="font-style: italic; font-weight: bold;">Text</span></p>` however, the instant this is displayed, the `onChange` handler is called and indicates that the inner HTML is actually: `<p><span style="font-weight: bold; font-style: italic;">Text</span></p>` where the `font-style` and `font-weight` style attributes have been re-ordered.

If you start the editor with a default value of `<p><span style="font-weight: bold;  font-style: italic; ">Text</span></p>` where the ordering of the attributes has been flipped the resulting HTML passed to the `onChange` handler continues to do re-ordering: `<p><span style="font-style: italic; font-weight: bold;">Text</span></p>`. 

Ideally `Quill`/`ReactQuill` would either
A. have a consistent ordering of these attributes (i.e. `font-style` is always first, `font-weight` is always second, etc.) or
B. simply append new attributes to the end of the style string and not do any sort of re-ordering.

https://codesandbox.io/s/react-quill-template-forked-ocoge?fontsize=14&hidenavigation=1&theme=dark

### Ticket due diligence

- [x] I have verified that the issue persists under ReactQuill `v2.0.0-beta.2`
- [ ] I can't use the beta version for other reasons

### ReactQuill version

- [ ] master
- [x] v2.0.0-beta.2
- [ ] v2.0.0-beta.1
- [ ] 1.3.5
- [ ] 1.3.4 or older
- [ ] Other (fork)

### FAQ

**Is this a bug in Quill or ReactQuill?**

It's very possible that this bug is a Quill issue, however, it's easiest to demonstrate with `ReactQuill`'s API. Looking at the code I think the culprit may be how Quill converts a Delta to HTML and is surfaced in `ReactQuill` because of the use of `editor.clipboard.convert`.

[Quill documentation]:
https://quilljs.com/docs

[issues page]:
https://github.com/quilljs/quill/issues

**How do I access the wrapped Quill instance?**

See the [instance methods] and [API] documentation.

[instance methods]:
https://github.com/zenoamaro/react-quill#methods

[API]:
https://github.com/zenoamaro/react-quill#api-reference

**Comment by alexkrolick** [comment]
I think this is a Quill thing - it's part of how Quill handles the HTML conversion. I'd raise this over there.
