### ISSUE TITLE
CSS classes are not on the page when showing content from react quill.

### ISSUE THREAD

**Issue by luluhoc** [zenoamaro/react-quill#666]
Thanks for filing an issue!

### ReactQuill version

- [ ] master
- [x ] v2.0.0-beta.2
- [ ] v2.0.0-beta.1
- [ ] 1.3.5
- [ ] 1.3.4 or older
- [ ] Other (fork)

Hey, 

I don't know why but when showing content is formatted but, CSS classes like ql-size-small, etc are not on the page.

**Comment by alexkrolick** [comment]
Have a look at the styling docs: https://github.com/zenoamaro/react-quill#themes
