### ISSUE TITLE
How do I convert a plain HTML-code into a value of an editor?

### ISSUE THREAD

**Issue by ex1t3** [zenoamaro/react-quill#676]
I was just wondering, if there is a way to do this?

**I need to insert an already existing HTML code so it will be displayed as a text inside of the editor.**
```
let htmlSample = "<p>It's a test html <b>to be inserted!</b></p>
<ReactQuill htmlValue="{htmlSample}" />
```
So the result would be:
![image](https://user-images.githubusercontent.com/22543379/100286875-41b89c80-2f7c-11eb-8ce9-1b1b5dd658c5.png)

**Comment by ex1t3** [comment]
Okay, I got this. If anyone else wonders how to insert plain html - simply put your custom editor area like this
`<ReactQuill value={this.state.value}><div class="your-custom-container"><p>your custom html</p></div>`

**Comment by bogoroh** [comment]
@ex1t3 . I Don't understand your code snippet. Could you send me a working one?
