### ISSUE TITLE
Warning: Quill Toolbar.getDOMNode(...) is deprecated. Please use ReactDOM.findDOMNode(instance) instead

### ISSUE THREAD

**Issue by buctyoyo** [zenoamaro/react-quill#68]
__react 0.14.3 __
I got such error

**Comment by difelice** [comment]
The npm module has not been updated yet, you could install the latest with that fix via github:
```
npm i https://github.com/zenoamaro/react-quill
```

**Comment by cereallarceny** [comment]
The latest doesn't have this fix either...

**Comment by difelice** [comment]
Looks like the repo does not have latest build in the dist folder, try to run `npm run build`

**Comment by difelice** [comment]
Here's the commit: https://github.com/zenoamaro/react-quill/commit/ff973605b78108fc22a7200ebea22b418ac562d2#diff-d24fe73020f46dde060f58786e987b61

**Comment by zenoamaro** [comment]
Updates to the distributables are now being shipped with version `v0.4.0`, and published to NPM.
