### ISSUE TITLE
Unexpected warning when trying to use react-quill with react-hook-form.

### ISSUE THREAD

**Issue by amandeepmicro** [zenoamaro/react-quill#680]
I'm trying to validate the body of my form by using react hook form  and react quill. Please look at this issue and help me resolve it. 
Link to codesandbox : [link](https://codesandbox.io/s/html-editor-dpfhg?file=/src/App.js)

1st warning: 
react-dom.development.js:67 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Quill

2nd warning: 
react-dom.development.js:67 Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Quill

**Comment by Jonofat** [comment]
Did you get this to work with React-hook-form validation? If so, please could you share your solution, it would really help me a lot!

**Comment by amandeepmicro** [comment]
> Did you get this to work with React-hook-form validation? If so, please could you share your solution, it would really help me a lot!

Got it to work after trying all alternatives , Here is it. 
 dependencies -> `"react-quill": "^2.0.0-beta.2", "react-hook-form": "^6.13.0",` 
code ->
```
import { useForm, Controller } from 'react-hook-form';

import ReactQuill, { Quill } from 'react-quill';

const { register, unregister, handleSubmit, errors, getValues, control, setValue, trigger, reset, watch } = useForm({
      mode: 'onChange',
      defaultValues
   });

 <Controller
      control={control}
      name="body"
      rules={{
           required: "Article must have some content.",
           validate: value => {
               return value.split(' ').length > 10 || "Enter at least 10 words in the body."
             }
           }}
           render={(
                { onChange, onBlur, value, name, ref },
                { invalid, isTouched, isDirty }
               ) => (
                  <ReactQuill
                         onChange={onChange}
                         value={value}
                         inputRef={ref}
                         theme="snow"
                         formats={editorFormats}
                         modules={editorModules}
                         className={!!errors.body ? 'quill-error' : ''}
                         placeholder='Write your article content here...'
                         id="body"
                      />
                   )}
   />
   {errors.body && <span style={formStyle.errorMessage}>{errors.body.message}</span>}

```

Hope it helps.

**Comment by smartdev1206** [comment]
Hi,@amandeepmicro this solution isn't working for me. Can you please check this issue?
[https://stackoverflow.com/questions/67983695/how-to-validate-react-quill-with-react-hook-form-and-yup](https://stackoverflow.com/questions/67983695/how-to-validate-react-quill-with-react-hook-form-and-yup)
