### ISSUE TITLE
onPaste event support

### ISSUE THREAD

**Issue by skrobek** [zenoamaro/react-quill#69]
Would it be possible to add event for clipboard evenets, at least for the paste https://facebook.github.io/react/docs/events.html#clipboard-events ?

**Comment by tsusini** [comment]
+1

**Comment by zenoamaro** [comment]
I believe this issue should be redirected upstream to Quill.js proper.

Closing this, but feel free to reopen in case you feel that react-quill is preventing you from using onPaste.

**Comment by Bangkokian** [comment]
FYI -- As a very simple paste event detection, it's possible to use HTML5's **onpaste** within the quill editor HTML tag.

eg: 

`<div id="quillEditor" onpaste="console.log('you pasted something')"></div>`
