### ISSUE TITLE
upgrade to React 17

### ISSUE THREAD

**Issue by piratefinn** [zenoamaro/react-quill#691]
### Issue
This package currently throws a warning with React 17 as it still uses React 16. Seeing as previous commits fixed the deprecations 16 threw for what would change in 17, this should hopefully be a trivial change.

```
npm WARN react-quill@2.0.0-beta.2 requires a peer of react-dom@^16.0.0 but none is installed. You must install peer dependencies yourself.
```

### ReactQuill version
v2.0.0-beta.2

**Comment by hstevanoski** [comment]
Also, there are warnings about `componentWillReceiveProps` and `componentWillUpdate` being used that should be taken care of.  
However, looking at [this comment](https://github.com/zenoamaro/react-quill/issues/601#issuecomment-797262321) and the number of issues alone, it looks like this library isn't maintained anymore...

<img src="https://user-images.githubusercontent.com/10324469/114698914-eb2bdf00-9d1f-11eb-8abd-49d9003b65fb.png" width="480" />

**Comment by OrLevy23** [comment]
any chances this can get fixed?

**Comment by zettry1** [comment]
Any updates?

**Comment by thekennysong** [comment]
+1

**Comment by mahbd** [comment]
+1

**Comment by damien-monni** [comment]
+1

**Comment by nntdias** [comment]
+1

**Comment by sufius** [comment]
+1

**Comment by ckarsan** [comment]
+1

**Comment by younessadmi** [comment]
+1 !

**Comment by alexandrepernin** [comment]
+ 1

**Comment by rampa2510** [comment]
+1

**Comment by nathanmaru** [comment]
+1

**Comment by natanaelsimoes** [comment]
+1

**Comment by alexkrolick** [comment]
https://www.npmjs.com/package/react-quill?activeTab=versions 2.0.0-beta.3 allows react 17
