### ISSUE TITLE
No styles in distribution

### ISSUE THREAD

**Issue by lostpebble** [zenoamaro/react-quill#70]
Can't seem to find the quill.base.css or snow theme files anywhere in the node_modules package folder or the github repository.

**Comment by couds** [comment]
The style is in the quill folder not in the quill-react folder (node-modules/quill/dist/quill/base.css

**Comment by zenoamaro** [comment]
The latest release links Quill's stylesheets on ReactQuill's `dist/` directory for convenience.

See the [Styles chapter](https://github.com/zenoamaro/react-quill#styles-and-themes) on the README.
