### ISSUE TITLE
(Beta) 2.0 Already Requires an Out of Date React?

### ISSUE THREAD

**Issue by machineghost** [zenoamaro/react-quill#717]
I tried to install the beta, and got:

```
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project

Could not resolve dependency:
npm ERR! peer react@"^0.14.9 || ^15.3.0 || ^16.0.0" from react-quill@1.3.5
```

If I'm reading that correctly, React-Quill ... _the super new beta version_ ... requires that I have React 16 installed?  That doesn't seem correct.

### Ticket due diligence
- [X] I have verified that the issue persists under ReactQuill `v2.0.0-beta.2`

### ReactQuill version

- [X] v2.0.0-beta.2

**Comment by machineghost** [comment]
https://github.com/zenoamaro/react-quill/blob/master/package.json

```
    "react": "^16.11.0",
    "react-dom": "^16.11.0",
```

https://reactjs.org/versions shows **17.0.2** as the latest.

**Comment by markhughes** [comment]
If using yarn you can use resolutions:
https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

**Comment by alexkrolick** [comment]
https://www.npmjs.com/package/react-quill?activeTab=versions 2.0.0-beta.3 allows 17 as a peer dep
