### ISSUE TITLE
dist/css is not in npm package

### ISSUE THREAD

**Issue by iam4x** [zenoamaro/react-quill#74]
Running npm i -S react-quill will not provide you the CSS

**Comment by iam4x** [comment]
My bad dup of #70

**Comment by zenoamaro** [comment]
It's a proper issue, I'm reopening this one.

**Comment by zenoamaro** [comment]
It seems NPM won't publish symbolic links, which I'm using to provide a shortcut to quill's stylesheets.

I would prefer not to make an explicit copy of them, though. I'm looking for a solution to this.

**Comment by iam4x** [comment]
Since it depends on quill package as well, I have imported the styles from the quill package :)

**Comment by samzhang111** [comment]
This specific issue has broken the install for a project that I've been watching. I vote to maintain a copy of the quill styles in dist/ until a better solution is found.

**Comment by tylercollier** [comment]
In the meantime, I suggest changing the doc where it references the CSS paths. Change them from pointing at `react-quill/dist` to just `quill/dist`.

**Comment by abejfehr** [comment]
I thought I should mention that this is also an issue on cdnjs. I don't know if you publish there manually, but both of these files are empty:

https://cdnjs.cloudflare.com/ajax/libs/react-quill/0.4.1/quill.base.css
https://cdnjs.cloudflare.com/ajax/libs/react-quill/0.4.1/quill.snow.css

**Comment by spaceghostu** [comment]
I used npm i -S react-quill and there are no css files in dist/
