### ISSUE TITLE
why there are two quill toolbars?

### ISSUE THREAD

**Issue by simon-zhangmuye** [zenoamaro/react-quill#794]
![image](https://user-images.githubusercontent.com/10706610/165880272-5b6250eb-8b66-44cf-8807-9445dcf0c411.png)

**Comment by simon-zhangmuye** [comment]
I install it with npm install react-quill@beta --legacy-peer-deps

**Comment by ddy121** [comment]
That's my problem, too. Is there a solution

**Comment by Kikketer** [comment]
This issue remains for me as well
"react": "^18.1.0",
"react-quill": "^2.0.0-beta.4",
