### ISSUE TITLE
React 18 whitespace not working

### ISSUE THREAD

**Issue by taochu** [zenoamaro/react-quill#795]
After upgrading to React 18, when I type whitespaces into the editor, nothing is inserted and the placeholder still renders.

I've confirmed that the v2 beta versions have it solved but since it's still beta, we're hesitant to do the upgrade.

[CodeSandbox](https://codesandbox.io/s/react-quill-react-18-whitespace-issue-o5vqn9)

### Ticket due diligence

- [ ] I have verified that the issue persists under ReactQuill `v2.0.0-beta.2`
- [x] I can't use the beta version for other reasons

### ReactQuill version

- [ ] master
- [ ] v2.0.0-beta.2
- [ ] v2.0.0-beta.1
- [x] 1.3.5
- [ ] 1.3.4 or older
- [ ] Other (fork)

**Comment by andreiwow2** [comment]
I have the same issue...

**Comment by taochu** [comment]
@maxstue 

Unfortunately no. We ended up bumping our react quill version to v2 beta which solved the issue.

**Comment by nadrianfikri** [comment]
I have the same issue

**Comment by maxstue** [comment]
@nadrianfikri I reinstalled the 2.0.0-beta.4 Version and than the problem was gone🤔

**Comment by Afonker** [comment]
<img width="418" alt="image" src="https://user-images.githubusercontent.com/37506445/170488499-865dc945-7a0d-4dd8-b52b-b25007149d64.png">
I solved it this way

**Comment by GavinThomas1192** [comment]
@b-hexsoul discovered that after upgrading to react-18 we needed to add the prop preserveWhitespace to our <ReactQuill instance.

**Comment by Aveline67** [comment]
this looks ok for me :

``` tsx
    const ref = React.createRef<ReactQuill>()

    useEffect(() => {
        let x = ref.current?.getEditor();
        if (x) {
            x.on('text-change', function (delta, oldDelta, source) {
                let innerHtml = x?.root.innerHTML;
                if (innerHtml)
                   console.log(innerHtml)
            })
        }
    }, [])
    
        return (<>
            <ReactQuill
                ref={ref}
                theme="snow"
                value={props.value} />
        </>);
```

**Comment by thatgriffith** [comment]
I did like @taochu and @maxstue and upgraded to beta and everything worked again. I had updated a project to React 18 which introduced this bug. Didn't have to change anything else in the code, only updating the package and running the project again. Thanks guys!

**Comment by maxstue** [comment]
@Inakitajes nobody really knows, thats why I created an Issue at my current Project/Company to switch to another editor (lexical from facebook looks really goot ;) )

**Comment by ismaelrodino2** [comment]
try adding  preserveWhitespace property.
ex: <ReactQuill value={value} onChange={setValue} preserveWhitespace />

**Comment by amrbahnas** [comment]
Controlling Component using defaulValue instead of Value prop, work fine for me 
   ```
<ReactQuill
     defaultValue={content}
     onChange={onChange}
   />
```
