### ISSUE TITLE
React Quill does not install on React 18 

### ISSUE THREAD

**Issue by AbobkerElaghel** [zenoamaro/react-quill#799]
### Ticket due diligence
- [ ] I have verified that the issue persists under ReactQuill `v2.0.0-beta.2`

### ReactQuill version
- [ ] v2.0.0-beta.4

Windows 11
Node 16

$ npm i react-quill@2.0.0-beta.4
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-app@0.1.0
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"^18.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16 || ^17" from react-quill@2.0.0-beta.4
npm ERR! node_modules/react-quill
npm ERR!   react-quill@"2.0.0-beta.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Abobk\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Abobk\AppData\Local\npm-cache\_logs\2022-05-21T12_56_03_661Z-debug-0.log

**Comment by SabrinaDanielle** [comment]
I’m wondering the same, did everyone else using React 18 force the install despite the required peer deps being 17 || 18

**Comment by zhao605207225** [comment]
npm i react-quill --save --force ,this can be installed,Looking forward to a better solution.

**Comment by DevJordanW** [comment]
I force installed on 18.1 and i'm getting some weird bugs so I just had to uninstall and look for another package until Quill gets updated.

**Comment by jake-johnson-kenzie** [comment]
@DevJordanW Did you end up finding a compatible alternative that was easy to migrate to?

**Comment by kemikal** [comment]
I tried ckeditor with react! No problems!

**Comment by DevJordanW** [comment]
> @DevJordanW Did you end up finding a compatible alternative that was easy to migrate to?

Not yet, thankfully my project is still in development so I have some time, I hear ckeditor and draftjs are popular so I might dig into those

**Comment by binyamindavid** [comment]
Any fix for this?

**Comment by jainPrajwal** [comment]
Is there any fix other than force installing the package..?

**Comment by ming0624** [comment]
I have the same issue

**Comment by heegu0311** [comment]
Same issue on my project..

**Comment by jainPrajwal** [comment]
> I have the same issue

I finally force installed it. Didn't face any issue as such in my side project

**Comment by Dayo-Adewuyi** [comment]
what is the solution to this issue? currently facing the same thing

**Comment by Pytez** [comment]
STILL WAITING FOR A SOLUTION IN 2025!!!!!!!!!!!!!!!!!

**Comment by scofield144** [comment]
Hi dev, still waiting.
