### ISSUE TITLE
s.th. wrong with the toolbar

### ISSUE THREAD

**Issue by freder** [zenoamaro/react-quill#8]
hi,

I just tried to use react-quill, but something is not quite right with the toolbar:

![screen shot 2015-05-28 at 11 07 52](https://cloud.githubusercontent.com/assets/724844/7856554/5b964d28-052a-11e5-9f32-ac006cd7aebd.png)

also I get this console warning:

```
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of Quill Toolbar. See https://fb.me/react-warning-keys for more information.
```

here's how I use it:

```
<ReactQuill
	ref='bio'
	value={this.state.form.bio}
	onChange={ function(value) { that.handleChangeRichtext('bio', value) } }
/>
```

not sure what I'm doing wrong here...

**Comment by zenoamaro** [comment]
Hi, let me ask you a few questions to be sure:

Are you using the distributable `dist/react-quill.js` or browserify/webpack?

Which version of React and React-quill are you including?

Can you compare your implementation with this one? http://zenoamaro.github.io/react-quill/

**Comment by freder** [comment]
I'm using browserify.
`react@0.13.3`
`react-quill@0.1.1`

will have a look at the demo after lunch.

**Comment by zenoamaro** [comment]
Is it possible that you aren't including Quill's stylesheet? I admit the documentation is not clear at all about this requirement.

~~~html
<link rel="stylesheet" href="../node_modules/quill/dist/quill.snow.css">
~~~

About the `key` prop warning: yes, it's the toolbar separators, which I haven't found a good key for yet. It's a harmless warning though. It doesn't appear when building for production, and you can safely ignore that for now. I'll try to fix that somewhere in the next few days.

**Comment by freder** [comment]
you're right, I hadn't included the original `quill` files. that and setting `theme='snow'` did it for me. — thanks!

**Comment by zenoamaro** [comment]
Thanks, I'll add a note for that in the docs later!
