### ISSUE TITLE
In   "react": "^18.0.0",`  <React.StrictMode><App /></React.StrictMode>` show two controllers appear

### ISSUE THREAD

**Issue by RSS1102** [zenoamaro/react-quill#804]
In `  <React.StrictMode><App /></React.StrictMode>`
![image](https://user-images.githubusercontent.com/81673017/171253697-0ac6a4b1-53ea-49cc-b1de-aa39123ff28b.png)

**a waring:**
chunk-Q2XSVQRF.js?v=2319fa03:519 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Quill
printWarning @ chunk-Q2XSVQRF.js?v=2319fa03:519
chunk-Q2XSVQRF.js?v=2319fa03:519 Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Quill

**Comment by RSS1102** [comment]
i must be don't use  `<React.StrictMode><App /></React.StrictMode>`
use `App />`，it will be normal

**Comment by korany-lee** [comment]
this issue fixed #793
And also we are waiting react 18 version peer dependency allowed. #781
