### ISSUE TITLE
Unable to install react-quill on React "18.1.0"

### ISSUE THREAD

**Issue by ishan-im** [zenoamaro/react-quill#815]
Hello,
I am unable to installing react-quill on my project where react verstion is "18.1.0"

here is the error code:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree       
npm ERR!
npm ERR! While resolving: git-node@0.1.0
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"18.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16 || ^17" from react-quill@2.0.0-beta.4
npm ERR! node_modules/react-quill
npm ERR!   react-quill@"2.0.0-beta.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry   
npm ERR! this command with --force, or --legacy-peer-deps 
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ishan\AppData\Local\npm-cache\_logs\2022-06-29T03_00_20_369Z-debug.log

any solution 😭?

**Comment by kemikal** [comment]
I need this too to deploy
This seems to be fixed in PR 781

Local dev you can force install

npm i react-quill --save --force
