### ISSUE TITLE
Publish latest changes as new 2.0.0 beta to support React 19

### ISSUE THREAD

**Issue by fabb** [zenoamaro/react-quill#821]
React 18 support was added in https://github.com/zenoamaro/react-quill/pull/793, but has not yet been published as a new beta version yet. Please publish as new version, thanks!

**Comment by darwin808** [comment]
@g12i @fabb 
Any updates on this?

**Comment by g12i** [comment]
Hi @darwin808 I don't have write or publish access so I can't really tell. But I'd suggest to merge #822 before publishing it.

**Comment by blendPOS** [comment]
Would really like for this to be updated as well!

**Comment by alexkrolick** [comment]
Sorry that took a while, thanks for the fixes @g12i 

v2.0.0 is published
