### ISSUE TITLE
Not working on ES6

### ISSUE THREAD

**Issue by thanhthang20** [zenoamaro/react-quill#83]
![screen shot 2016-03-18 at 12 21 43 pm](https://cloud.githubusercontent.com/assets/5382700/13869150/0ea61d28-ed04-11e5-9391-b9cb88a58694.png)

**Comment by parduhn** [comment]
ES6 works for me:

```
"use strict";
import React from 'react';
import ReactQuill from 'react-quill';
import '../../node_modules/react-quill/node_modules/quill/dist/quill.base.css';
import '../../node_modules/react-quill/node_modules/quill/dist/quill.snow.css';

export default class Editor extends React.Component {
     render() {
            return ( <ReactQuill {...this.props} theme="snow"
                                               value={this.props.body}
                                               onChange={this.props.onChange}/>
                       )
    }
}
```

**Comment by zenoamaro** [comment]
Yeah, can't see any reason why it shouldn't work. This could be a bug elsewhere; do you have a test case which reproducing the issue?

**Comment by thanhthang20** [comment]
I found the problem. I downloaded the react-quill zip folder, so it missed 
` "dependencies": {
    "quill": "^0.20.1"
  },`

Anyway to install react-quill with npm?

**Comment by zenoamaro** [comment]
`npm install react-quill` should suffice

**Comment by zenoamaro** [comment]
Closed for inactivity. 

Feel free to reopen should you still encounter this issue.

**Comment by teqsk1514** [comment]
whenever i m using

`import ReactQuill from 'react-quill';`

I am getting this error
 
![screenshot 90](https://user-images.githubusercontent.com/23125071/44641183-5f84a900-a9e3-11e8-8ea2-1c181cbcd05e.png)



Please Help me out

**Comment by alexkrolick** [comment]
I think you need to add the `prop-types` peer dependency

**Comment by alexkrolick** [comment]
```npm install --save prop-types```

**Comment by teqsk1514** [comment]
i did that also but the same error is coming
