### ISSUE TITLE
Can Quill be used as an HTML editor?

### ISSUE THREAD

**Issue by 3den** [zenoamaro/react-quill#84]
I loved Quill, but on the project that i am working we need an editor that supports both WYSIWYG  and pure HTML...  Is there some plugin for quill that supports editing HTML code directly?

**Comment by zenoamaro** [comment]
You can use Quill to present and edit the rendered HTML, but you can also edit the same HTML with a proper code editor like CodeMirror, and even edit the same HTML side-by-side.

Just have a container component keeping track of your document, and have it switch between a Quill editor and a CodeMirror editor. Or maybe even display them side-by-side. Kind of how it works in the demo.

Would that be clear enough?

**Comment by satyadeeproat** [comment]
Hi, I am doing a basic crud operation. So I am writing some text using Quill editor, and then after it's done. I am adding some CSS as I have to show it as a page. IT works fine. But when I edit the page again, the css classes I add automatically vanishes as I guess Quill doesn't allow the CSS to work. How to sort out the problem

**Comment by alexkrolick** [comment]
You would need to apply the same CSS to the .quill or .ql-editor classes
