### ISSUE TITLE
how to add some new tag, like 'code', 'blockquote'

### ISSUE THREAD

**Issue by YuxinChou** [zenoamaro/react-quill#85]
Hi, I want to add some new toolbar, like 'code', 'blockquote'.
But, how to add these functions? 
need modify quill.js？

Thank you.

**Comment by Nazanin1369** [comment]
There is a pull request up for supporting code blocks: #98

**Comment by zenoamaro** [comment]
With the switch to Quill v1, this is now done using Parchment instead. Please refer to [the Parchment guide](https://github.com/quilljs/parchment/) for further information.
