### ISSUE TITLE
CSS height attribute can break react-quill

### ISSUE THREAD

**Issue by stevenarnold** [zenoamaro/react-quill#86]
In page with multiple react-quill components, setting a CSS height on the components seems to break all the components after the first one.

See https://jsfiddle.net/thothamonibis/gL2x0dnj/1/
The most important aspect is the CSS setting the height at the top of the CSS section.  If you remove this, the react-quill components behave correctly.

Note I am very new to both react and react-quill, so I might be missing something obvious, but this seems wrong to me.

**Comment by therealparmesh** [comment]
I believe there is something wrong with the styling. I'm seeing 'height: 100%' instead of what I think should be something flex-based for the children of the main div.

**Comment by zenoamaro** [comment]
This should be fixed in the latest version, as it has been updated to Quill v1.

Can you verify using the latest `master`?
