### ISSUE TITLE
Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>

### ISSUE THREAD

**Issue by parduhn** [zenoamaro/react-quill#87]
Since I updated all import to the most current version I get the "Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>." in the console log as soon as the react-quill component is mounted.

**Comment by AlexKovalevych** [comment]
getting the same error

**Comment by zhang-z** [comment]
hi, did you install through master branch or v0.4.1 ? It's supposed to be fixed in pull request #73 . Not released yet

**Comment by AlexKovalevych** [comment]
Yes, i've reinstalled it with:

```
npm i git+https://github.com/zenoamaro/react-quill.git
```

and error has gone, thanks!

**Comment by zenoamaro** [comment]
Sorry about the delay. The fix will be out soon.

**Comment by sahanDissanayake** [comment]
still has error. Could you please give us an ETA for the new release ?

thanks

**Comment by Jock924491** [comment]
I am having error with this as well

**Comment by patotoma** [comment]
+1

**Comment by SteveOscar** [comment]
+1

**Comment by GuillaumeCisco** [comment]
+1

**Comment by sarkistlt** [comment]
+ 1 'master branch'
When will you update npm?

**Comment by theguxi** [comment]
+1
npm package still not updated

**Comment by Promphut** [comment]
+1
npm package still not updated

**Comment by YouHan26** [comment]
+1
npm package still not updated

**Comment by apers** [comment]
+1
npm package

**Comment by altayaydemir** [comment]
+1 for npm package 🤔

**Comment by acomito** [comment]
+1

**Comment by intpp** [comment]
@zenoamaro can you update npm package?

last version in npm - 0.4.1, in current package.json 2.0.1

**Comment by tape88** [comment]
npm - 0.4.1 still broken,
npm i git+https://github.com/zenoamaro/react-quill.git - solution

**Comment by GuillaumeCisco** [comment]
@zenoamaro is it possible to get the 1.0.0 release from the npm registry?

**Comment by sarkistlt** [comment]
`npm i -S react-quill@1.0.0-beta-1`

**Comment by volkandkaya** [comment]
I'm getting this error on v1.2.3. Any way to fix it?

**Comment by miukimiu** [comment]
@volkandkaya I was getting the same error and fix it this way:
```
<select className="ql-size" value={this.state.fontSize} onChange={this.handleFontSizeChange}>
  <option value="extra-small">Extra Small</option>
  <option value="small">Small</option>
  <option value="medium">Medium</option>
  <option value="large">Large</option>
</select>
```
You can read more about this issue here:
[https://reactjs.org/docs/forms.html](https://reactjs.org/docs/forms.html)

The way to solve it is to put a **value** on the select tag and then have a **handleFontSizeChange** function:

```
handleFontSizeChange(event) {
    this.setState({
      fontSize: event.target.value,
    });
  }
```
