### ISSUE TITLE
unprivilegedEditor methods are always undefined

### ISSUE THREAD

**Issue by vdrg** [zenoamaro/react-quill#88]
I need to get the editor's contents in a Delta object but the object created by makeUnprivilegedEditor, which exposes the method getContents(), doesn't seem to work (it's methods always return undefined).
Thanks!

**Comment by jimf** [comment]
This was fixed in 58d68e2. Any chance of a new version getting published?

**Comment by zenoamaro** [comment]
Fixed with #130.
