### ISSUE TITLE
When playing with bold and italic cursor losing its current location

### ISSUE THREAD

**Issue by asvsfs** [zenoamaro/react-quill#9]
When hit bold couple of times when writing cursor will move back to the last position that bold is used.

**Comment by zenoamaro** [comment]
Hi, what browser are you testing on?

This may be a bug on Quill proper, does it also happen here? https://quilljs.com/

**Comment by asvsfs** [comment]
Chrome latest version

Bests
Amir

**Comment by asvsfs** [comment]
No Its okay when using it from website , but it happens when using it with React

**Comment by zenoamaro** [comment]
Latest version handles events in a different way, so that should do it. Let me know if it doesn't.

**Comment by OlegWock** [comment]
Hello @zenoamaro I faced this problem (tried beta too with same result). I have same component (which includes react-quill editor) inside Shadow DOM and inside ordinary page and it breaks only on shadow dom. I would be very grateful if you advise me how I can get around this issue or how I can debug it and help with fixing
