### ISSUE TITLE
Good job on ReactQuill 2.0

### ISSUE THREAD

**Issue by Etheryte** [zenoamaro/react-quill#916]
Thanks a lot for your work on version 2.0. I needed to upgrade a project that was on a version that was over three years old and the upgrade was as simple as bumping the version number in `package.json`. No regressions, no nothing. This literally never happens in the npm ecosystem, so I wanted to say thank you for your work, this really was a drop-in replacement.

**Comment by alexkrolick** [comment]
Thank you for comment! Glad it works for you.
