### ISSUE TITLE
code blocks

### ISSUE THREAD

**Issue by Nazanin1369** [zenoamaro/react-quill#92]
Is there a plan to roll out adding code blocks?

Since Quilljs has added code blocks support in its beta release: 
https://github.com/quilljs/quill/issues/116

The first thing is to make react-quill compatible with Quilljs version 1.0. Here is a guide to upgrade:http://beta.quilljs.com/guides/upgrading-to-1-0/

Shall I put up a pull request for this?

**Comment by Nazanin1369** [comment]
Pull Request #98

**Comment by alexkrolick** [comment]
Appears to be working with demo on master: https://zenoamaro.github.io/react-quill/

**Comment by CristinaWang** [comment]
The code-block feature seems not working anymore in the latest version. Got warning: "quill:toolbar ignoring attaching to disabled format code-block". Is this feature deprecate?

**Comment by alexkrolick** [comment]
You need to add the format to the formats prop

**Comment by CristinaWang** [comment]
Yeah, I figure out after I added the comments so I delete it. Thank you.

**Comment by jagadishreddykovvuri** [comment]
fgg`cddcd`
