### ISSUE TITLE
import { Quill } from 'react-quill' : document is not defined 

### ISSUE THREAD

**Issue by Minhnhat0408** [zenoamaro/react-quill#923]
So I'm using nextjs app 13.5.3-canary.3 and typescript with react-quill 2.0.0 
So I want to use both ImageResizer and ImageUploader from [quill-image-resize-module-react](https://www.npmjs.com/package/quill-image-resize-module-react) and [quill-image-uploader](https://github.com/NoelOConnell/quill-image-uploader) 
Hence I need to use {Quill} (not ReactQuill) from 'react-quill' 
<img width="404" alt="image" src="https://github.com/zenoamaro/react-quill/assets/63915841/6f46308e-1daf-45b0-b4f2-9f77b979e7b8">

THe current bug with the import 
<img width="703" alt="image" src="https://github.com/zenoamaro/react-quill/assets/63915841/dfeae2a0-a764-4419-8650-bf7b6efe06cf">
How I 've tried to import it to avoid the bug 
<img width="844" alt="image" src="https://github.com/zenoamaro/react-quill/assets/63915841/8831d519-591b-4b70-aa14-5c19cdcf8818">
but it have another issues with type 
<img width="706" alt="image" src="https://github.com/zenoamaro/react-quill/assets/63915841/d75da053-6f8d-4244-84fe-bbb6938fda8f">

Do you guys know how I can fix it or may be the workaround of it. 
I just want to have a text editor with image resizer and uploader. Hope u guys can help me.

**Comment by Minhnhat0408** [comment]
For anyone who still stuck on the part to implement 2 aforementioned modules image resize and image uploader for react quill.
I 've fixed it by **import the {Quill} inside UseEffect**. Because apparently useEffect renders when the dom has been loaded:
here my code:
<img width="760" alt="image" src="https://github.com/zenoamaro/react-quill/assets/63915841/413f8786-825e-4ec4-9f4f-6c87f45a23d9">

rememer to have a **loaded useState** and set it to truee in the end of the useEffect and have the **render <ReactQuill> when loaded is true :**

<img width="775" alt="image" src="https://github.com/zenoamaro/react-quill/assets/63915841/ba31ebce-fcdf-4f5f-87ae-19cd4a512d48">

**Comment by ButzkeGWG** [comment]
You can try this:

![image](https://github.com/zenoamaro/react-quill/assets/126742508/1445c54a-17f0-4975-8376-b7e199387695)
