### ISSUE TITLE
Bump version to Quill 1.0?

### ISSUE THREAD

**Issue by clemmy** [zenoamaro/react-quill#93]
Quill 1.0.0-beta.1 has been released and it contains many bug fixes. There are some breaking changes listed here: http://beta.quilljs.com/guides/upgrading-to-1-0/. Are there plans for a version bump soon?

**Comment by clemmy** [comment]
I'm working on a pull request here: https://github.com/wifast/react-quill

**Comment by Nazanin1369** [comment]
I have already upgraded the Quill to 1.0.0-beta.2 in my pull request here:
https://github.com/zenoamaro/react-quill/pull/98

**Comment by clemmy** [comment]
Hello Nazanin, I checked out your pull request and although it is working, it doesn't allow font family and font size customization like the previous version from what I can see. I also submitted a pull request here: https://github.com/zenoamaro/react-quill/pull/99, but I am still working out some bugs. However, it is for the most part complete, and you can check out the demo here: http://wifast.github.io/react-quill/

**Comment by Nazanin1369** [comment]
Hi Clement,

I do not see the clode blocks implemented in your demo.
So since we have a wrapper around Quill itself we can change the font
family and size customization to stat the same. But is that a requirement?
Either we can have another commit to make it work with previous font size
if it is.


On Thursday, May 26, 2016, Clement Hoang <notifications@github.com> wrote:

> Hello Nazanin, I checked out your pull request and although it is working,
> it doesn't allow font family and font size customization like the previous
> version from what I can see. I also submitted a pull request here: #99
> <https://github.com/zenoamaro/react-quill/pull/99>, but I am still
> working out some bugs. However, it is for the most part complete, and you
> can check out the demo here: http://wifast.github.io/react-quill/
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/zenoamaro/react-quill/issues/93#issuecomment-222035448>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGFV2CMfIR71beo9kpjoHC8F8i_XXH_yks5qFkKWgaJpZM4Icg5d>
> .
>


-- 
Best Regards,

**Comment by Nazanin1369** [comment]
Are you guys having slack channel for communication on this repo?

**Comment by Nazanin1369** [comment]
I see you upgraded to beta.3. I think we can merge my pull request first. Which will upgrade to beta.2 and support code blocks and then you merge yours on top of mine which will support your customizable fonts and also upgrade it to beta.3 beside my code block support. That would resolve all

**Comment by clemmy** [comment]
Hi Nazanin, I'm not aware of any slack channel for communication at this point in time. In terms of whether it is required or not, I am simply following the behavior this project previously had. We should see if @zenoamaro has any input on this, and where he wants the direction of react-quill to go.

**Comment by Nazanin1369** [comment]
Sure, I also can put up another PR after you have merged your pull request only for code blocks if you are willing to merge your upgrade.

**Comment by MasahiroMorita** [comment]
I'm looking forward to this! I really need this version of Quill.

**Comment by thomas-jeepe** [comment]
Updates?

**Comment by clemmy** [comment]
@MasahiroMorita @thomas-jeepe There is a working version I wrote located here: https://github.com/zenoamaro/react-quill/pull/99. However, it doesn't expose the API for settings custom formats yet.

**Comment by thomas-jeepe** [comment]
Alright, thanks for the response

**Comment by alexkrolick** [comment]
https://github.com/alexkrolick/react-quill

Added support for using modules to configure toolbar, formats, keyboard, etc.

@clemmy @MasahiroMorita @thomas-jeepe

**Comment by zenoamaro** [comment]
Thanks to the great work of @clemmy and @alexkrolick, ReactQuill is now updated to Quill 1.0. 

Closing this in favor of #113.
