### ISSUE TITLE
React Quill - How to prevent default behaviour of enter key?

### ISSUE THREAD

**Issue by frdomovic** [zenoamaro/react-quill#936]
# React Quill - How to prevent default behaviour of enter key?

Using ReactQuill v2.0.0-beta.2 or v2.0.0

```
  onKeyDown(e) {
    if (e.key === 'Enter') {
      e.preventDefault();
      return false; // does nothing
    }
  ...
   <ReactQuill onKeyDown={onKeyDown.bind(this)} ... />
```
Doesn't prevent default behaviour and while using bindings like this: 

```
<ReactQuill
      modules={{
        keyboard: {
          bindings: {
                  enter: {
                      key: 13,
                      handler: () => {/* do nothing */}
                  }
              }
      }
      }}
     ...
    />
```
Causes `TypeError: Cannot read properties of undefined (reading 'delta')`

**Comment by frdomovic** [comment]
see [919](https://github.com/zenoamaro/react-quill/issues/919)

**Comment by tchen-l** [comment]
try this
```
<div
  onKeyDownCapture={(e) => {
    if (e.code === 'Enter') {
      e.preventDefault()
    }
  }}
>
  <ReactQuill />
</div>
```

**Comment by Hujinna** [comment]
> try this
> 
> ```
> <div
>   onKeyDownCapture={(e) => {
>     if (e.code === 'Enter') {
>       e.preventDefault()
>     }
>   }}
> >
>   <ReactQuill />
> </div>
> ```

It wokers well.

> ```
> const modules = useMemo(
>    () => ({
>      toolbar: false,
>      keyboard: {
>        bindings: {
>          linebreak: {
>            key: 13,
>            shiftKey: true,
>            handler: (range: { index: number }) => {
>              const editor = ReactQuillRef.current?.getEditor();
>              editor?.setSelection(range.index, 'silent');
>              editor?.insertText(range.index, '\n', 'user');
>              editor?.setSelection(range.index + 1, 'silent');
>              editor?.format('linebreak', true, 'user');
>            },
>         },
>    }),
>   [ReactQuillRef]
>  );
> ```
> ```
>  const handleKeyDown = (e) => {
>    if (e.keyCode === 13 && (e.shiftKey || e.metaKey || e.ctrlKey)) {
>      console.log('换行');
>    } else if (e.code === 'Enter' && !isTyping) {
>      e.preventDefault();
>      e.stopPropagation();
>      handleSend();
>    }
>  };
> ```
> ```
> <div
>      onKeyDown={handleKeyDown}
>      onCompositionStart={() => setIsTyping(true)}
>      onCompositionEnd={() => setIsTyping(false)}
>    >
>      <ReactQuill
>        ref={ReactQuillRef}
>        theme="snow"
>        value={text}
>        formats={['bold', 'italic', 'underline', 'video', 'image', 'link']}
>        modules={modules}
>        onChange={setText}
>      />
> </div>
> ```

**Comment by sakshijha8** [comment]
<ReactQuill
        preserveWhitespace
        readOnly={readOnly}
        ref={ref}
        value={value || ""}
        onChange={onChange}
        placeholder={placeholder}
        formats={formats}
        className={className}
        modules={{
          ...mutatedToolbar,
          keyboard: {
            bindings: {
              sendMessage: {
                key: 13,
                handler: (range, context) => {
                  if (value && value.trim()) {
                    handleSendMessage();
                    ref.current.getEditor().setText("");
                  }
                  return false;
                },
              },
              preventLeadingSpace: {
                key: 32,
                handler: (range, context) => {
                  const editor = ref.current.getEditor();
                  const textBefore = editor.getText(0, range.index);
                  if (!textBefore.trim()) {
                    return false;
                  }
                  return true;
                },
              },
            },
          },
          mention: {
            allowedChars: /^[A-Za-z\s]*$/,
            mentionDenotationChars: ["@", "#"],
            source: sourceFxn,
          },
        }}
        theme="snow"
      />

This works well for me.
