### ISSUE TITLE
Support for placeholder value

### ISSUE THREAD

**Issue by samdturner** [zenoamaro/react-quill#95]
I'd like to suggest adding support for a placeholder prop.

I am trying to add a placeholder by using a hack with CSS and setting a title attribute on the contenteditable html tag:

```
[contentEditable=true]:empty:not(:focus):before{
   content:attr(title);
}
```

```
// within a component that wraps ReactQuill

componentDidMount() {
  document.getElementById('ql-editor-1').setAttribute('title', 'Job Description');
}
```

Even after implementing this hack, the placeholder still does not appear because the default markup inside of the content editable div is not actually an empty string.

```
<div class="ql-editor" id="ql-editor-1" contenteditable="true" title="Job Description">
  <div>
    <br>
  </div>
</div>
```

I'd also appreciate any other suggestions of how to get a placeholder value using the current implementation.

**Comment by alexkrolick** [comment]
This is supporting in the upcoming Quill release, v1.0.0.

**Comment by zenoamaro** [comment]
Placeholder value is now supported in the latest `master`.
