### ISSUE TITLE
Can I set myself boundsContainer in Tooltip?

### ISSUE THREAD

**Issue by win9s** [zenoamaro/react-quill#974]
When I set the left element in a modal div ( antd modal ) , the tooltip is partially hidden, the `left` attributes is miscalculated

I looked through the source code and found that the boundsContainer was set incorrectly in Tooltip constructor .

**Comment by myt588** [comment]
any updates here? experiencing the same thing 🤔

**Comment by myt588** [comment]
> any updates here? experiencing the same thing 🤔

in case anyone else is looking for solution:

`
    <ReactQuill
        style={{
          flex: 1,
          display: `flex`,
          flexDirection: `column`,
          overflow: `hidden`,
        }}
        theme="snow"
        value={value}
        onChange={handleChange}
        modules={modules}
        formats={formats}
        bounds=".quill-container"
      />
`

you can add a bounds props to resolve this issue. cheers

**Comment by yinyoude** [comment]
Use bounds in antd modal is not working:https://github.com/ant-design/ant-design/issues/39333
react-quill should render after ant modal,like this:
`
const MyQuill = () => {
  const [enabled, setEnabled] = React.useState(false);
  React.useEffect(() => {
    setEnabled(true);
  }, []);

  return enabled ? (
    <div className="quill-bounds">
      <ReactQuill
        theme="snow"
        bounds=".quill-bounds"
        modules={{
          toolbar: {
            container: [["link"]],
            theme: "snow",
          },
        }}
      />
    </div>
  ) : null;
};
`
